### ISSUE TITLE
conjure-up fails with json cannot unmarshall ApplicationDeploy.num-units.

### ISSUE THREAD

**Issue by hmlanigan** [conjure-up/conjure-up#1001]
I did a conjure-up of the openstack-novalxd bundle, however I used configure to attempt to set the openstack-dashboard units to 0 as I don't want to use it.  You can leave the field blank, but not set to 0.  Blank produces the following error:

2017-06-25 22:46:45,949 [INFO] conjure-up/openstack-novalxd - juju.model: model.py:1180 - Deploying cs:openstack-dashboard-246
2017-06-25 22:46:45,951 [DEBUG] conjure-up/openstack-novalxd - events.py:52 - Setting Error at conjureup/events.py:143
2017-06-25 22:46:46,009 [ERROR] conjure-up/openstack-novalxd - events.py:162 - Unhandled exception
Traceback (most recent call last):
  File "/snap/conjure-up/516/lib/python3.6/site-packages/conjureup/controllers/deploy/gui.py", line 245, in _do_deploy
    await juju.deploy_service(application, default_series, msg_cb=msg_cb)
  File "/snap/conjure-up/516/lib/python3.6/site-packages/conjureup/juju.py", line 622, in deploy_service
    app_inst = await app.juju.client.deploy(**deploy_args)
  File "/snap/conjure-up/516/lib/python3.6/site-packages/juju/model.py", line 1141, in deploy
    placement=parse_placement(to)
  File "/snap/conjure-up/516/lib/python3.6/site-packages/juju/model.py", line 1204, in _deploy
    result = await app_facade.Deploy([app])
  File "/snap/conjure-up/516/lib/python3.6/site-packages/juju/client/facade.py", line 392, in wrapper
    reply = await f(*args, **kwargs)
  File "/snap/conjure-up/516/lib/python3.6/site-packages/juju/client/_client5.py", line 503, in Deploy
    reply = await self.rpc(msg)
  File "/snap/conjure-up/516/lib/python3.6/site-packages/juju/client/facade.py", line 514, in rpc
    result = await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/snap/conjure-up/516/lib/python3.6/site-packages/juju/client/connection.py", line 267, in rpc
    raise JujuAPIError(result)
juju.errors.JujuAPIError: json: cannot unmarshal string into Go struct field ApplicationDeploy.num-units of type int
2017-06-25 22:46:46,012 [DEBUG] conjure-up/openstack-novalxd - __init__.py:21 - Showing dialog for exception: json: cannot unmarshal string into Go struct field ApplicationDeploy.num-units of type int

 snap info conjure-up
name:      conjure-up
summary:   "Package runtime for conjure-up spells"
publisher: canonical
contact:   https://github.com/conjure-up/conjure-up
description: |
  This package provides conjure-up, an interface to installing spells that
  provide the user with an end to end walkthrough experience for installing and
  using big software.

commands:
  - conjure-up.conjure-down
  - conjure-up
  - conjure-up.juju
  - conjure-up.lxc
  - conjure-up.lxd
  - conjure-up.redis-cli
tracking:           edge
installed:          2.3-alpha1-20170623.2206 (516) 92MB classic
refreshed:          2017-06-23 18:35:07 -0400 EDT
channels:
  latest/stable:    2.2.2                    (510) 92MB classic
  latest/candidate: 2.2.2                    (510) 92MB classic
  latest/beta:      2.2.2                    (510) 92MB classic
  latest/edge:      2.3-alpha1-20170623.2206 (516) 92MB classic

**Comment by battlemidget** [comment]
@hmlanigan thanks for the report!
