### ISSUE TITLE
conjure-up on bonded network interface could not find a suitable physical network interface to create a LXD bridge on.

### ISSUE THREAD

**Issue by chrone81** [conjure-up/conjure-up#1044]
Does conjure-up have network interface limitation such as not working on lacp bond, vlan, and bridge interfaces?

I got this error message when firing up conjure-up openstack on localhost although with or without lxdbr0 bridge interface from the "lxd init".

`Could not find a suitable physical network interface to create a LXD bridge on.`

```
/snap/bin/juju
/snap/bin/conjure-up
/snap/bin/conjure-up.lxd
2.2.1-xenial-amd64
conjure-up 2.2.2
2.14
config: {}
user@node10:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
```

```
2017-07-19 09:39:49,198 [DEBUG] conjure-up/openstack-novalxd - download.py:60 - Path is local filesystem, copying /snap/conjure-up/549/spells/openstack-novalxd to /home/user/.cache/conjure-up/openstack-novalxd
2017-07-19 09:39:51,851 [DEBUG] conjure-up/openstack-novalxd - utils.py:581 - Parsing 3: enp8s0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond0 state UP group default qlen 1000
    link/ether 00:25:90:58:b6:a0 brd ff:ff:ff:ff:ff:ff
 for IPv4 address
2017-07-19 09:39:51,858 [DEBUG] conjure-up/openstack-novalxd - utils.py:581 - Parsing 2: enp7s0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond0 state UP group default qlen 1000
    link/ether 00:25:90:58:b6:a0 brd ff:ff:ff:ff:ff:ff
 for IPv4 address
2017-07-19 09:39:51,933 [DEBUG] conjure-up/openstack-novalxd - utils.py:581 - Parsing 3: enp8s0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond0 state UP group default qlen 1000
    link/ether 00:25:90:58:b6:a0 brd ff:ff:ff:ff:ff:ff
 for IPv4 address
2017-07-19 09:39:51,941 [DEBUG] conjure-up/openstack-novalxd - utils.py:581 - Parsing 2: enp7s0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond0 state UP group default qlen 1000
    link/ether 00:25:90:58:b6:a0 brd ff:ff:ff:ff:ff:ff
 for IPv4 address
2017-07-19 09:39:51,951 [DEBUG] conjure-up/openstack-novalxd - events.py:55 - Setting Error at conjureup/events.py:147
2017-07-19 09:39:52,114 [ERROR] conjure-up/openstack-novalxd - events.py:166 - Unhandled exception
Traceback (most recent call last):
  File "/snap/conjure-up/549/usr/lib/python3.6/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/snap/conjure-up/549/lib/python3.6/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/snap/conjure-up/549/lib/python3.6/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/snap/conjure-up/549/lib/python3.6/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/snap/conjure-up/549/lib/python3.6/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/snap/conjure-up/549/lib/python3.6/site-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/snap/conjure-up/549/lib/python3.6/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/snap/conjure-up/549/lib/python3.6/site-packages/conjureup/ui/views/cloud.py", line 26, in keypress
    return super().keypress(size, key)
  File "/snap/conjure-up/549/lib/python3.6/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/snap/conjure-up/549/lib/python3.6/site-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/snap/conjure-up/549/lib/python3.6/site-packages/urwid/decoration.py", line 836, in keypress
    return self._original_widget.keypress((maxcol,), key)
  File "/snap/conjure-up/549/lib/python3.6/site-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/snap/conjure-up/549/lib/python3.6/site-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/snap/conjure-up/549/lib/python3.6/site-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/snap/conjure-up/549/lib/python3.6/site-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/snap/conjure-up/549/lib/python3.6/site-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/snap/conjure-up/549/lib/python3.6/site-packages/conjureup/ui/views/cloud.py", line 101, in submit
    self.cb(result.label)
  File "/snap/conjure-up/549/lib/python3.6/site-packages/conjureup/controllers/clouds/gui.py", line 27, in finish
    return controllers.use('regions').render()
  File "/snap/conjure-up/549/lib/python3.6/site-packages/conjureup/controllers/regions/gui.py", line 12, in render
    return self.finish(self.default_region)
  File "/snap/conjure-up/549/lib/python3.6/site-packages/conjureup/controllers/regions/common.py", line 47, in finish
    controllers.use('credentials').render()
  File "/snap/conjure-up/549/lib/python3.6/site-packages/conjureup/controllers/credentials/gui.py", line 20, in render
    self.finish(None)
  File "/snap/conjure-up/549/lib/python3.6/site-packages/conjureup/controllers/credentials/common.py", line 21, in finish
    controllers.use('lxdsetup').render()
  File "/snap/conjure-up/549/lib/python3.6/site-packages/conjureup/controllers/__init__.py", line 66, in use
    return module._controller_class()
  File "/snap/conjure-up/549/lib/python3.6/site-packages/conjureup/controllers/lxdsetup/common.py", line 39, in __init__
    self.ifaces = utils.get_physical_network_interfaces()
  File "/snap/conjure-up/549/lib/python3.6/site-packages/conjureup/utils.py", line 563, in get_physical_network_interfaces
    "Could not find a suitable physical network interface "
Exception: Could not find a suitable physical network interface to create a LXD bridge on. Please check your network configuration.
2017-07-19 09:39:52,129 [DEBUG] conjure-up/openstack-novalxd - __init__.py:21 - Showing dialog for exception: Could not find a suitable physical network interface to create a LXD bridge on. Please check your network configuration.
2017-07-19 09:40:01,566 [DEBUG] conjure-up/openstack-novalxd - events.py:55 - Setting Shutdown at conjureup/events.py:143
2017-07-19 09:40:01,569 [DEBUG] conjure-up/openstack-novalxd - events.py:55 - Received Shutdown at conjureup/events.py:180
2017-07-19 09:40:01,569 [INFO] conjure-up/openstack-novalxd - events.py:184 - Shutting down

```

**Comment by battlemidget** [comment]
@chrone81 If they should up as virtual interfaces then lxd can't bridge to it

**Comment by chrone81** [comment]
I see, well the bond and bond with vlan interfaces are all virtual, that's why. Thanks! :)
