### ISSUE TITLE
conjure-up does not work out-of-the-box in a minimal virtual machine installation - Could not determine LXD version

### ISSUE THREAD

**Issue by juliohm1978** [conjure-up/conjure-up#1062]
Just ran into this issue using Ubuntu 16.04.2 LTS as a VirtualBox guest.

To make things clear, in a full normal installation of the OS, `snapd` is already installed. Installing and using conjure-up works as expected.

However, it's quite common to install ubuntu using its Minimal Virtual Machine mode (F4 at the first boot screen). This obviously prevents extra packages from being installed, including `snapd` and `lxd`. In this scenario, simply installing `snapd` or `lxd` is not enough. I end up with the exact same issues reported on #683, from which none of the proposed solutions work.

I assumed from common sense that the `snapd` package would include enough dependencies, but I was wrong. So, I'm creating this issue to ask: **what packages exactly do I need to install to make conjure-up work in a Minimal Virtual Machine installation?** I'm pretty sure it's just missing something related to lxd, but I can't quite figure out what that is.

Below is a typical run of this scenario.

```
user@vmk8s:~$ sudo apt install snapd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  apparmor libapparmor-perl liblzo2-2 squashfs-tools
Suggested packages:
  apparmor-profiles apparmor-profiles-extra apparmor-docs apparmor-utils
The following NEW packages will be installed:
  apparmor libapparmor-perl liblzo2-2 snapd squashfs-tools
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 10.3 MB of archives.
After this operation, 60.3 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://br.archive.ubuntu.com/ubuntu xenial/main amd64 liblzo2-2 amd64 2.08-1.2 [48.7 kB]
Get:2 http://br.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libapparmor-perl amd64 2.10.95-0ubuntu2.6 [31.4 kB]
Get:3 http://br.archive.ubuntu.com/ubuntu xenial-updates/main amd64 apparmor amd64 2.10.95-0ubuntu2.6 [450 kB]
Get:4 http://br.archive.ubuntu.com/ubuntu xenial/main amd64 squashfs-tools amd64 1:4.3-3ubuntu2 [105 kB]
Get:5 http://br.archive.ubuntu.com/ubuntu xenial-updates/main amd64 snapd amd64 2.25 [9,706 kB]
Fetched 10.3 MB in 3s (3,067 kB/s) 
Preconfiguring packages ...
Selecting previously unselected package liblzo2-2:amd64.
(Reading database ... 82888 files and directories currently installed.)
Preparing to unpack .../liblzo2-2_2.08-1.2_amd64.deb ...
Unpacking liblzo2-2:amd64 (2.08-1.2) ...
Selecting previously unselected package libapparmor-perl.
Preparing to unpack .../libapparmor-perl_2.10.95-0ubuntu2.6_amd64.deb ...
Unpacking libapparmor-perl (2.10.95-0ubuntu2.6) ...
Selecting previously unselected package apparmor.
Preparing to unpack .../apparmor_2.10.95-0ubuntu2.6_amd64.deb ...
Unpacking apparmor (2.10.95-0ubuntu2.6) ...
Selecting previously unselected package squashfs-tools.
Preparing to unpack .../squashfs-tools_1%3a4.3-3ubuntu2_amd64.deb ...
Unpacking squashfs-tools (1:4.3-3ubuntu2) ...
Selecting previously unselected package snapd.
Preparing to unpack .../archives/snapd_2.25_amd64.deb ...
Unpacking snapd (2.25) ...
Processing triggers for systemd (229-4ubuntu19) ...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up liblzo2-2:amd64 (2.08-1.2) ...
Setting up libapparmor-perl (2.10.95-0ubuntu2.6) ...
Setting up apparmor (2.10.95-0ubuntu2.6) ...
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
diff: /var/lib/apparmor/profiles/.apparmor.md5sums: No such file or directory
Setting up squashfs-tools (1:4.3-3ubuntu2) ...
Setting up snapd (2.25) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Processing triggers for systemd (229-4ubuntu19) ...
Processing triggers for ureadahead (0.100.0-19) ...

user@vmk8s:~$ sudo snap install conjure-up --classic
2017-07-28T00:12:30-03:00 INFO cannot auto connect core:core-support-plug to core:core-support: (slot auto-connection), existing connection state "core:core-support-plug core:core-support" in the way
conjure-up 2.2.2 from 'canonical' installed

user@vmk8s:~$ conjure-up
Traceback (most recent call last):
  File "/snap/conjure-up/549/bin/conjure-up", line 11, in <module>
    load_entry_point('conjure-up==2.2.2', 'console_scripts', 'conjure-up')()
  File "/snap/conjure-up/549/lib/python3.6/site-packages/conjureup/app.py", line 256, in main
    utils.lxd_version(),
  File "/snap/conjure-up/549/lib/python3.6/site-packages/conjureup/utils.py", line 208, in lxd_version
    raise Exception("Could not determine LXD version.")
Exception: Could not determine LXD version.

### Changing the core to the beta channel makes no difference.

user@vmk8s:~$ sudo snap list
Name        Version     Rev   Developer  Notes
conjure-up  2.2.2       549   canonical  classic
core        16-2.26.14  2462  canonical  -

user@vmk8s:~$ sudo snap refresh core --beta
core (beta) 16-2.27 from 'canonical' refreshed

user@vmk8s:~$ sudo snap list
Name        Version  Rev   Developer  Notes
conjure-up  2.2.2    549   canonical  classic
core        16-2.27  2517  canonical  core

user@vmk8s:~$ conjure-up
Traceback (most recent call last):
  File "/snap/conjure-up/549/bin/conjure-up", line 11, in <module>
    load_entry_point('conjure-up==2.2.2', 'console_scripts', 'conjure-up')()
  File "/snap/conjure-up/549/lib/python3.6/site-packages/conjureup/app.py", line 256, in main
    utils.lxd_version(),
  File "/snap/conjure-up/549/lib/python3.6/site-packages/conjureup/utils.py", line 208, in lxd_version
    raise Exception("Could not determine LXD version.")
Exception: Could not determine LXD version.

### A familiar error appears with conjure-up.lxd.

user@vmk8s:~$ conjure-up.lxd --version
/snap/conjure-up/549/wrappers/lxd: 9: exec: aa-exec: not found

### And, strangely engouh, running conjure-up.lxd with sudo works.

user@vmk8s:~$ sudo conjure-up.lxd --version
2.14
```

**Comment by battlemidget** [comment]
Very interesting, `aa-exec` comes from the `apparmor` package. Can you check and see if that package is installed?

**Comment by juliohm1978** [comment]
Yes, `apparmor` is apparently installed.

```
user@ubuntu:~$ sudo apt install apparmor
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apparmor is already the newest version (2.10.95-0ubuntu2.6).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

user@ubuntu:~$ conjure-up
Traceback (most recent call last):
  File "/snap/conjure-up/549/bin/conjure-up", line 11, in <module>
    load_entry_point('conjure-up==2.2.2', 'console_scripts', 'conjure-up')()
  File "/snap/conjure-up/549/lib/python3.6/site-packages/conjureup/app.py", line 256, in main
    utils.lxd_version(),
  File "/snap/conjure-up/549/lib/python3.6/site-packages/conjureup/utils.py", line 208, in lxd_version
    raise Exception("Could not determine LXD version.")
Exception: Could not determine LXD version.
```

**Comment by battlemidget** [comment]
Oh I bet your path is different on a minimal install? What does `echo $PATH` show?

**Comment by juliohm1978** [comment]
Here it is:

```
user@ubuntu:~$ echo $PATH
/home/user/bin:/home/user/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin
```

**Comment by battlemidget** [comment]
You dont have /usr/sbin in your users path, I'm not sure why it is not there as on all my systems it is there by default. If you add that `/usr/sbin` to your path then conjure-up should work

**Comment by juliohm1978** [comment]
You are correct! Adding the following line to `~/.brashrc` of the common user account works.

```
export PATH=$PATH:/usr/sbin
```

Thank you!
