### ISSUE TITLE
Unable to use conjure-up to deploy helm and kubernetes on fresh ubuntu 16.04.03-LTS-x64

### ISSUE THREAD

**Issue by speculatrix** [conjure-up/conjure-up#1125]
I have tried this several times in different ways.

I tried running the conjure-up on a fresh EC2 instance on an Ubuntu 16.04 server, created from the standard images provided on EC2.

This report was generated using a totally fresh standard install of ubuntu server 16.04.03-x64 on a QEMU/KVM VM. I have a 100M symmetric internet connection but only IPv4.

## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [N ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ Y] Is conjure-up running inside a virtual machine?
- [N ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

    $ sudo snap refresh conjure-up --edge
    [sudo] password for pmansfield: 
    conjure-up (edge) 2.3-alpha1-20170830.2008 from 'canonical' refreshed

## Please provide the output of the following commands

```
which juju
    /snap/bin/juju

which conjure-up
    /snap/bin/conjure-up

which conjure-up.lxd
   ... nothing ...

juju version
    2.3-alpha1-xenial-amd64

conjure-up --version
    conjure-up 2.3-alpha1

lxc config show
    Generating a client certificate. This may take a minute...
    If this is your first time using LXD, you should also run: sudo lxd init
    To start your first container, try: lxc launch ubuntu:16.04

    config: {}


cat /etc/lsb-release
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=16.04
    DISTRIB_CODENAME=xenial
    DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
    sosreport (version 3.4)
    no valid plugins were enabled

```

The resulting output file can be attached to this issue.

## What Spell was Selected?

    I followed this guide to the letter
    https://tutorials.ubuntu.com/tutorial/install-kubernetes-with-conjure-up

    If I try it again, I get the same result.

## What provider (aws, maas, localhost, etc)?
    aws

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

**Comment by speculatrix** [comment]
just about to attach files

**Comment by speculatrix** [comment]
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1266624/conjure-up.tar.gz)

**Comment by speculatrix** [comment]
not sure how I accidentally closed the issue :-(

**Comment by battlemidget** [comment]
Looks like you are running an older juju, can you do

```
sudo snap refresh juju --candidate 
```

Then `rm -rf ~/.local/share/juju`, and `rm -rf ~/.cache/conjure-up` and retry conjure-up? If it fails again please attach a new tarball of `~/.cache/conjure-up`

**Comment by speculatrix** [comment]
$ sudo snap refresh conjure-up --edge
[sudo] password for pmansfield: 
conjure-up (edge) 2.3-alpha1-20170831.1508 from 'canonical' refreshed
$

did the rm -rf

ran conjure-up, 
selected Canonical Distribution of Kubernetes Core... as per the instructions. Some fields were already populated.

this time I got a different error. I've screen-shotted as I go, I'll redact this and attach them.

**Comment by speculatrix** [comment]
OK, here's screen shots and the tar-gz of the .cache/conjure-up

[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1267915/conjure-up.tar.gz)

[conjure-up-screenshots.tar.gz](https://github.com/conjure-up/conjure-up/files/1267912/conjure-up-screenshots.tar.gz)

**Comment by battlemidget** [comment]
Thanks!

Relevant error:

```
2017-08-31 17:36:26,881 [DEBUG] conjure-up/canonical-kubernetes - events.py:53 - Setting Error at conjureup/events.py:147
2017-08-31 17:36:26,881 [ERROR] conjure-up/canonical-kubernetes - events.py:159 - Unhandled exception in <Task finished coro=<do_deploy() done, defined at /snap/conjure-up/677/lib/python3.6/site-packages/conjureup/controllers/deploy/common.py:9> exception=JujuAPIError('failed to create relation egress networks: forbidden transaction: references unknown collection "relationNetworks"',)>
Traceback (most recent call last):
  File "/snap/conjure-up/677/lib/python3.6/site-packages/conjureup/controllers/deploy/common.py", line 43, in do_deploy
    await asyncio.gather(*tasks)
  File "/snap/conjure-up/677/lib/python3.6/site-packages/conjureup/juju.py", line 701, in set_relations
    await app.juju.client.add_relation(*rel_pair)
  File "/snap/conjure-up/677/lib/python3.6/site-packages/juju/model.py", line 890, in add_relation
    result = await app_facade.AddRelation([relation1, relation2])
  File "/snap/conjure-up/677/lib/python3.6/site-packages/juju/client/facade.py", line 392, in wrapper
    reply = await f(*args, **kwargs)
  File "/snap/conjure-up/677/lib/python3.6/site-packages/juju/client/_client5.py", line 439, in AddRelation
    reply = await self.rpc(msg)
  File "/snap/conjure-up/677/lib/python3.6/site-packages/juju/client/facade.py", line 514, in rpc
    result = await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/snap/conjure-up/677/lib/python3.6/site-packages/juju/client/connection.py", line 267, in rpc
    raise JujuAPIError(result)
juju.errors.JujuAPIError: failed to create relation egress networks: forbidden transaction: references unknown collection "relationNetworks"
2017-08-31 17:36:26,890 [DEBUG] conjure-up/canonical-kubernetes - __init__.py:21 - Showing dialog for exception: failed to create relation egress networks: forbidden transaction: references unknown collection "relationNetworks"
```

**Comment by speculatrix** [comment]
sorry about being vague, this is the first time I have touched any of these tools.

**Comment by battlemidget** [comment]
@speculatrix not a problem, this is a unique error that none of us have seen before. we're still investigating

**Comment by battlemidget** [comment]
@speculatrix Ok this looks like a mongodb error (probably b/c something that should be behind a feature flag isnt).

I'm preparing a release for stable, is it ok if i update this bug when i have something in our candidate channel for you to try?

**Comment by battlemidget** [comment]
@speculatrix yea it's not just you hitting this, https://travis-ci.org/conjure-up/conjure-up/builds/270515922#L866 we're hitting it in our CI as well. This is something related to an underlying piece of tech we use (juju). I'm going to release a stable with a stable juju so I'll let you know when it's ready to try

**Comment by lghinet** [comment]
hello,

same provblem here 


`2017-09-01 08:32:10,027 [INFO] conjure-up/canonical-kubernetes - juju.py:698 - Setting relation easyrsa:client <-> kubernetes-master:certificates
2017-09-01 08:32:10,031 [DEBUG] conjure-up/canonical-kubernetes - events.py:53 - Setting PendingRelations:easyrsa:client <-> kubernetes-master:certificates at conjureup/juju.py:700
2017-09-01 08:32:10,233 [DEBUG] conjure-up/canonical-kubernetes - events.py:53 - Setting Error at conjureup/events.py:147
2017-09-01 08:32:10,234 [ERROR] conjure-up/canonical-kubernetes - events.py:159 - Unhandled exception in <Task finished coro=<do_deploy() done, defined at /snap/conjure-up/694/lib/python3.6/site-packages/conjureup/controllers/deploy/common.py:9> exception=JujuAPIError('failed to create relation egress networks: forbidden transaction: references unknown collection "relationNetworks"',)>
Traceback (most recent call last):
  File "/snap/conjure-up/694/lib/python3.6/site-packages/conjureup/controllers/deploy/common.py", line 43, in do_deploy
    await asyncio.gather(*tasks)
  File "/snap/conjure-up/694/lib/python3.6/site-packages/conjureup/juju.py", line 701, in set_relations
    await app.juju.client.add_relation(*rel_pair)
  File "/snap/conjure-up/694/lib/python3.6/site-packages/juju/model.py", line 890, in add_relation
    result = await app_facade.AddRelation([relation1, relation2])
  File "/snap/conjure-up/694/lib/python3.6/site-packages/juju/client/facade.py", line 392, in wrapper
    reply = await f(*args, **kwargs)
  File "/snap/conjure-up/694/lib/python3.6/site-packages/juju/client/_client5.py", line 439, in AddRelation
    reply = await self.rpc(msg)
  File "/snap/conjure-up/694/lib/python3.6/site-packages/juju/client/facade.py", line 514, in rpc
    result = await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/snap/conjure-up/694/lib/python3.6/site-packages/juju/client/connection.py", line 267, in rpc
    raise JujuAPIError(result)
juju.errors.JujuAPIError: failed to create relation egress networks: forbidden transaction: references unknown collection "relationNetworks"
2017-09-01 08:32:10,261 [DEBUG] conjure-up/canonical-kubernetes - __init__.py:21 - Showing dialog for exception: failed to create relation egress networks: forbidden transaction: references unknown collection "relationNetworks"
2017-09-01 08:36:05,609 [DEBUG] conjure-up/canonical-kubernetes - events.py:53 - Setting Shutdown at conjureup/events.py:143
2017-09-01 08:36:05,645 [DEBUG] conjure-up/canonical-kubernetes - events.py:53 - Received Shutdown at conjureup/events.py:174
2017-09-01 08:36:05,645 [INFO] conjure-up/canonical-kubernetes - events.py:178 - Shutting down
2017-09-01 08:36:05,646 [INFO] conjure-up/canonical-kubernetes - app_config.py:187 - Storing conjure-up state
2017-09-01 08:36:05,758 [INFO] conjure-up/canonical-kubernetes - app_config.py:191 - State saved in model config
2017-09-01 08:36:05,758 [INFO] conjure-up/canonical-kubernetes - events.py:188 - Disconnecting model
2017-09-01 08:36:05,766 [INFO] conjure-up/canonical-kubernetes - events.py:190 - Disconnected
2017-09-01 08:36:05,767 [DEBUG] conjure-up/canonical-kubernetes - events.py:200 - Cancelling pending task: <Task pending coro=<DeployController._wait_for_applications() running at /snap/conjure-up/694/lib/python3.6/site-packages/conjureup/controllers/deploy/gui.py:90> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f3b129c29a8>()]>>
2017-09-01 08:36:05,767 [DEBUG] conjure-up/canonical-kubernetes - events.py:200 - Cancelling pending task: <Task finished coro=<WebSocketCommonProtocol.run() done, defined at /snap/conjure-up/694/lib/python3.6/site-packages/websockets/protocol.py:428> result=None>
`

using localhost 
and canonical kubernetes charm

**Comment by battlemidget** [comment]
Yep known problem and is being worked on from juju team

**Comment by battlemidget** [comment]
Doing a `sudo snap refresh conjure-up --edge` should have a working juju now

**Comment by lghinet** [comment]
snap "conjure-up" has no updates available
still not working

**Comment by battlemidget** [comment]
@lghinet we've done a release candidate now in `sudo snap refresh conjure-up --candidate`

**Comment by falfaro** [comment]
Isn't "snap" supposed to deal better with these dependencies? Because on my (limited) experience with conjure-up and snap, it's broken most of the time :-)

**Comment by battlemidget** [comment]
Yea it's a little awkward and I've been in ongoing discussions on how to handle snap dependencies.

**Comment by speculatrix** [comment]
I can confirm that this now works, I followed the Canonical/Ubuntu official guide and ended up with a working k8s cluster.
Note: if your AWS Availability Zone is London, then you may have problems. Mine got stuck deploying. I think it might be because London doesn't have the full range of EC2 tiers? I switched to Ireland and it worked perfectly.
![screenshot_2017-09-06_13-33-02](https://user-images.githubusercontent.com/210077/30113143-9a3d6efa-930b-11e7-8df2-6487331a4f12.png)

**Comment by speculatrix** [comment]
thanks very much to all who worked on fixing this
