### ISSUE TITLE
hangs on master - Waiting for kube-system pods to start

### ISSUE THREAD

**Issue by lghinet** [conjure-up/conjure-up#1134]
- [ ] Is conjure-up running inside a virtual machine?
yes
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?
no, --candidate 

## Please provide the output of the following commands

```
which juju
2.2.2-xenial-amd64

which conjure-up
conjure-up 2.3.0-rc1

which lxc
config:
  core.https_address: '[::]'

lxc 2.17

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

```

Please attach tarball of **~/.cache/conjure-up**:

[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1276563/conjure-up.tar.gz)

## What Spell was Selected?
canonical kubernetes

## What provider (aws, maas, localhost, etc)?
localhost

**Comment by lghinet** [comment]
error log from kubernetes-master/0  - Error syncing pod

i think its related to kubernetes cni.
i use a custom network lxdbr0, so that the new ips are from my local network

> And then add a bridge by creating /etc/network/interfaces.d/containerbr.cfg with the contents:
auto containerbr
iface containerbr inet dhcp
  bridge_ports eth0

https://insights.ubuntu.com/2015/11/10/converting-eth0-to-br0-and-getting-all-your-lxc-or-lxd-onto-your-lan/

**Comment by battlemidget** [comment]
Ok we'll probably need to include a few of the kubernetes guys, @cynerva, @tvansteenburgh.

Can you `juju ssh kubernetes-master/0` and then `sudo pastebinit /var/log/juju/unit-kubernetes-master-0.log`

**Comment by lghinet** [comment]
here is the log

**Comment by battlemidget** [comment]
This is one of the errors seen:

```
2017-09-05 11:36:15 INFO juju-log etcd:3: Invoking reactive handler: reactive/kubernetes_master.py:309:set_app_version
2017-09-05 11:36:17 INFO juju-log etcd:3: Invoking reactive handler: reactive/tls_client.py:58:store_client
2017-09-05 11:36:17 INFO juju-log etcd:3: Invoking reactive handler: reactive/kubernetes_master.py:477:configure_cdk_addons
The connection to the server localhost:8080 was refused - did you specify the right host or port?
2017-09-05 11:36:27 DEBUG etcd-relation-joined Traceback (most recent call last):
2017-09-05 11:36:27 DEBUG etcd-relation-joined   File "/snap/cdk-addons/119/apply", line 93, in <module>
2017-09-05 11:36:27 DEBUG etcd-relation-joined     main()
2017-09-05 11:36:27 DEBUG etcd-relation-joined   File "/snap/cdk-addons/119/apply", line 12, in main
2017-09-05 11:36:27 DEBUG etcd-relation-joined     render_templates()
2017-09-05 11:36:27 DEBUG etcd-relation-joined   File "/snap/cdk-addons/119/apply", line 23, in render_templates
2017-09-05 11:36:27 DEBUG etcd-relation-joined     "num_nodes": get_node_count()
2017-09-05 11:36:27 DEBUG etcd-relation-joined   File "/snap/cdk-addons/119/apply", line 77, in get_node_count
2017-09-05 11:36:27 DEBUG etcd-relation-joined     output = kubectl("get", "nodes", "-o", "name")
2017-09-05 11:36:27 DEBUG etcd-relation-joined   File "/snap/cdk-addons/119/apply", line 73, in kubectl
2017-09-05 11:36:27 DEBUG etcd-relation-joined     return subprocess.check_output(cmd)
2017-09-05 11:36:27 DEBUG etcd-relation-joined   File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
2017-09-05 11:36:27 DEBUG etcd-relation-joined     **kwargs).stdout
2017-09-05 11:36:27 DEBUG etcd-relation-joined   File "/usr/lib/python3.5/subprocess.py", line 708, in run
2017-09-05 11:36:27 DEBUG etcd-relation-joined     output=stdout, stderr=stderr)
2017-09-05 11:36:27 DEBUG etcd-relation-joined subprocess.CalledProcessError: Command '['/snap/cdk-addons/119/kubectl', 'get', 'nodes', '-o', 'name']' returned non-zero exit status 1
2017-09-05 11:36:28 INFO juju-log etcd:3: Addons are not ready yet.
2017-09-05 11:36:55 INFO juju.worker.uniter.operation runhook.go:113 ran "etcd-relation-joined" hook
```

**Comment by battlemidget** [comment]
@lghinet can we also see your lxc setup?

**Comment by lghinet** [comment]
lxc info :

```root@kubernetes:~$ lxc info
config:
  core.https_address: '[::]'
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
------------

api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 10.1.3.80:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFTDCCAzSgAwIBAgIQVTeul/sZA9N4/rNktI3icjANBgkqhkiG9w0BAQsFADA4
 ......
    pIgi7lkKEbUI17PDPI4oA9YaB2UeLY9ODQN1ErggD3Q4fWmya+0HuCTd3kHvMtQm
    JdW5fyj9yUM8nHRLo+7osg==
    -----END CERTIFICATE-----
  certificate_fingerprint: ea7208459946368d9f265fec4bbc3cfe18ef2241abaa3aa733a770c83693c714
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-93-generic
  server: lxd
  server_pid: 1472
  server_version: "2.17"
  storage: dir
  storage_version: "1"
totalsoft@kubernetes:~$
```

$ lxc profile show default
```config: {}
description: Default LXD profile
devices:
  eth0:
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/containers/juju-caec97-0
- /1.0/containers/juju-caec97-1
- /1.0/containers/juju-caec97-2
- /1.0/containers/juju-caec97-3
- /1.0/containers/juju-caec97-4
- /1.0/containers/juju-caec97-5
- /1.0/containers/juju-f23978-0
```

totalsoft@kubernetes:~$ cat /etc/network/interfaces

```
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth0
iface eth0 inet manual

auto br0
iface br0 inet dhcp
  bridge_ports eth0
```


![image](https://user-images.githubusercontent.com/12889810/30063122-34123c9c-9256-11e7-9fcb-0235bae3f3b8.png)




so there is no default lxdbr0 network, instead I used br0 which is also bridged using  bridge-utils.
the ip assignment is ok

in rest its a fresh ubuntu,

**Comment by Cynerva** [comment]
It's not clear from the charm log what the problem is, so we'll need more info.

@lghinet Can you run the script from this repo and paste the archive that it creates? https://github.com/juju-solutions/cdk-field-agent

**Comment by lghinet** [comment]
its stuck on 

`totalsoft@kubernetes:~/cdk-field-agent$ python3 ./collect.py
Getting juju status...
Executing debug action on kubernetes-master/0...
`

**Comment by lghinet** [comment]
thanks for help 
[results-2017-09-06-08-27-04.tar.gz](https://github.com/conjure-up/conjure-up/files/1279890/results-2017-09-06-08-27-04.tar.gz)

![image](https://user-images.githubusercontent.com/12889810/30095882-ee314474-92dd-11e7-910e-8a945644f575.png)

**Comment by lghinet** [comment]
```
ubuntu@juju-a53432-1:~$ ifconfig
eth0      Link encap:Ethernet  HWaddr 00:16:3e:27:83:61
          inet addr:10.1.3.97  Bcast:10.1.3.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:14719 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2268 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1776710 (1.7 MB)  TX bytes:398310 (398.3 KB)

flannel.1 Link encap:Ethernet  HWaddr 4e:4d:19:98:54:4e
          inet addr:10.1.5.0  Bcast:0.0.0.0  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:6 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:90 errors:0 dropped:0 overruns:0 frame:0
          TX packets:90 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:4566 (4.5 KB)  TX bytes:4566 (4.5 KB)

lxdbr0    Link encap:Ethernet  HWaddr aa:51:68:4a:05:d6
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

```

this is my config from the master node,  
until the interface flannel.1 is up, the dns is working fine, i can ping between nodes, 
after that no dns,

**Comment by Cynerva** [comment]
Thanks. I see lots of errors coming from kubelet all based on this:
```
Get https://gcr.io/v1/_ping: dial tcp: i/o timeout
```

Looking at the routing table on kubernetes-worker/0, I think I see a problem:

```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.1.3.254      0.0.0.0         UG    0      0        0 eth0
10.1.0.0        0.0.0.0         255.255.0.0     U     0      0        0 flannel.1
10.1.3.0        0.0.0.0         255.255.255.0   U     0      0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
```

It looks like the networks for flannel (10.1.0.0/16) and your local network (10.1.3.0/24) overlap. I'm guessing this is leading to the gcr.io tcp timeout.

You can configure flannel to use a different CIDR, e.g. `10.2.0.0/16`:
```
juju config flannel cidr=10.2.0.0/16
```

I'm not sure if this works on a live cluster, though; after configuring flannel, you might need to recreate all the pods (`kubectl delete po ...` and let them recreate on their own), or even remove the kubernetes-master and kubernetes-worker units (`juju remove-unit kubernetes-master/0`, `juju add-unit kubernetes-master`, etc)

**Comment by lghinet** [comment]
i will recreate the enviroment,start fresh .
how can i tell flannel to use a specific cidr from conjure-up gui ? (from configure advanced ?)

thanks

**Comment by battlemidget** [comment]
@lghinet we'll need to ad that capability in the UI, for now just use ` juju config flannel cidr=10.2.0.0/16` and follow this bug: https://github.com/conjure-up/conjure-up/issues/1142

**Comment by lghinet** [comment]
its working
thanks

**Comment by GiantShawn** [comment]
[Uploading results-2018-01-15-15-27-05.tar.gz…]()
I got seemingly the same error as Ighinet but not relating to CIDR config I think. Can you(@Cynerva) help to check this result as well. I am still struggling to set my first kubernetes environment up
[results-2018-01-15-15-27-05.tar.gz](https://github.com/conjure-up/conjure-up/files/1630730/results-2018-01-15-15-27-05.tar.gz)
 and can't figure it out. Thanks.
[results-2018-01-15-15-27-05.tar.gz](https://github.com/conjure-up/conjure-up/files/1630727/results-2018-01-15-15-27-05.tar.gz)


$ juju status
Model       Controller  Cloud/Region         Version  SLA
kubernetes  kctl        localhost/localhost  2.3.1    unsupported

App                    Version  Status   Scale  Charm                  Store       Rev  OS      Notes
easyrsa                3.0.1    active       1  easyrsa                jujucharms   27  ubuntu
etcd                   2.3.8    active       3  etcd                   jujucharms   63  ubuntu
flannel                0.9.1    active       4  flannel                jujucharms   40  ubuntu
kubeapi-load-balancer  1.10.3   active       1  kubeapi-load-balancer  jujucharms   43  ubuntu  exposed
kubernetes-master      1.9.1    waiting      1  kubernetes-master      jujucharms   78  ubuntu
kubernetes-worker      1.9.1    active       3  kubernetes-worker      jujucharms   81  ubuntu  exposed

Unit                      Workload  Agent      Machine  Public address  Ports           Message
easyrsa/0*                active    idle       0        10.86.151.67                    Certificate Authority connected.
etcd/0*                   active    idle       1        10.86.151.155   2379/tcp        Healthy with 3 known peers
etcd/1                    active    idle       2        10.86.151.22    2379/tcp        Healthy with 3 known peers
etcd/2                    active    idle       3        10.86.151.177   2379/tcp        Healthy with 3 known peers
kubeapi-load-balancer/0*  active    idle       4        10.86.151.17    443/tcp         Loadbalancer ready.
kubernetes-master/0*      waiting   executing  5        10.86.151.245   6443/tcp        Waiting for kube-system pods to start
  flannel/3               active    idle                10.86.151.245                   Flannel subnet 10.1.76.1/24
kubernetes-worker/0*      active    idle       6        10.86.151.11    80/tcp,443/tcp  Kubernetes worker running.
  flannel/2               active    idle                10.86.151.11                    Flannel subnet 10.1.89.1/24
kubernetes-worker/1       active    idle       7        10.86.151.12    80/tcp,443/tcp  Kubernetes worker running.
  flannel/1               active    idle                10.86.151.12                    Flannel subnet 10.1.14.1/24
kubernetes-worker/2       active    idle       8        10.86.151.193   80/tcp,443/tcp  Kubernetes worker running.
  flannel/0*              active    idle                10.86.151.193                   Flannel subnet 10.1.55.1/24

Machine  State    DNS            Inst id        Series  AZ  Message
0        started  10.86.151.67   juju-5e3e9c-0  xenial      Running
1        started  10.86.151.155  juju-5e3e9c-1  xenial      Running
2        started  10.86.151.22   juju-5e3e9c-2  xenial      Running
3        started  10.86.151.177  juju-5e3e9c-3  xenial      Running
4        started  10.86.151.17   juju-5e3e9c-4  xenial      Running
5        started  10.86.151.245  juju-5e3e9c-5  xenial      Running
6        started  10.86.151.11   juju-5e3e9c-6  xenial      Running
7        started  10.86.151.12   juju-5e3e9c-7  xenial      Running
8        started  10.86.151.193  juju-5e3e9c-8  xenial      Running

Relation provider                    Requirer                             Interface         Type         Message
easyrsa:client                       etcd:certificates                    tls-certificates  regular
easyrsa:client                       kubeapi-load-balancer:certificates   tls-certificates  regular
easyrsa:client                       kubernetes-master:certificates       tls-certificates  regular
easyrsa:client                       kubernetes-worker:certificates       tls-certificates  regular
etcd:cluster                         etcd:cluster                         etcd              peer
etcd:db                              flannel:etcd                         etcd              regular
etcd:db                              kubernetes-master:etcd               etcd              regular
kubeapi-load-balancer:loadbalancer   kubernetes-master:loadbalancer       public-address    regular
kubeapi-load-balancer:website        kubernetes-worker:kube-api-endpoint  http              regular
kubernetes-master:cni                flannel:cni                          kubernetes-cni    subordinate
kubernetes-master:kube-api-endpoint  kubeapi-load-balancer:apiserver      http              regular
kubernetes-master:kube-control       kubernetes-worker:kube-control       kube-control      regular
kubernetes-worker:cni                flannel:cni                          kubernetes-cni    subordinate


$ juju ssh kubernetes-master/0

ubuntu@juju-5e3e9c-5:~$ route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         10.86.151.1     0.0.0.0         UG    0      0        0 eth0
10.1.14.0       10.1.14.0       255.255.255.0   UG    0      0        0 flannel.1
10.1.55.0       10.1.55.0       255.255.255.0   UG    0      0        0 flannel.1
10.1.89.0       10.1.89.0       255.255.255.0   UG    0      0        0 flannel.1
10.86.151.0     *               255.255.255.0   U     0      0        0 eth0

**Comment by Cynerva** [comment]
@GiantShawn I do see the same gcr.io timeout in your kubelet logs:

```
Get https://gcr.io/v1/_ping: dial tcp 108.177.97.82:443: i/o timeout
```

It's not immediately obvious what the cause is, though. I don't see anything obvious in the attached debug output.

I've noticed that none of the units are able to ping google.com either. Is your host machine behind a firewall that could be filtering traffic?

Can you run the following on your host machine and share the output?
* `curl https://gcr.io/v1/_ping` (should output `v1 Registry API is disabled ...`)
* `sudo sysctl net.ipv4.ip_forward` (should be 1)
* `sudo iptables-save` (should see a line like `-A POSTROUTING -s 10.86.151.0/24 ! -d 10.86.151.0/24 -m comment --comment "generated for LXD network lxdbr0" -j MASQUERADE`)

**Comment by adamelliotfields** [comment]
@battlemidget just wanted to chime in, running `juju config flannel cidr=10.2.0.0/16` worked for me on a default `lxd init` using `lxdbr0`.

Only additional steps I took were restarting the LXC containers:

```bash
lxc restart juju-24a266-0 && lxc restart juju-24a266-1
```

I'm assuming `lxc restart --all` would also work. The good news is I didn't have to reinstall any charms and relations.

It took a few minutes for everything to settle, but looking good so far:

```bash
juju status
Model                        Controller                Cloud/Region         Version  SLA
conjure-kubernetes-core-f36  conjure-up-localhost-19e  localhost/localhost  2.3.3    unsupported

App                Version  Status  Scale  Charm              Store       Rev  OS      Notes
easyrsa            3.0.1    active      1  easyrsa            jujucharms   27  ubuntu  
etcd               2.3.8    active      1  etcd               jujucharms   63  ubuntu  
flannel            0.9.1    active      2  flannel            jujucharms   40  ubuntu
kubernetes-master  1.9.3    active      1  kubernetes-master  jujucharms   78  ubuntu  exposed
kubernetes-worker  1.9.3    active      1  kubernetes-worker  jujucharms   81  ubuntu  exposed

Unit                  Workload  Agent  Machine  Public address  Ports           Message
easyrsa/0*            active    idle   1/lxd/0  10.0.167.224                    Certificate Authority connected.
etcd/0*               active    idle   1        10.123.169.41   2379/tcp        Healthy with 1 known peer
kubernetes-master/0*  active    idle   1        10.123.169.41   6443/tcp        Kubernetes master running.
  flannel/0*          active    idle            10.123.169.41                   Flannel subnet 10.2.85.1/24
kubernetes-worker/0*  active    idle   0        10.123.169.23   80/tcp,443/tcp  Kubernetes worker running.
  flannel/1           active    idle            10.123.169.23                   Flannel subnet 10.2.95.1/24

Machine  State    DNS            Inst id              Series  AZ  Message
0        started  10.123.169.23  juju-24a266-0        xenial      Running
1        started  10.123.169.41  juju-24a266-1        xenial      Running
1/lxd/0  started  10.0.167.224   juju-24a266-1-lxd-0  xenial      Container started

Relation provider                    Requirer                             Interface         Type         Message
easyrsa:client                       etcd:certificates                    tls-certificates  regular
easyrsa:client                       kubernetes-master:certificates       tls-certificates  regular
easyrsa:client                       kubernetes-worker:certificates       tls-certificates  regular
etcd:cluster                         etcd:cluster                         etcd              peer
etcd:db                              flannel:etcd                         etcd              regular
etcd:db                              kubernetes-master:etcd               etcd              regular
kubernetes-master:cni                flannel:cni                          kubernetes-cni    subordinate
kubernetes-master:kube-api-endpoint  kubernetes-worker:kube-api-endpoint  http              regular
kubernetes-master:kube-control       kubernetes-worker:kube-control       kube-control      regular
kubernetes-worker:cni                flannel:cni                          kubernetes-cni    subordinate
```

Kubernetes Dashboard looking good as well:

```bash
# use SSH port forwarding
ssh -L 8001:127.0.0.1:8001 ubuntu@10.123.169.23

# copy token to log into dashboard
kubectl config view

# visit http://localhost:8001/ui in host machine browser
kubectl proxy
```

Wanted to comment since this is the first Google search result. Having struggled with Minikube and KubeADM, the Juju + Conjure Up approach is the most user friendly way to run Kubernetes locally for those of us running Ubuntu on our personal computers. Thanks for making this awesome tool for DevOps noobs like myself :)

**Comment by glortho** [comment]
I also seem to have a kube master that waits forever. I see this in conjure-up.log:
```
2018-04-19 10:55:21,055 [ERROR] conjure-up/canonical-kubernetes - events.py:160 - Unhandled exception in <Task finished coro=<Connection.reconnect() done, defined at /snap/conjure-up/987/lib/python3.6/site-packages/juju/client/connection.py:422> exception=JujuConnectionError('Unable to connect to any endpoint: 10.19.195.168:17070',)>
Traceback (most recent call last):
  File "/snap/conjure-up/987/lib/python3.6/site-packages/juju/client/connection.py", line 430, in reconnect
    await self._connect_with_login([(self.endpoint, self.cacert)])
  File "/snap/conjure-up/987/lib/python3.6/site-packages/juju/client/connection.py", line 476, in _connect_with_login
    await self._connect(endpoints)
  File "/snap/conjure-up/987/lib/python3.6/site-packages/juju/client/connection.py", line 456, in _connect
    endpoint for endpoint, cacert in endpoints])))
juju.errors.JujuConnectionError: Unable to connect to any endpoint: 10.19.195.168:17070
```
and this in juju/unit-kubernetes-master-0.log:
```
2018-04-19 15:18:00 INFO juju.worker.uniter uniter.go:167 unit "kubernetes-master/0" started
2018-04-19 15:18:00 INFO juju.worker.uniter uniter.go:206 hooks are retried true
2018-04-19 15:18:00 INFO juju.worker.upgrader upgrader.go:178 desired agent binary version: 2.3.3
2018-04-19 15:18:01 INFO juju.worker.upgrader upgrader.go:178 desired agent binary version: 2.3.3
2018-04-19 15:18:04 DEBUG collect-metrics The connection to the server localhost:8080 was refused - did you specify the right host or port?
2018-04-19 15:18:05 DEBUG collect-metrics The connection to the server localhost:8080 was refused - did you specify the right host or port?
2018-04-19 15:18:05 DEBUG collect-metrics The connection to the server localhost:8080 was refused - did you specify the right host or port?
2018-04-19 15:18:05 DEBUG collect-metrics The connection to the server localhost:8080 was refused - did you specify the right host or port?
2018-04-19 15:18:05 DEBUG collect-metrics The connection to the server localhost:8080 was refused - did you specify the right host or port?
2018-04-19 15:18:05 DEBUG collect-metrics The connection to the server localhost:8080 was refused - did you specify the right host or port?
2018-04-19 15:18:06 DEBUG collect-metrics The connection to the server localhost:8080 was refused - did you specify the right host or port?
2018-04-19 15:18:06 DEBUG collect-metrics The connection to the server localhost:8080 was refused - did you specify the right host or port?
2018-04-19 15:18:06 INFO juju-log Reactive main running for hook config-changed
2018-04-19 15:18:07 INFO juju-log Initializing Snap Layer
2018-04-19 15:18:07 DEBUG config-changed lxc
2018-04-19 15:18:07 INFO juju-log Initializing Leadership Layer (is leader)
2018-04-19 15:18:07 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:400:idle_status
2018-04-19 15:18:07 DEBUG config-changed The connection to the server localhost:8080 was refused - did you specify the right host or port?
2018-04-19 15:18:07 INFO juju-log failed to get kube-system pod status
2018-04-19 15:18:38 INFO juju-log Invoking reactive handler: reactive/tls_client.py:60:store_client
2018-04-19 15:18:39 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:504:create_service_configs
2018-04-19 15:18:39 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:393:set_app_version
2018-04-19 15:18:40 INFO juju-log Invoking reactive handler: reactive/tls_client.py:36:store_server
2018-04-19 15:18:40 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:577:send_data
2018-04-19 15:18:41 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:682:loadbalancer_kubeconfig
2018-04-19 15:18:41 DEBUG config-changed Cluster "juju-cluster" set.
2018-04-19 15:18:41 DEBUG config-changed Property "users" unset.
2018-04-19 15:18:41 DEBUG config-changed User "admin" set.
2018-04-19 15:18:41 DEBUG config-changed Context "juju-context" modified.
2018-04-19 15:18:41 DEBUG config-changed Switched to context "juju-context".
2018-04-19 15:18:41 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:462:etcd_data_change
2018-04-19 15:18:42 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:488:send_cluster_dns_detail
2018-04-19 15:18:42 INFO juju-log Invoking reactive handler: reactive/tls_client.py:15:store_ca
2018-04-19 15:18:43 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:555:push_service_data
2018-04-19 15:18:43 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:637:configure_cdk_addons
2018-04-19 15:18:47 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:400:idle_status
2018-04-19 15:19:18 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:488:send_cluster_dns_detail
2018-04-19 15:19:19 INFO juju.worker.uniter.operation runhook.go:119 ran "config-changed" hook
2018-04-19 15:19:19 INFO juju-log Reactive main running for hook config-changed
2018-04-19 15:19:19 INFO juju-log Initializing Snap Layer
2018-04-19 15:19:19 DEBUG config-changed lxc
2018-04-19 15:19:19 INFO juju-log Initializing Leadership Layer (is leader)
2018-04-19 15:19:20 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:504:create_service_configs
2018-04-19 15:19:20 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:682:loadbalancer_kubeconfig
2018-04-19 15:19:20 DEBUG config-changed Cluster "juju-cluster" set.
2018-04-19 15:19:20 DEBUG config-changed Property "users" unset.
2018-04-19 15:19:21 DEBUG config-changed User "admin" set.
2018-04-19 15:19:21 DEBUG config-changed Context "juju-context" modified.
2018-04-19 15:19:21 DEBUG config-changed Switched to context "juju-context".
2018-04-19 15:19:21 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:462:etcd_data_change
2018-04-19 15:19:21 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:555:push_service_data
2018-04-19 15:19:22 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:400:idle_status
2018-04-19 15:19:53 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:577:send_data
2018-04-19 15:19:53 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:488:send_cluster_dns_detail
2018-04-19 15:19:54 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:393:set_app_version
2018-04-19 15:19:54 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:637:configure_cdk_addons
2018-04-19 15:19:57 INFO juju-log Invoking reactive handler: reactive/tls_client.py:60:store_client
2018-04-19 15:19:57 INFO juju-log Invoking reactive handler: reactive/tls_client.py:36:store_server
2018-04-19 15:19:57 INFO juju-log Invoking reactive handler: reactive/tls_client.py:15:store_ca
2018-04-19 15:19:57 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:400:idle_status
2018-04-19 15:20:28 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:488:send_cluster_dns_detail
2018-04-19 15:20:28 INFO juju.worker.uniter.operation runhook.go:119 ran "config-changed" hook
2018-04-19 15:23:04 INFO juju-log Reactive main running for hook update-status
2018-04-19 15:23:04 INFO juju-log Initializing Snap Layer
2018-04-19 15:23:04 DEBUG update-status lxc
2018-04-19 15:23:04 INFO juju-log Initializing Leadership Layer (is leader)
2018-04-19 15:23:04 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:577:send_data
2018-04-19 15:23:05 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:555:push_service_data
2018-04-19 15:23:05 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:393:set_app_version
2018-04-19 15:23:06 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:637:configure_cdk_addons
2018-04-19 15:23:08 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:488:send_cluster_dns_detail
2018-04-19 15:23:08 INFO juju-log Invoking reactive handler: reactive/tls_client.py:15:store_ca
2018-04-19 15:23:09 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:682:loadbalancer_kubeconfig
2018-04-19 15:23:09 DEBUG update-status Cluster "juju-cluster" set.
2018-04-19 15:23:09 DEBUG update-status Property "users" unset.
2018-04-19 15:23:09 DEBUG update-status User "admin" set.
2018-04-19 15:23:09 DEBUG update-status Context "juju-context" modified.
2018-04-19 15:23:09 DEBUG update-status Switched to context "juju-context".
2018-04-19 15:23:09 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:462:etcd_data_change
2018-04-19 15:23:10 INFO juju-log Invoking reactive handler: reactive/tls_client.py:60:store_client
2018-04-19 15:23:10 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:504:create_service_configs
2018-04-19 15:23:10 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:400:idle_status
2018-04-19 15:23:20 DEBUG collect-metrics No resources found.
2018-04-19 15:23:21 DEBUG collect-metrics No resources found.
2018-04-19 15:23:41 INFO juju-log Invoking reactive handler: reactive/tls_client.py:36:store_server
2018-04-19 15:23:41 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:488:send_cluster_dns_detail
2018-04-19 15:23:42 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:400:idle_status
2018-04-19 15:24:13 INFO juju.worker.uniter.operation runhook.go:119 ran "update-status" hook
```

i tried `juju config flannel cidr=10.2.0.0/16` and then `lxc restart --all`. everything came back up properly, but master is still waiting.

any thoughts appreciated!

ubuntu 16.04
conjure-up 2.5.6

**Comment by tony-haibo-zhu** [comment]
And i met the same problem, any solution to workaround?

**Comment by babarzahoor** [comment]
After spending many weeks on this issue, I found why this happens.
First of all we need to check constraints are being met or not i.e. machines are having same resources which are required to setup Kubernetes cluster.

Secondly we need to perform manual upgrade on master nodes & Workers nodes of Kubernetes using below commands.
juju run-action kubernetes-master/0 upgrade
juju run-action kubernetes-worker/0 upgrade
juju run-action kubernetes-worker/1 upgrade 
........

And after all this whole exercise we need to setup service account to access the Kubernetes Dashboard using below commands.

kubectl create serviceaccount dashboard -n default

kubectl create clusterrolebinding dashboard-admin -n default   --clusterrole=cluster-admin   --serviceaccount=default:dashboard

kubectl get secret $(kubectl get serviceaccount dashboard -o jsonpath="{.secrets[0].name}") -o jsonpath="{.data.token}" | base64 --decode

Please use output  of the last command as your Token for accessing the Kubernetes dashboard every time.

https://kubeapi-load-balancer-ip:443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

**Comment by battlemidget** [comment]
@cynerva ^

**Comment by seffyroff** [comment]
I've followed most resolution suggestions here and in other threads, unfortunately my deployment seems unable to reach ready state.  My environment may be the cause - I'm running the spell against an LXD cluster, so in come cases privileged containers may be landing on the same host and overwriting one another's config files.  I'll test that theory with a smaller footprint that is host-isolated.
