### ISSUE TITLE
Kubernetes Core failing immediately after Juju controller provision on MAAS

### ISSUE THREAD

**Issue by andyshinn** [conjure-up/conjure-up#1188]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [X] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [X] Is conjure-up running inside a virtual machine?
- [X] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
~ $ juju version
2.2.4-sierra-amd64
~ $ which juju
/usr/local/bin/juju

~ $ /usr/local/bin/conjure-up --version
conjure-up 2.3.1
~ $ which conjure-up          
/usr/local/bin/conjure-up

# No LXN on macOS
~ $ which lxc
lxc not found

# No LSB information on macOS
~ [1] $ cat /etc/lsb-release
cat: /etc/lsb-release: No such file or directory
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1384826/conjure-up.tar.gz)

## Sosreport

Please attach a sosreport:

```
# No sosreport on macOS
```

The resulting output file can be attached to this issue.

## What Spell was Selected?

Kubernetes Core

## What provider (aws, maas, localhost, etc)?

MAAS

### MAAS Users
Which version of MAAS?

2.2.2-6099-g8751f91-0ubuntu1~16.04.1

## Commands ran

Please outline what commands were run to install and execute conjure-up:

```
~ $ brew install conjure-up
~ $ conjure-up
```
## Additional Information

After starting to deploy, I receive this error shortly after:

> Failure in step /Users/andy/.cache/conjure-up/kubernetes-core/steps/step-01_get-kubectl

The relevant error in logs is at:

```
2017-10-08 00:25:20,180 [ERROR] conjure-up/kubernetes-core - events.py:159 - Unhandled exception in <Task finished coro=<RunStepsController.run_steps() done, defined at /usr/local/Cellar/conjure-up/2.3.1/libexec/lib/python3.6/site-packages/conjureup/controllers/runsteps/gui.py:15> exception=Exception('Failure in step /Users/andy/.cache/conjure-up/kubernetes-core/steps/step-01_get-kubectl',)>
Traceback (most recent call last):
  File "/usr/local/Cellar/conjure-up/2.3.1/libexec/lib/python3.6/site-packages/conjureup/controllers/runsteps/gui.py", line 19, in run_steps
    step.result = await step.run(app.ui.set_footer)
  File "/usr/local/Cellar/conjure-up/2.3.1/libexec/lib/python3.6/site-packages/conjureup/models/step.py", line 162, in run
    raise Exception("Failure in step {}".format(self.filename))
Exception: Failure in step /Users/andy/.cache/conjure-up/kubernetes-core/steps/step-01_get-kubectl
```

When going through the `/Users/andy/.cache/conjure-up/kubernetes-core/steps/step-01_get-kubectl` script I notice the one of the first `juju` commands fails with a `no available address`:

```
~ $ export JUJU_MODEL=conjure-kubernetes-core-8e2
~ $ export JUJU_CONTROLLER=conjure-up-cloud-maas-cbc-7fa
~ $ juju scp -m $JUJU_CONTROLLER:$JUJU_MODEL kubernetes-master/0:config ~/.kube/config.$JUJU_MODEL
Error: no available address
```

Let me know if there is other testing I can do. I've already blown away this environment but will have another ready to test (the model and controller will be different).

**Comment by andyshinn** [comment]
OK, some more debugging. It looks like I may be running into https://bugs.launchpad.net/juju/+bug/1599272. After a while, the node does get provisioned and I get a new error:

```
export JUJU_CONTROLLER=conjure-up-cloud-maas-23f-2ed
export JUJU_MODEL=conjure-kubernetes-core-b15
~ $ juju scp -m $JUJU_CONTROLLER:$JUJU_MODEL kubernetes-master/0:config ~/.kube/config.$JUJU_MODEL
ERROR exit status 1 (scp: config: No such file or directory)
```

This appears to be because the unit is ready yet:

```
~ $ juju show-status                                                                              
Model                        Controller                     Cloud/Region    Version  SLA
conjure-kubernetes-core-b15  conjure-up-cloud-maas-23f-2ed  cloud-maas-23f  2.2.4    unsupported

App                Version  Status       Scale  Charm              Store       Rev  OS      Notes
easyrsa                     waiting        0/1  easyrsa            jujucharms   22  ubuntu  
etcd               2.3.8    blocked          1  etcd               jujucharms   56  ubuntu  
flannel                     maintenance      2  flannel            jujucharms   35  ubuntu  
kubernetes-master  1.8.0    blocked          1  kubernetes-master  jujucharms   58  ubuntu  exposed
kubernetes-worker  1.8.0    blocked          1  kubernetes-worker  jujucharms   62  ubuntu  exposed

Unit                  Workload     Agent       Machine  Public address  Ports  Message
easyrsa/0             waiting      allocating  1/lxd/0                         waiting for machine
etcd/0*               blocked      idle        1        192.168.88.14          Missing relation to certificate authority.
kubernetes-master/0*  blocked      idle        1        192.168.88.14          Waiting for workers.
  flannel/1           maintenance  executing            192.168.88.14          (install) installing charm software
kubernetes-worker/0*  blocked      idle        2        192.168.88.15          Relate kubernetes-worker:kube-control kubernetes-master:kube-control
  flannel/0*          maintenance  executing            192.168.88.15          (install) installing charm software

Machine  State    DNS            Inst id  Series  AZ       Message
0        started  192.168.88.13  rfpaax   xenial  default  Deployed
1        started  192.168.88.14  m3tpbp   xenial  default  Deployed
1/lxd/0  pending                 pending  xenial           starting
2        started  192.168.88.15  ntshmm   xenial  default  Deployed
3        started  192.168.88.16  axwaqr   xenial  default  Deployed

Relation provider                    Requirer                             Interface         Type
easyrsa:client                       etcd:certificates                    tls-certificates  regular
easyrsa:client                       kubernetes-master:certificates       tls-certificates  regular
easyrsa:client                       kubernetes-worker:certificates       tls-certificates  regular
etcd:cluster                         etcd:cluster                         etcd              peer
etcd:db                              flannel:etcd                         etcd              regular
etcd:db                              kubernetes-master:etcd               etcd              regular
kubernetes-master:cni                flannel:cni                          kubernetes-cni    subordinate
kubernetes-master:kube-api-endpoint  kubernetes-worker:kube-api-endpoint  http              regular
kubernetes-master:kube-control       kubernetes-worker:kube-control       kube-control      regular
kubernetes-worker:cni                flannel:cni                          kubernetes-cni    subordinate
```

Is it possible to change the timeouts? It seems like it fails pretty quickly and I need to probably wait 10+ more minutes for it to finish.
