### ISSUE TITLE
The 'conjure-up==2.4a1' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by EugeneKha** [conjure-up/conjure-up#1210]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [x] Is conjure-up running inside a virtual machine?
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
/snap/bin/juju

juju version
2.3-beta2-xenial-amd64

which conjure-up
/snap/bin/conjure-up

conjure-up --version
Traceback (most recent call last):
  File "/snap/conjure-up/799/bin/conjure-up", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'conjure-up==2.4a1' distribution was not found and is required by the application

which lxc
/usr/bin/lxc

/snap/bin/lxc config show
-bash: /snap/bin/lxc: No such file or directory

/usr/bin/lxc config show
config: {}

/snap/bin/lxc version
-bash: /snap/bin/lxc: No such file or directory

/usr/bin/lxc version
2.0.10

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

## Commands ran

sudo snap install conjure-up --classic
conjure-up

sudo snap refresh conjure-up --edge
conjure-up

## Additional Information

I have a fresh Ubuntu 16.04 on VirtualBox v5.1.30

**Comment by battlemidget** [comment]
Hi,

Im unable to reproduce:

```
ubuntu@ip-172-31-19-202:~$ snap info conjure-up
name:      conjure-up
summary:   Package runtime for conjure-up spells
publisher: canonical
contact:   https://github.com/conjure-up/conjure-up
description: |
  This package provides conjure-up, an interface to installing spells that
  provide the user with an end to end walkthrough experience for installing and
  using big software.
snap-id: ijQR4HjYlTAmIjELJm5XCpNAqbDZWJ3h
commands:
  - conjure-up.conjure-down
  - conjure-up
  - conjure-up.juju
tracking:    edge
installed:   2.4-alpha1-20171031.1910 (799) 92MB classic
refreshed:   2017-10-31 19:29:45 +0000 UTC
channels:                                   
  stable:    2.3.1                    (745) 83MB classic
  candidate: 2.3.1                    (745) 83MB classic
  beta:      2.3.1                    (745) 83MB classic
  edge:      2.4-alpha1-20171031.1910 (799) 92MB classic
ubuntu@ip-172-31-19-202:~$ conjure-up
ubuntu@ip-172-31-19-202:~$ conjure-up --version
conjure-up 2.4-alpha1
```

Can you give us a little more information about your system? Perhaps a `sosreport` as well?
