### ISSUE TITLE
Error on post-deploy of kubernete add-ons deis workflow!​

### ISSUE THREAD

**Issue by fatdrag0n** [conjure-up/conjure-up#1214]
Error on post-deploy of kubernete add-ons deis workflow!​

```
2017-11-03 00:01:36,077 [DEBUG] conjure-up/canonical-kubernetes - step.py:134 - Storing environment
2017-11-03 00:01:36,086 [DEBUG] conjure-up/canonical-kubernetes - step.py:140 - Executing script: /home/benf/.cache/conjure-up/canonical-kubernetes/steps/step-03_enable-cni
2017-11-03 00:01:36,584 [INFO] conjure-up/canonical-kubernetes - step.py:94 - Running step: step-01_install-workflow.
2017-11-03 00:01:36,722 [DEBUG] conjure-up/canonical-kubernetes - step.py:134 - Storing environment
2017-11-03 00:01:36,729 [DEBUG] conjure-up/canonical-kubernetes - step.py:140 - Executing script: /home/benf/.cache/conjure-up/canonical-kubernetes/addons/deis/steps/step-01_install-workflow
2017-11-03 00:02:28,322 [DEBUG] conjure-up/canonical-kubernetes - events.py:53 - Setting Error at conjureup/events.py:147
2017-11-03 00:02:28,323 [ERROR] conjure-up/canonical-kubernetes - events.py:159 - Unhandled exception in <Task finished coro=<RunStepsController.run_steps() done, defined at /snap/conjure-up/745/lib/python3.6/site-packages/conjureup/controllers/runsteps/gui.py:15> exception=Exception('Failure in step /home/benf/.cache/conjure-up/canonical-kubernetes/addons/deis/steps/step-01_install-workflow',)>
Traceback (most recent call last):
  File "/snap/conjure-up/745/lib/python3.6/site-packages/conjureup/controllers/runsteps/gui.py", line 19, in run_steps
    step.result = await step.run(app.ui.set_footer)
  File "/snap/conjure-up/745/lib/python3.6/site-packages/conjureup/models/step.py", line 162, in run
    raise Exception("Failure in step {}".format(self.filename))
Exception: Failure in step /home/benf/.cache/conjure-up/canonical-kubernetes/addons/deis/steps/step-01_install-workflow
2017-11-03 00:02:28,353 [DEBUG] conjure-up/canonical-kubernetes - __init__.py:21 - Showing dialog for exception: Failure in step /home/benf/.cache/conjure-up/canonical-kubernetes/addons/deis/steps/step-01_install-workflow
```

## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
/snap/bin/juju

juju version
2.2.3-xenial-amd64

which conjure-up
/snap/bin/conjure-up

conjure-up --version
conjure-up 2.3.1

which lxc
/usr/bin/lxc

/snap/bin/lxc config show
/usr/bin/lxc config show
config:
  core.https_address: '[::]'


/snap/bin/lxc version
2.18


cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

too many questions, no time..maybe I can add them later!!!

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.


## What Spell was Selected?

## What provider (aws, maas, localhost, etc)?

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

## Additional Information

**Comment by battlemidget** [comment]
Please provide the information requested in the template.

**Comment by fatdrag0n** [comment]
No time, sorry, go ahead close it if you can't proceed.. maybe I can duplicate the error during holidays or something!

**Comment by battlemidget** [comment]
@fatdrag0n thanks, if we could get a reproducible error or if you get a chance to try again we can reopen this.
