### ISSUE TITLE
Unable to bootstrap (cloud type:localhost)

### ISSUE THREAD

**Issue by B1T0** [conjure-up/conjure-up#1328]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
    /snap/bin/juju
juju version
    2.3.2-xenial-amd64

which conjure-up
    /snap/bin/conjure-up
conjure-up --version
    conjure-up 2.5.3-rc1

which lxc
    /snap/bin/lxc
/snap/bin/lxc config show
    config:
      core.https_address: '[::]'
/snap/bin/lxc version
    2.21

cat /etc/lsb-release
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=16.04
    DISTRIB_CODENAME=xenial
    DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```
Attaching the file did not work. If you really need it, i I will try uploading it again.

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
    sosreport (version 3.4)

    no valid plugins were enabled
```

The resulting output file can be attached to this issue.

## What Spell was Selected?
OpenStack with NovaLXD

## What provider (aws, maas, localhost, etc)?
localhost

## Commands ran

Please outline what commands were run to install and execute conjure-up:
I used [this tutorial](https://tutorials.ubuntu.com/tutorial/install-openstack-with-conjure-up?_ga=2.206421972.651240382.1517665493-353644902.1491418301#0) to install OpenStack. After choosing "Deploy all 15 Remaining Applications" the program fails.

## Additional Information
In the conjure-up.log the following error is printed:
```
2018-02-08 14:42:49,457 [DEBUG] conjure-up/openstack-novalxd - juju.py:187 - Bootstrapping to set region: {}
2018-02-08 14:42:49,458 [DEBUG] conjure-up/openstack-novalxd - juju.py:223 - bootstrap cmd: ['/snap/bin/juju', 'bootstrap', 'localhost/localhost', 'conjure-up-localhost-ab4', '--default-model', 'conjure-openstack-novalx-66f', '--config', 'image-stream=daily', '--bootstrap-series', 'xenial']
2018-02-08 14:42:50,092 [ERROR] conjure-up/openstack-novalxd - common.py:52 - Error bootstrapping controller: ['ERROR Get https://10.238.243.1:8443/1.0: remote error: tls: handshake failure']
2018-02-08 14:42:50,094 [DEBUG] conjure-up/openstack-novalxd - events.py:53 - Setting Error at conjureup/events.py:148
2018-02-08 14:42:50,096 [ERROR] conjure-up/openstack-novalxd - events.py:160 - Unhandled exception in <Task finished coro=<BaseBootstrapController.run() done, defined at /snap/conjure-up/924/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py:15> exception=BootstrapError('Unable to bootstrap (cloud type: localhost)',)>
Traceback (most recent call last):
  File "/snap/conjure-up/924/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py", line 21, in run
    await self.do_bootstrap()
  File "/snap/conjure-up/924/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py", line 57, in do_bootstrap
    app.provider.cloud_type))
conjureup.errors.BootstrapError: Unable to bootstrap (cloud type: localhost)
```
I checked the proxy settings but these are correct.

**Comment by B1T0** [comment]
After checking the proxy settings again and reading the help of conjure-up I tried to start it using the --apt-[https-]proxy and --http[s]-proxy options, but this did not help me. Now I get a different error.

```
2018-02-13 13:49:58,458 [DEBUG] conjure-up/openstack-novalxd - juju.py:187 - Bootstrapping to set region: {}
2018-02-13 13:49:58,458 [DEBUG] conjure-up/openstack-novalxd - juju.py:223 - bootstrap cmd: ['/snap/bin/juju', 'bootstrap', 'localhost/localhost', 'conjure-up-localhost-1c2', '--default-model', 'conjure-openstack-novalx-2c0', '--config', 'image-stream=daily', '-- PROXY SETTINGS (I deleted the IPs)', '--bootstrap-series', 'xenial']
2018-02-13 13:49:58,473 [DEBUG] conjure-up/openstack-novalxd - events.py:53 - Awaiting Bootstrapped at conjureup/controllers/bootstrap/tui.py:17
2018-02-13 13:50:12,615 [ERROR] conjure-up/openstack-novalxd - common.py:52 - Error bootstrapping controller: ['Creating Juju controller "conjure-up-localhost-1c2" on localhost/localhost', 'Looking for packaged Juju agent version 2.3.1 for amd64', 'To configure your system to better support LXD containers, please see: https://github.com/lxc/lxd/blob/master/doc/production-setup.md', 'Launching controller instance(s) on localhost/localhost...', '   ', ' - unable to get LXD image for juju/xenial/amd64: Get https://cloud-images.ubuntu.com/daily//streams/v1/index.json: Unable to connect to: cloud-images.ubuntu.com:443', 'ERROR failed to bootstrap model: cannot start bootstrap instance: unable to get LXD image for juju/xenial/amd64: Get https://cloud-images.ubuntu.com/daily//streams/v1/index.json: Unable to connect to: cloud-images.ubuntu.com:443']
2018-02-13 13:50:12,617 [DEBUG] conjure-up/openstack-novalxd - events.py:53 - Setting Error at conjureup/events.py:148
2018-02-13 13:50:12,618 [ERROR] conjure-up/openstack-novalxd - events.py:160 - Unhandled exception in <Task finished coro=<BaseBootstrapController.run() done, defined at /snap/conjure-up/924/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py:15> exception=BootstrapError('Unable to bootstrap (cloud type: localhost)',)>
Traceback (most recent call last):
  File "/snap/conjure-up/924/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py", line 21, in run
    await self.do_bootstrap()
  File "/snap/conjure-up/924/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py", line 57, in do_bootstrap
    app.provider.cloud_type))
conjureup.errors.BootstrapError: Unable to bootstrap (cloud type: localhost)
```

**Comment by battlemidget** [comment]
The error indicates you can not access the required cloud-images site `Unable to connect to: cloud-images.ubuntu.com:443`

**Comment by B1T0** [comment]
It seems to fail due to my proxy server 😞 

I will close this Issue.
