### ISSUE TITLE
conjure-down app.env['PATH'] -- NoneType object is not subscriptable

### ISSUE THREAD

**Issue by JimMcHale** [conjure-up/conjure-up#1338]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
/snap/bin/juju

juju version
2.3.3-xenial-amd64

which conjure-up
/snap/bin/conjure-up 
/snap/bin/conjure-down

conjure-up --version
conjure-up 2.5.3

which lxc
/snap/bin/lxc config show
/snap/bin/lxc version

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1744710/conjure-up.tar.gz)

```

## Sosreport

Please attach a sosreport:
[sosreport-jmchale-20180221112311.tar.gz](https://github.com/conjure-up/conjure-up/files/1744777/sosreport-jmchale-20180221112311.tar.gz)

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.


## What Spell was Selected?
none or kubernetes
both fail with the same error

## What provider (aws, maas, localhost, etc)?
localhost

### MAAS Users
Which version of MAAS?
n/a

## Commands ran
conjure-down

conjure-down kubernetes

both fail with the same error

Please outline what commands were run to install and execute conjure-up:

## Additional Information
conjure-down
Traceback (most recent call last):
  File "/snap/conjure-up/967/bin/conjure-down", line 11, in <module>
    load_entry_point('conjure-up==2.5.3', 'console_scripts', 'conjure-down')()
  File "/snap/conjure-up/967/lib/python3.6/site-packages/conjureup/destroy.py", line 73, in main
    juju.set_bin_path()
  File "/snap/conjure-up/967/lib/python3.6/site-packages/conjureup/juju.py", line 61, in set_bin_path
    app.env['PATH'])
TypeError: 'NoneType' object is not subscriptable


conjure-down kubernetes
Traceback (most recent call last):
  File "/snap/conjure-up/967/bin/conjure-down", line 11, in <module>
    load_entry_point('conjure-up==2.5.3', 'console_scripts', 'conjure-down')()
  File "/snap/conjure-up/967/lib/python3.6/site-packages/conjureup/destroy.py", line 73, in main
    juju.set_bin_path()
  File "/snap/conjure-up/967/lib/python3.6/site-packages/conjureup/juju.py", line 61, in set_bin_path
    app.env['PATH'])
TypeError: 'NoneType' object is not subscriptable

This is happening on a system running ubuntu 16.04.3 LTS and also in an azure vm running ubuntu 16.04.3 LTS

**Comment by kingttx** [comment]
Same with conjure-up version 2.5.6, Ubuntu 16.04.4, and OpenStack NovaLXD on localhost.

**Comment by kingttx** [comment]
Refreshed to --edge, still same error.

**Comment by kingttx** [comment]
Refreshed to --beta, still same error.
