### ISSUE TITLE
Unable to conjure-up CDK on arm64

### ISSUE THREAD

**Issue by moon127** [conjure-up/conjure-up#1369]
Unable to deploy CDK using conjure-up on ARM64, as the kubernetes-master and worker units fail at harm install due to lack of kubectl snap under arm64:

2018-03-15 15:30:49 DEBUG install error: snap "kubectl" not found (at least in channel "1.9/stable")
2018-03-15 15:30:49 DEBUG install 
2018-03-15 15:30:49 DEBUG install error: snap "kubectl" not found (at least in channel "1.9/stable")
2018-03-15 15:30:49 DEBUG install 
2018-03-15 15:30:49 DEBUG install error: snap "kubectl" not found (at least in channel "1.9/stable")
2018-03-15 15:30:49 DEBUG install 
2018-03-15 15:30:50 DEBUG install Traceback (most recent call last):
2018-03-15 15:30:50 DEBUG install   File "/var/lib/juju/agents/unit-kubernetes-master-0/charm/hooks/install", line 19, in <module>
2018-03-15 15:30:50 DEBUG install     main()
2018-03-15 15:30:50 DEBUG install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 72, in main
2018-03-15 15:30:50 DEBUG install     bus.dispatch(restricted=restricted_mode)
2018-03-15 15:30:50 DEBUG install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 375, in dispatch
2018-03-15 15:30:50 DEBUG install     _invoke(other_handlers)
2018-03-15 15:30:50 DEBUG install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 351, in _invoke
2018-03-15 15:30:50 DEBUG install     handler.invoke()
2018-03-15 15:30:50 DEBUG install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 173, in invoke
2018-03-15 15:30:50 DEBUG install     self._action(*args)
2018-03-15 15:30:50 DEBUG install   File "/var/lib/juju/agents/unit-kubernetes-master-0/charm/reactive/kubernetes_master.py", line 240, in do_upgrade
2018-03-15 15:30:50 DEBUG install     install_snaps()
2018-03-15 15:30:50 DEBUG install   File "/var/lib/juju/agents/unit-kubernetes-master-0/charm/reactive/kubernetes_master.py", line 248, in install_snaps
2018-03-15 15:30:50 DEBUG install     snap.install('kubectl', channel=channel, classic=True)
2018-03-15 15:30:50 DEBUG install   File "lib/charms/layer/snap.py", line 45, in install
2018-03-15 15:30:50 DEBUG install     _install_store(snapname, **kw)
2018-03-15 15:30:50 DEBUG install   File "lib/charms/layer/snap.py", line 147, in _install_store
2018-03-15 15:30:50 DEBUG install     stderr=subprocess.STDOUT)
2018-03-15 15:30:50 DEBUG install   File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
2018-03-15 15:30:50 DEBUG install     **kwargs).stdout
2018-03-15 15:30:50 DEBUG install   File "/usr/lib/python3.5/subprocess.py", line 708, in run
2018-03-15 15:30:50 DEBUG install     output=stdout, stderr=stderr)
2018-03-15 15:30:50 DEBUG install subprocess.CalledProcessError: Command '['snap', 'install', '--channel=1.9/stable', '--classic', 'kubectl']' returned non-zero exit status 1
2018-03-15 15:30:50 ERROR juju.worker.uniter.operation runhook.go:107 hook "install" failed: exit status 1
2018-03-15 15:30:50 INFO juju.worker.uniter resolver.go:100 awaiting error resolution for "install" hook
2018-03-15 15:30:50 INFO juju.worker.uniter resolver.go:100 awaiting error resolution for "install" hook
2018-03-15 15:32:17 INFO juju.worker.uniter resolver.go:100 awaiting error resolution for "install" hook
^C
ubuntu@juju-50b092-6:~$ sudo snap install --channel=1.9/stable --classic kubectl
error: snap "kubectl" not found (at least in channel "1.9/stable")

Expected outcome here would be for a conjure-up target listed from the menu, such as CDK, to be deployable on the target architecture.

gareth@po-2:~$ juju --version
2.2.6-xenial-arm64
gareth@po-2:~$ which conjure-up
/snap/bin/conjure-up
gareth@po-2:~$ conjure-up --version
conjure-up 2.4.2
gareth@po-2:~$ which lxc
/snap/bin/lxc
gareth@po-2:~$ /snap/bin/lxc config show
config:
  core.https_address: '[::]'
gareth@po-2:~$ /snap/bin/lxc version
2.21
gareth@po-2:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
gareth@po-2:~$ uname -a
Linux po-2 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:47 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

**Comment by battlemidget** [comment]
Yea this is a known issue and we're currently working to resolve building snaps for those architectures

@tvansteenburgh

**Comment by wwwtyro** [comment]
@battlemidget Feel free to assign to me, I'll ping you when it's ready.

**Comment by battlemidget** [comment]
@wwwtyro thanks man!
