### ISSUE TITLE
uncaught ConnectionClosedError in deploystatus 

### ISSUE THREAD

**Issue by mikemccracken** [conjure-up/conjure-up#137]
```python-traceback
Exception in ev.run():
Traceback (most recent call last):
  File "/home/mmccrack/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/home/mmccrack/conjure-up/conjure-dev/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/mmccrack/conjure-up/conjure-dev/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/home/mmccrack/conjure-up/conjure-dev/lib/python3.5/site-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/mmccrack/conjure-up/conjure-dev/lib/python3.5/site-packages/urwid/main_loop.py", line 164, in cb
    callback(self, user_data)
  File "/home/mmccrack/conjure-up/conjure/controllers/deploystatus/gui.py", line 46, in __refresh
    this.view.refresh_nodes()
  File "/home/mmccrack/conjure-up/conjure/ui/views/deploystatus.py", line 22, in refresh_nodes
    status = model_status()
  File "/home/mmccrack/conjure-up/conjure/juju.py", line 31, in _decorator
    return f(*args, **kwargs)
  File "/home/mmccrack/conjure-up/conjure/api/models.py", line 42, in model_status
    return juju.CLIENT.Client(request="FullStatus")
  File "/home/mmccrack/conjure-up/macumba/v2.py", line 113, in _request
    'Params': params})
  File "/home/mmccrack/conjure-up/macumba/v2.py", line 124, in call
    return self.receive(req_id, timeout)
  File "/home/mmccrack/conjure-up/macumba/api.py", line 119, in receive
    res = self.conn.do_receive(request_id)
  File "/home/mmccrack/conjure-up/macumba/ws.py", line 75, in do_receive
    raise ConnectionClosedError
macumba.errors.ConnectionClosedError
```

**Comment by battlemidget** [comment]
This problem cropped up because the underlying zfs vol was full. Not sure how we can reliably check for this since macumba thinks juju has gone away

**Comment by mikemccracken** [comment]
I suggest catching the error and showing a dialog saying 'a problem has
occurred contacting juju' or something, and give a choice to retry or bail

**Comment by battlemidget** [comment]
Hard to reproduce, we'll keep this for later in case it crops back up
