### ISSUE TITLE
Glance: Error on image upload [ObjectNotFound: [errno 2] error opening pool 'glance']

### ISSUE THREAD

**Issue by ToniIltanen** [conjure-up/conjure-up#1379]
With the latest snap from conjure-up (tested with both --classic and --edge), image upload to glance fails from Horizon. also using glance image-create fails on the same error.

Result: All created images stay in queue status

Spell: OpenStack with NovaLXD on localhost

**glance-api -log from creating an image through Horizon:**
```
2018-03-23 07:53:26.757 4175 INFO eventlet.wsgi.server [req-41689456-b75b-4ca4-8f53-e55dcd535339 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 07:53:26] "POST /v2/images HTTP/1.1" 201 920 0.106402
2018-03-23 07:53:26.827 4173 INFO eventlet.wsgi.server [req-a23167a4-b782-400c-b5b2-b5c3f0ae1eb7 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 07:53:26] "GET /v2/images?limit=1000&sort_key=created_at&sort_dir=desc HTTP/1.1" 200 887 0.022907
2018-03-23 07:53:26.835 4173 INFO eventlet.wsgi.server [req-17896fb1-89d0-40ef-bccc-d62ea6c9822b 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 07:53:26] "GET /v2/schemas/image HTTP/1.1" 200 4352 0.003657
2018-03-23 07:53:26.912 4175 ERROR glance.api.v2.image_data [req-185d528d-9049-4327-b616-824faa9050f8 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] Failed to upload image data due to internal error: ObjectNotFound: [errno 2] error opening pool 'glance'
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi [req-185d528d-9049-4327-b616-824faa9050f8 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] Caught error: [errno 2] error opening pool 'glance': ObjectNotFound: [errno 2] error opening pool 'glance'
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi Traceback (most recent call last):
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance/common/wsgi.py", line 1227, in __call__
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi     request, **action_args)
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance/common/wsgi.py", line 1270, in dispatch
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi     return method(*args, **kwargs)
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance/common/utils.py", line 414, in wrapped
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi     return func(self, req, *args, **kwargs)
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance/api/v2/image_data.py", line 267, in upload
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi     self._restore(image_repo, image)
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi     self.force_reraise()
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi     six.reraise(self.type_, self.value, self.tb)
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance/api/v2/image_data.py", line 132, in upload
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi     image.set_data(data, size)
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance/domain/proxy.py", line 195, in set_data
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi     self.base.set_data(data, size)
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance/notifier.py", line 480, in set_data
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi     _send_notification(notify_error, 'image.upload', msg)
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi     self.force_reraise()
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi     six.reraise(self.type_, self.value, self.tb)
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance/notifier.py", line 427, in set_data
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi     self.repo.set_data(data, size)
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance/api/policy.py", line 193, in set_data
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi     return self.image.set_data(*args, **kwargs)
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance/quota/__init__.py", line 304, in set_data
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi     self.image.set_data(data, size=size)
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance/location.py", line 439, in set_data
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi     verifier=verifier)
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance_store/backend.py", line 453, in add_to_backend
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi     verifier)
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance_store/backend.py", line 426, in store_add_to_backend
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi     verifier=verifier)
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance_store/capabilities.py", line 225, in op_checker
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi     return store_op_fun(store, *args, **kwargs)
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance_store/_drivers/rbd.py", line 458, in add
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi     with conn.open_ioctx(self.pool) as ioctx:
2018-03-23 07:53:26.947 4175 ERROR glance.common.wsgi   
```

**Comment by ToniIltanen** [comment]
glance image-create result:

```
ubuntu@juju-47a823-7:/tmp$ glance image-create --name cirros-test-2 --visibility public --disk-format qcow2 --container-format bare < /tmp/cirros-0.4.0-x86_64-disk.img
+------------------+--------------------------------------+
| Property         | Value                                |
+------------------+--------------------------------------+
| checksum         | None                                 |
| container_format | bare                                 |
| created_at       | 2018-03-23T09:01:50Z                 |
| disk_format      | qcow2                                |
| id               | 220f6855-30a5-4448-bd1a-181e456b7bec |
| locations        | []                                   |
| min_disk         | 0                                    |
| min_ram          | 0                                    |
| name             | cirros-test-2                        |
| owner            | ecd3c6a4b5ee4f3d82df93ff9ec48acf     |
| protected        | False                                |
| size             | None                                 |
| status           | queued                               |
| tags             | []                                   |
| updated_at       | 2018-03-23T09:01:50Z                 |
| virtual_size     | None                                 |
| visibility       | public                               |
+------------------+--------------------------------------+
500 Internal Server Error: The server has either erred or is incapable of performing the requested operation. (HTTP 500)```

Log:
```
2018-03-23 08:46:07.165 4174 INFO eventlet.wsgi.server [req-13b1ffcb-b979-443a-a952-992aea395367 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 08:46:07] "GET /v2/images?status=active&limit=1000&sort_key=created_at&sort_dir=desc HTTP/1.1" 200 327 0.026348
2018-03-23 08:46:07.271 4173 INFO eventlet.wsgi.server [req-8184413c-0bf0-47f7-a37f-0f7b82bce80e 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 08:46:07] "GET /v2/schemas/metadefs/namespace HTTP/1.1" 200 3300 0.003841
2018-03-23 08:46:07.284 4173 INFO eventlet.wsgi.server [req-1896aba0-2b35-455d-9b95-82b9147adb01 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 08:46:07] "GET /v2/schemas/metadefs/namespace HTTP/1.1" 200 3300 0.008988
2018-03-23 08:46:07.287 4169 INFO eventlet.wsgi.server [req-930eb7f5-36fa-4f40-b540-5f02dd0ab790 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 08:46:07] "GET /v2/schemas/metadefs/namespace HTTP/1.1" 200 3300 0.005573
2018-03-23 08:46:07.303 4174 INFO eventlet.wsgi.server [req-6b23bfc7-e5ca-420b-bd75-834e9fd7ffcd 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 08:46:07] "GET /v2/schemas/metadefs/namespace HTTP/1.1" 200 3300 0.006958
2018-03-23 08:46:07.305 4173 INFO eventlet.wsgi.server [req-0a231aa7-284b-416c-9704-3297d9781aad 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 08:46:07] "GET /v2/metadefs/namespaces?sort_key=namespace&resource_types=OS%3A%3ANova%3A%3AServer&properties_target=metadata&limit=1000&sort_dir=asc HTTP/1.1" 200 408 0.028643
2018-03-23 08:46:07.308 4169 INFO eventlet.wsgi.server [req-489a6c96-67cc-40da-ba3f-7dd4a1a4b3bc 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 08:46:07] "GET /v2/metadefs/namespaces?sort_key=namespace&resource_types=OS%3A%3ANova%3A%3AFlavor&properties_target=&limit=1000&sort_dir=asc HTTP/1.1" 200 400 0.013131
2018-03-23 08:46:07.310 4173 INFO eventlet.wsgi.server [req-3525fb08-0a51-4d8a-ab21-8d7636bff900 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 08:46:07] "GET /v2/metadefs/namespaces?sort_key=namespace&resource_types=OS%3A%3AGlance%3A%3AImage&properties_target=&limit=1000&sort_dir=asc HTTP/1.1" 200 401 0.018040
2018-03-23 08:46:07.321 4173 INFO eventlet.wsgi.server [req-87c11ccf-ea1d-4bee-a98b-d6da9bfb6d1d 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 08:46:07] "GET /v2/schemas/metadefs/namespace HTTP/1.1" 200 3300 0.005199
2018-03-23 08:46:07.322 4174 INFO eventlet.wsgi.server [req-5ccbec39-5a9d-4286-99a1-629d49616405 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 08:46:07] "GET /v2/metadefs/namespaces?sort_key=namespace&resource_types=OS%3A%3ACinder%3A%3AVolumes&properties_target=&limit=1000&sort_dir=asc HTTP/1.1" 200 403 0.007605
2018-03-23 08:46:07.339 4173 INFO eventlet.wsgi.server [req-6d4b1432-0126-4a14-994a-0264c7d94bb1 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 08:46:07] "GET /v2/metadefs/namespaces?sort_key=namespace&resource_types=OS%3A%3ANova%3A%3AServer&properties_target=scheduler_hints&limit=1000&sort_dir=asc HTTP/1.1" 200 415 0.008069
2018-03-23 08:47:15.696 4173 INFO eventlet.wsgi.server [req-21ff30d1-d9d0-434e-a6cd-b7bc38afc021 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 08:47:15] "GET /v2/images?limit=1000&sort_key=created_at&sort_dir=desc HTTP/1.1" 200 887 0.028503
2018-03-23 08:47:15.719 4173 INFO eventlet.wsgi.server [req-5953073f-de03-4137-8fae-a414c1052852 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 08:47:15] "GET /v2/schemas/image HTTP/1.1" 200 4352 0.003353
2018-03-23 08:59:33.375 4169 WARNING glance.api.versions [-] The Images (Glance) v1 API is deprecated and will be removed on or after the Pike release, following the standard OpenStack deprecation policy. Currently, the solution is to set enable_v1_api=False and enable_v2_api=True in your glance-api.conf file. Once those options are removed from the code, Images (Glance) v2 API will be switched on by default and will be the only option to deploy and use.
2018-03-23 08:59:33.376 4169 INFO eventlet.wsgi.server [-] 10.101.0.83 - - [23/Mar/2018 08:59:33] "GET /versions HTTP/1.1" 200 1101 0.001388
2018-03-23 08:59:34.005 4169 INFO eventlet.wsgi.server [req-d65940cc-df22-42f3-a967-761e0c688c73 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 08:59:34] "GET /v2/schemas/image HTTP/1.1" 200 4352 0.624505
2018-03-23 08:59:34.015 4169 INFO eventlet.wsgi.server [req-8e57c066-a06b-480b-8cfa-0bd1f98367ad 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 08:59:34] "GET /v2/schemas/metadefs/namespace HTTP/1.1" 200 3300 0.004878
2018-03-23 08:59:34.022 4169 INFO eventlet.wsgi.server [req-962935aa-6db6-49ac-b3f5-01ca97471768 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 08:59:34] "GET /v2/schemas/metadefs/resource_type HTTP/1.1" 200 1462 0.003696
2018-03-23 08:59:34.884 4175 INFO eventlet.wsgi.server [req-9591d540-d612-4444-9cf8-76b7b9a01c96 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 08:59:34] "GET /v2/images?limit=20&sort_key=name&sort_dir=asc HTTP/1.1" 200 878 0.449388
2018-03-23 08:59:34.892 4175 INFO eventlet.wsgi.server [req-a9d46cc6-c63f-4e1b-b3cf-ec2ad9486775 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 08:59:34] "GET /v2/schemas/image HTTP/1.1" 200 4352 0.004006
2018-03-23 09:01:34.790 4173 WARNING glance.api.versions [-] The Images (Glance) v1 API is deprecated and will be removed on or after the Pike release, following the standard OpenStack deprecation policy. Currently, the solution is to set enable_v1_api=False and enable_v2_api=True in your glance-api.conf file. Once those options are removed from the code, Images (Glance) v2 API will be switched on by default and will be the only option to deploy and use.
2018-03-23 09:01:34.791 4173 INFO eventlet.wsgi.server [-] 10.101.0.83 - - [23/Mar/2018 09:01:34] "GET /versions HTTP/1.1" 200 1101 0.001591
2018-03-23 09:01:35.882 4173 INFO eventlet.wsgi.server [req-60872638-a11e-4591-b1c2-7ff543838046 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 09:01:35] "GET /v2/schemas/image HTTP/1.1" 200 4352 0.550018
2018-03-23 09:01:35.891 4173 INFO eventlet.wsgi.server [req-4a7aef09-b0c0-4e93-b5e9-4e0f94ee429b 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 09:01:35] "GET /v2/schemas/image HTTP/1.1" 200 4352 0.004009
2018-03-23 09:01:49.832 4175 WARNING glance.api.versions [-] The Images (Glance) v1 API is deprecated and will be removed on or after the Pike release, following the standard OpenStack deprecation policy. Currently, the solution is to set enable_v1_api=False and enable_v2_api=True in your glance-api.conf file. Once those options are removed from the code, Images (Glance) v2 API will be switched on by default and will be the only option to deploy and use.
2018-03-23 09:01:49.833 4175 INFO eventlet.wsgi.server [-] 10.101.0.83 - - [23/Mar/2018 09:01:49] "GET /versions HTTP/1.1" 200 1101 0.001835
2018-03-23 09:01:50.303 4175 INFO eventlet.wsgi.server [req-32ad5b87-42c1-484f-9a41-673c3ede5fec 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 09:01:50] "GET /v2/schemas/image HTTP/1.1" 200 4352 0.057805
2018-03-23 09:01:50.311 4175 INFO eventlet.wsgi.server [req-c949d9d8-250b-4bab-8454-e479a0540255 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 09:01:50] "GET /v2/schemas/image HTTP/1.1" 200 4352 0.004803
2018-03-23 09:01:50.374 4175 INFO eventlet.wsgi.server [req-b374023e-8dfb-42dc-a2bf-f3f06bfda0d4 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 09:01:50] "POST /v2/images HTTP/1.1" 201 920 0.036807
2018-03-23 09:01:50.462 4175 ERROR glance.api.v2.image_data [req-21c7dab3-9f32-4aaf-9087-f83cb585a364 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] Failed to upload image data due to internal error: ObjectNotFound: [errno 2] error opening pool 'glance'
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi [req-21c7dab3-9f32-4aaf-9087-f83cb585a364 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] Caught error: [errno 2] error opening pool 'glance': ObjectNotFound: [errno 2] error opening pool 'glance'
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi Traceback (most recent call last):
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance/common/wsgi.py", line 1227, in __call__
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi     request, **action_args)
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance/common/wsgi.py", line 1270, in dispatch
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi     return method(*args, **kwargs)
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance/common/utils.py", line 414, in wrapped
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi     return func(self, req, *args, **kwargs)
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance/api/v2/image_data.py", line 267, in upload
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi     self._restore(image_repo, image)
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi     self.force_reraise()
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi     six.reraise(self.type_, self.value, self.tb)
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance/api/v2/image_data.py", line 132, in upload
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi     image.set_data(data, size)
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance/domain/proxy.py", line 195, in set_data
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi     self.base.set_data(data, size)
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance/notifier.py", line 480, in set_data
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi     _send_notification(notify_error, 'image.upload', msg)
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi     self.force_reraise()
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi     six.reraise(self.type_, self.value, self.tb)
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance/notifier.py", line 427, in set_data
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi     self.repo.set_data(data, size)
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance/api/policy.py", line 193, in set_data
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi     return self.image.set_data(*args, **kwargs)
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance/quota/__init__.py", line 304, in set_data
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi     self.image.set_data(data, size=size)
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance/location.py", line 439, in set_data
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi     verifier=verifier)
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance_store/backend.py", line 453, in add_to_backend
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi     verifier)
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance_store/backend.py", line 426, in store_add_to_backend
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi     verifier=verifier)
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance_store/capabilities.py", line 225, in op_checker
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi     return store_op_fun(store, *args, **kwargs)
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi   File "/usr/lib/python2.7/dist-packages/glance_store/_drivers/rbd.py", line 458, in add
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi     with conn.open_ioctx(self.pool) as ioctx:
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi   File "rados.pyx", line 498, in rados.requires.wrapper.validate_func (/build/ceph-dRxO9O/ceph-12.2.2/obj-x86_64-linux-gnu/src/pybind/rados/pyrex/rados.c:4922)
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi   File "rados.pyx", line 1193, in rados.Rados.open_ioctx (/build/ceph-dRxO9O/ceph-12.2.2/obj-x86_64-linux-gnu/src/pybind/rados/pyrex/rados.c:14362)
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi ObjectNotFound: [errno 2] error opening pool 'glance'
2018-03-23 09:01:50.491 4175 ERROR glance.common.wsgi 
2018-03-23 09:01:50.507 4175 INFO eventlet.wsgi.server [req-21c7dab3-9f32-4aaf-9087-f83cb585a364 7e3e8611991f4d76849357f9c5954f1f ecd3c6a4b5ee4f3d82df93ff9ec48acf - 185647530e46491b86b391c5c5275828 185647530e46491b86b391c5c5275828] 10.101.0.83 - - [23/Mar/2018 09:01:50] "PUT /v2/images/220f6855-30a5-4448-bd1a-181e456b7bec/file HTTP/1.1" 500 454 0.123640```

**Comment by inetuid** [comment]
Same issue here.

**Comment by ToniIltanen** [comment]
any progress on this?

**Comment by tcrisall** [comment]
similar problem on image import.  I'm thinking this relates back to the 'glance' pool not being created in ceph?

according to /etc/glance/glance-api.conf:
  default_store = rbd
  rbd_store_ceph_conf = /etc/ceph/ceph.conf
  rbd_store_user = glance
  rbd_store_pool = glance

error from /var/log/glance/glance-api.log:
  2018-04-16 01:03:28.561 2768 ERROR glance.async.taskflow_executor [-] Failed
  to execute task 94d6b235-c597-4984-b8f6-02c0016c67b4: [errno 2] error opening
  pool 'glance': ObjectNotFound: [errno 2] error opening pool 'glance'

when I pop onto the ceph mon node and look I get:
  #ceph osd pool ls
  default.rgw.buckets

**Comment by battlemidget** [comment]
Can you test `sudo snap refresh conjure-up --edge`? We've made some recent adjustments to openstack-novalxd spell

**Comment by battlemidget** [comment]
https://github.com/conjure-up/spells/pull/175

**Comment by tcrisall** [comment]
I will take a look at the new work 

As a side note - I was able to get up and playing by attaching to one of the ceph-mon nodes and renaming the ceph pool 'default.rgw.buckets' to 'glance'...
