### ISSUE TITLE
rarely conjure-up will fail at the end with a sudo password issue

### ISSUE THREAD

**Issue by hyperbolic2346** [conjure-up/conjure-up#1386]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [N] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [N] Is conjure-up running inside a virtual machine?
- [Y] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju - /snap/bin/juju
juju version - 2.3.5-artful-amd64

which conjure-up - /snap/bin/conjure-up
conjure-up --version - conjure-up 2.5.6
```

## What Spell was Selected?
canonical-kubernetes
## What provider (aws, maas, localhost, etc)?
aws
## Commands ran
conjure-up canonical-kubernetes

## Additional Information
2018-03-29 17:28:10,414 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:17 - Showing screen: Running Post-Deploy Steps
2018-03-29 17:28:10,415 [INFO] conjure-up/canonical-kubernetes - step.py:215 - Running Canonical Distribution of Kubernetes step: 00_process-providertype after-deploy.
2018-03-29 17:28:10,560 [DEBUG] conjure-up/canonical-kubernetes - step.py:254 - Storing environment
2018-03-29 17:28:10,569 [DEBUG] conjure-up/canonical-kubernetes - step.py:260 - Executing script: /home/knobby/.cache/conjure-up/canonical-kubernetes/steps/00_process-providertype/after-deploy
2018-03-29 17:28:10,587 [INFO] conjure-up/canonical-kubernetes - step.py:215 - Running Canonical Distribution of Kubernetes step: 02_get-kubectl after-deploy.
2018-03-29 17:28:11,779 [DEBUG] conjure-up/canonical-kubernetes - events.py:53 - Setting Error at conjureup/events.py:148
2018-03-29 17:28:11,780 [DEBUG] conjure-up/canonical-kubernetes - events.py:152 - Would not track exception: The "Canonical Distribution of Kubernetes" step "Kubernetes Cluster Controller" requires sudo: password failed
2018-03-29 17:28:11,780 [ERROR] conjure-up/canonical-kubernetes - events.py:160 - Unhandled exception in <Task finished coro=<RunStepsController.run_steps() done, defined at /snap/conjure-up/983/lib/python3.6/site-packages/conjureup/controllers/runsteps/gui.py:14> exception=SudoError('The "Canonical Distribution of Kubernetes" step "Kubernetes Cluster Controller" requires sudo: password failed',)>
Traceback (most recent call last):
  File "/snap/conjure-up/983/lib/python3.6/site-packages/conjureup/controllers/runsteps/gui.py", line 19, in run_steps
    step.result = await step.after_deploy(view.set_footer)
  File "/snap/conjure-up/983/lib/python3.6/site-packages/conjureup/models/step.py", line 132, in after_deploy
    return await self.run(PHASES.AFTER_DEPLOY, msg_cb)
  File "/snap/conjure-up/983/lib/python3.6/site-packages/conjureup/models/step.py", line 225, in run
    'passwordless sudo required',
conjureup.utils.SudoError: The "Canonical Distribution of Kubernetes" step "Kubernetes Cluster Controller" requires sudo: password failed
2018-03-29 17:28:11,793 [DEBUG] conjure-up/canonical-kubernetes - __init__.py:29 - Showing dialog for exception: The "Canonical Distribution of Kubernetes" step "Kubernetes Cluster Controller" requires sudo: password failed

**Comment by johnsca** [comment]
The only reason I can think this might happen would be that sudo had cached auth at the start of the deployment that expired during the deployment.  But I would expect the validation on the steps input screen would still require you to enter the password and validate it.  Maybe there's an issue with that which lets invalid passwords through when there's cached auth?

**Comment by johnsca** [comment]
Of course, the better fix would be to remove the requirement for entering the root password entirely, but that would require making `snap login` a pre-req.

**Comment by macduff23** [comment]
sudo passwd - worked for me on this issue in the same env/versions, It was  frustrating and really Simple to fix - after allot of effort on a fresh Artful install. This was the 2nd run on this where I received this error on a pretty minimal fresh box.   From out of the box  ubuntu server and snapd packages with Lxd

1.Insure non root user (ubuntu/set.usr.path.var) member of sudo group - sudo passwd  (newpass)
2. Install remove dpkg  purge all legacy related apt related packages -  lxd /lxc/juju/conjure-up/
2.Assure using snap d. to install conjure/juju/lxd ect.. lxd init 
apt-get update 
I rebooted... login as usr/ubuntu - conjure-up 

I posted this here because very little comes back search wise on sudo failure during conjure.
something like that sudo user love. cheers.
