### ISSUE TITLE
Hi am trying to install OpenStack on a single machine with LXD and on localhost, however its stuck in bootstrap for long time and after 20 minutes its got timeout and failed with below error - 

### ISSUE THREAD

**Issue by MIRZAPUR123** [conjure-up/conjure-up#1397]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
juju version

which conjure-up
conjure-up --version

which lxc
/snap/bin/lxc config show
/snap/bin/lxc version

cat /etc/lsb-release
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

## Additional Information
                   ', ' - preparing image', ' - container started', '                                                                                                             ', ' - juju-74b65d-0 (arch=amd64)          ', 'Installing Juju agent on bootstrap instance', 'Fetching Juju GUI 2.12.1', 'Waiting for address', 'ERROR failed to bootstrap model: waited for 20m0s without getting any addresses']
2018-04-13 10:20:32,457 [DEBUG] conjure-up/openstack-novalxd - events.py:53 - Setting Error at conjureup/events.py:148
2018-04-13 10:20:32,458 [ERROR] conjure-up/openstack-novalxd - events.py:160 - Unhandled exception in <Task finished coro=<BaseBootstrapController.run() done, defined at /snap/conjure-up/987/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py:15> exception=BootstrapError('Unable to bootstrap (cloud type: localhost)',)>
Traceback (most recent call last):
  File "/snap/conjure-up/987/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py", line 21, in run
    await self.do_bootstrap()
  File "/snap/conjure-up/987/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py", line 65, in do_bootstrap
    app.provider.cloud_type))
conjureup.errors.BootstrapError: Unable to bootstrap (cloud type: localhost)
2018-04-13 10:20:32,470 [DEBUG] conjure-up/openstack-novalxd - __init__.py:29 - Showing dialog for exception: Unable to bootstrap (cloud type: localhost)
2018-04-13 10:36:14,480 [DEBUG] conjure-up/openstack-novalxd - events.py:53 - Setting Shutdown at /snap/conjure-up/987/usr/lib/python3.6/asyncio/events.py:127
2018-04-13 10:36:14,482 [DEBUG] conjure-up/openstack-novalxd - events.py:53 - Received Shutdown at conjureup/events.py:175
2018-04-13 10:36:14,483 [INFO] conjure-up/openstack-novalxd - events.py:179 - Shutting down
2018-04-13 10:36:14,483 [INFO] conjure-up/openstack-novalxd - app_config.py:227 - Storing conjure-up state
2018-04-13 10:36:14,487 [INFO] conjure-up/openstack-novalxd - app_config.py:236 - State saved
2018-04-13 10:36:14,488 [DEBUG] conjure-up/openstack-novalxd - events.py:199 - Cancelling pending task: <Task pending coro=<BootstrapController.wait() running at /snap/conjure-up/987/lib/python3.6/site-packages/conjureup/controllers/bootstrap/gui.py:43> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f5dcf47b0a8>()]>>

**Comment by MIRZAPUR123** [comment]
osp@BruCanOsp:~$ which juju
/snap/bin/juju
osp@BruCanOsp:~$ juju version
2.3.3-xenial-amd64
osp@BruCanOsp:~$ which conjure-up
/snap/bin/conjure-up
osp@BruCanOsp:~$ conjure-up --version
conjure-up 2.5.6
osp@BruCanOsp:~$
osp@BruCanOsp:~$
osp@BruCanOsp:~$
osp@BruCanOsp:~$
osp@BruCanOsp:~$ which lxc
/usr/bin/lxc
osp@BruCanOsp:~$ /snap/bin/lxc config show
config:
  core.https_address: '[::]'
osp@BruCanOsp:~$ /snap/bin/lxc version
Client version: 3.0.0
Server version: 3.0.0
osp@BruCanOsp:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
osp@BruCanOsp:~$

**Comment by battlemidget** [comment]
Did you setup networking and storage as outlined in the docs? https://docs.conjure-up.io/devel/en/#users-of-lxd
