### ISSUE TITLE
unable to install k8 with gpu support on mass

### ISSUE THREAD

**Issue by magick93** [conjure-up/conjure-up#1413]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [NO] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [NO] Is conjure-up running inside a virtual machine?
- [YES ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
/snap/bin/juju
juju version
2.3.5-artful-amd64

which conjure-up
/snap/bin/conjure-up
conjure-up --version
conjure-up 2.5.6


which lxc
/usr/bin/lxc

/snap/bin/lxc config show
config:
  core.https_address: '[::]:8443'
  core.trust_password: true

/snap/bin/lxc version
Client version: 3.0.0
Server version: 3.0.0


cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu 17.10"
```

The resulting output file can be attached to this issue.

## What Spell was Selected?
conjure-up kubernetes

## What provider (aws, maas, localhost, etc)?
mass

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

## Additional Information

**conjure-up.log**

```
2018-04-21 19:06:31,848 [DEBUG] conjure-up/_unspecified_spell - juju.py:34 - bin_path candidate found
2018-04-21 19:06:31,849 [DEBUG] conjure-up/_unspecified_spell - juju.py:34 - wait_path candidate found
2018-04-21 19:06:31,927 [DEBUG] conjure-up/_unspecified_spell - app.py:263 - Juju version: 2.3.3-artful-amd64, conjure-up version: 2.5.6
2018-04-21 19:06:31,963 [DEBUG] conjure-up/_unspecified_spell - telemetry.py:17 - Showing screen: Application Start
2018-04-21 19:06:31,968 [DEBUG] conjure-up/_unspecified_spell - telemetry.py:31 - OS: Linux-4.13.0-21-generic-x86_64-with-debian-stretch-sid 
2018-04-21 19:06:31,973 [INFO] conjure-up/_unspecified_spell - events.py:172 - Watching for shutdown
2018-04-21 19:06:32,014 [DEBUG] conjure-up/_unspecified_spell - events.py:53 - Awaiting Shutdown at conjureup/events.py:175
2018-04-21 19:06:32,021 [DEBUG] conjure-up/_unspecified_spell - telemetry.py:17 - Showing screen: Spell Selection
2018-04-21 19:06:34,021 [DEBUG] conjure-up/_unspecified_spell - telemetry.py:31 - Spell Choice: canonical-kubernetes-nvidia 
2018-04-21 19:06:34,047 [DEBUG] conjure-up/canonical-kubernetes-nvidia - download.py:60 - Path is local filesystem, copying /snap/conjure-up/987/spells/canonical-kubernetes-nvidia to /home/anton/.cache/conjure-up/canonical-kubernetes-nvidia
2018-04-21 19:06:35,019 [DEBUG] conjure-up/canonical-kubernetes-nvidia - step.py:27 - steps: [<StepModel Canonical Distribution of Kubernetes with nVidia GPU workers 00_process-providertype v: False c: []>, <StepModel Canonical Distribution of Kubernetes with nVidia GPU workers 01_select-network v: True c: []>, <StepModel Canonical Distribution of Kubernetes with nVidia GPU workers 02_get-kubectl v: True c: []>, <StepModel Canonical Distribution of Kubernetes with nVidia GPU workers 03_cluster-info v: True c: []>, <StepModel Canonical Distribution of Kubernetes with nVidia GPU workers 04_enable-cni v: False c: []>, <StepModel Canonical Distribution of Kubernetes with nVidia GPU workers 05_enable-nvidia v: True c: []>]
2018-04-21 19:06:36,185 [DEBUG] conjure-up/canonical-kubernetes-nvidia - utils.py:512 - Pulling bundle for ~containers/canonical-kubernetes-nvidia from channel: stable
2018-04-21 19:06:38,510 [DEBUG] conjure-up/canonical-kubernetes-nvidia - telemetry.py:17 - Showing screen: Add-on Selection
2018-04-21 19:06:46,066 [DEBUG] conjure-up/canonical-kubernetes-nvidia - telemetry.py:31 - Addon Selected: kubeflow 
2018-04-21 19:06:46,068 [DEBUG] conjure-up/canonical-kubernetes-nvidia - utils.py:512 - Pulling bundle for ~containers/canonical-kubernetes-nvidia from channel: stable
2018-04-21 19:06:49,104 [DEBUG] conjure-up/canonical-kubernetes-nvidia - gui.py:80 - Starting watcher for verifying LXD server is available.
2018-04-21 19:06:49,105 [DEBUG] conjure-up/canonical-kubernetes-nvidia - provider.py:373 - LXD environment set: binary /snap/bin/lxc lxd_dir /var/snap/lxd/common/lxd
2018-04-21 19:06:49,105 [DEBUG] conjure-up/canonical-kubernetes-nvidia - telemetry.py:17 - Showing screen: Choose a Cloud
2018-04-21 19:06:49,107 [DEBUG] conjure-up/canonical-kubernetes-nvidia - provider.py:373 - LXD environment set: binary /snap/bin/lxc lxd_dir /var/snap/lxd/common/lxd
2018-04-21 19:06:49,229 [DEBUG] conjure-up/canonical-kubernetes-nvidia - provider.py:387 - LXD query cmd: /snap/bin/lxc query --wait /1.0
2018-04-21 19:06:49,299 [DEBUG] conjure-up/canonical-kubernetes-nvidia - events.py:53 - Setting LXDAvailable at conjureup/controllers/clouds/gui.py:101
2018-04-21 19:06:57,809 [DEBUG] conjure-up/canonical-kubernetes-nvidia - telemetry.py:31 - Cloud selection: cloud-maas-f94 
2018-04-21 19:06:57,819 [DEBUG] conjure-up/canonical-kubernetes-nvidia - telemetry.py:17 - Showing screen: New Credential Creation
2018-04-21 19:07:23,365 [DEBUG] conjure-up/canonical-kubernetes-nvidia - juju.py:506 - {'clouds': {'cloud-maas-f94': {'type': 'maas', 'auth-types': ['oauth1'], 'endpoint': 'http://localhost/MAAS'}}}
2018-04-21 19:07:23,708 [DEBUG] conjure-up/canonical-kubernetes-nvidia - telemetry.py:17 - Showing screen: Configure Spell
2018-04-21 19:07:25,497 [INFO] conjure-up/canonical-kubernetes-nvidia - step.py:215 - Running Canonical Distribution of Kubernetes with nVidia GPU workers step: 01_select-network after-input.
2018-04-21 19:07:25,638 [WARNING] conjure-up/canonical-kubernetes-nvidia - step.py:251 - Env MAAS_ENDPOINT is None; replacing with empty string
2018-04-21 19:07:25,639 [WARNING] conjure-up/canonical-kubernetes-nvidia - step.py:251 - Env MAAS_APIKEY is None; replacing with empty string
2018-04-21 19:07:25,639 [DEBUG] conjure-up/canonical-kubernetes-nvidia - step.py:254 - Storing environment
2018-04-21 19:07:25,644 [DEBUG] conjure-up/canonical-kubernetes-nvidia - step.py:260 - Executing script: /home/anton/.cache/conjure-up/canonical-kubernetes-nvidia/steps/01_select-network/after-input
2018-04-21 19:07:34,071 [DEBUG] conjure-up/canonical-kubernetes-nvidia - telemetry.py:17 - Showing screen: Configure Applications
2018-04-21 19:07:34,331 [DEBUG] conjure-up/canonical-kubernetes-nvidia - maas.py:402 - Found endpoint: http://localhost/MAAS for cloud: cloud-maas-f94
2018-04-21 19:07:34,339 [DEBUG] conjure-up/canonical-kubernetes-nvidia - events.py:53 - Setting MAASConnected at conjureup/controllers/configapps/gui.py:49
2018-04-21 19:07:37,471 [DEBUG] conjure-up/canonical-kubernetes-nvidia - telemetry.py:17 - Showing screen: Configure Application
2018-04-21 19:07:38,656 [INFO] conjure-up/canonical-kubernetes-nvidia - applicationconfigure.py:87 - Hiding options not in the whitelist: ['channel', 'cuda_repo', 'default-backend-image', 'docker-ce-package', 'docker-logins', 'docker-opts', 'docker_runtime', 'enable-cgroups', 'http_proxy', 'https_proxy', 'ingress', 'kubelet-extra-args', 'labels', 'nagios_context', 'nagios_servicegroups', 'nginx-image', 'no_proxy', 'nvidia-container-runtime-package', 'nvidia-docker-package', 'proxy-extra-args', 'require-manual-upgrade', 'snap_proxy', 'snap_proxy_url']
2018-04-21 19:07:52,080 [DEBUG] conjure-up/canonical-kubernetes-nvidia - telemetry.py:17 - Showing screen: Configure Applications
2018-04-21 19:07:53,698 [DEBUG] conjure-up/canonical-kubernetes-nvidia - telemetry.py:17 - Showing screen: Bootstrapping Controller
2018-04-21 19:07:53,817 [INFO] conjure-up/canonical-kubernetes-nvidia - common.py:74 - Bootstrapping Juju controller...
2018-04-21 19:07:53,817 [DEBUG] conjure-up/canonical-kubernetes-nvidia - telemetry.py:31 - Juju Bootstrap: Started 
2018-04-21 19:07:53,818 [DEBUG] conjure-up/canonical-kubernetes-nvidia - juju.py:249 - bootstrap cmd: ['/snap/bin/juju', 'bootstrap', 'cloud-maas-f94', 'conjure-up-cloud-maas-f94-218', '--default-model', 'conjure-canonical-kubern-b27', '--config', 'image-stream=daily', '--bootstrap-series', 'xenial', '--credential', 'conjure-cloud-maas-f94-b85']
2018-04-21 19:07:53,821 [DEBUG] conjure-up/canonical-kubernetes-nvidia - events.py:53 - Awaiting Bootstrapped at conjureup/controllers/bootstrap/gui.py:43
2018-04-21 19:07:59,258 [ERROR] conjure-up/canonical-kubernetes-nvidia - common.py:60 - Error bootstrapping controller: ['Creating Juju controller "conjure-up-cloud-maas-f94-218" on cloud-maas-f94', 'Looking for packaged Juju agent version 2.3.3 for amd64', 'Launching controller instance(s) on cloud-maas-f94...', 'ERROR failed to bootstrap model: cannot start bootstrap instance in availability zone "default": failed to acquire node: No available machine matches constraints: [(\'agent_name\', [\'89cde007-425f-402a-87f7-e08dccf4f4cc\']), (\'mem\', [\'3584\']), (\'zone\', [\'default\'])] (resolved to "mem=3584.0 zone=default")']
2018-04-21 19:07:59,259 [DEBUG] conjure-up/canonical-kubernetes-nvidia - events.py:53 - Setting Error at conjureup/events.py:148
2018-04-21 19:07:59,260 [ERROR] conjure-up/canonical-kubernetes-nvidia - events.py:160 - Unhandled exception in <Task finished coro=<BaseBootstrapController.run() done, defined at /snap/conjure-up/987/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py:15> exception=BootstrapError('Unable to bootstrap (cloud type: maas)',)>
Traceback (most recent call last):
  File "/snap/conjure-up/987/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py", line 21, in run
    await self.do_bootstrap()
  File "/snap/conjure-up/987/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py", line 65, in do_bootstrap
    app.provider.cloud_type))
conjureup.errors.BootstrapError: Unable to bootstrap (cloud type: maas)
2018-04-21 19:07:59,274 [DEBUG] conjure-up/canonical-kubernetes-nvidia - __init__.py:29 - Showing dialog for exception: Unable to bootstrap (cloud type: maas)
```

**Comment by hyperbolic2346** [comment]
looks like MaaS wasn't able to provide a machine with the requirement of 3.5 gigs of memory in the zone default. Do you have machines available that meet those requirements in that zone?
