### ISSUE TITLE
conjure-up fails to enter openstack credentials

### ISSUE THREAD

**Issue by donbowman** [conjure-up/conjure-up#1419]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
NO
- [ ] Is conjure-up running inside a virtual machine?
NO
- [ x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?
YES

## Please provide the output of the following commands

```
which juju
juju version
$ conjure-up.juju --version                                                                                                                       
2.3.5-bionic-amd64                       

which conjure-up
conjure-up --version
$ conjure-up --version                                                                                                                            
conjure-up 2.5.6                 

which lxc
/snap/bin/lxc config show
$ lxc config show                                                                                                                                 
config: {}                      
/snap/bin/lxc version
$ lxc version                                                                                                                                     
Client version: 3.0.0                                                                                                                                                          
Server version: 3.0.0          

cat /etc/lsb-release
$ cat /etc/lsb-release                                                                                                                            
DISTRIB_ID=Ubuntu                                                                                                                                                              
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu Bionic Beaver (development branch)"
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1947230/conjure-up.tar.gz)

```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

## What Spell was Selected?
canonical kubernetes

## What provider (aws, maas, localhost, etc)?
openstack

### MAAS Users
Which version of MAAS?

N/A

## Commands ran

Please outline what commands were run to install and execute conjure-up:

snap install --edge --classic conjure-up
conjure-up [no arguments]
select openstack
select canonical kubernetes
select no options
enter credentials
crash

## Additional Information

```
2018-04-25 09:31:59,623 [DEBUG] conjure-up/_unspecified_spell - telemetry.py:17 - Showing screen: Spell Selection
2018-04-25 09:32:02,794 [DEBUG] conjure-up/_unspecified_spell - telemetry.py:31 - Spell Choice: canonical-kubernetes 
2018-04-25 09:32:02,868 [DEBUG] conjure-up/canonical-kubernetes - download.py:60 - Path is local filesystem, copying /snap/conjure-up/990/spells/canonical-kubernetes to /home/don/.cache/conjure-up/canonical-kubernetes
2018-04-25 09:32:03,868 [DEBUG] conjure-up/canonical-kubernetes - step.py:27 - steps: [<StepModel Canonical Distribution of Kubernetes 00_process-providertype v: False c: []>, <StepModel Canonical Distribution of Kubernetes 01_select-network v: True c: []>, <StepModel Canonical Distribution of Kubernetes 02_get-kubectl v: True c: []>, <StepModel Canonical Distribution of Kubernetes 03_cluster-info v: True c: []>, <StepModel Canonical Distribution of Kubernetes 04_enable-cni v: False c: []>]
2018-04-25 09:32:04,854 [DEBUG] conjure-up/canonical-kubernetes - utils.py:512 - Pulling bundle for canonical-kubernetes from channel: stable
2018-04-25 09:32:05,854 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:17 - Showing screen: Add-on Selection
2018-04-25 09:32:09,486 [DEBUG] conjure-up/canonical-kubernetes - gui.py:80 - Starting watcher for verifying LXD server is available.
2018-04-25 09:32:09,487 [DEBUG] conjure-up/canonical-kubernetes - provider.py:373 - LXD environment set: binary /snap/bin/lxc lxd_dir /var/snap/lxd/common/lxd
2018-04-25 09:32:09,488 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:17 - Showing screen: Choose a Cloud
2018-04-25 09:32:09,492 [DEBUG] conjure-up/canonical-kubernetes - provider.py:373 - LXD environment set: binary /snap/bin/lxc lxd_dir /var/snap/lxd/common/lxd
2018-04-25 09:32:09,579 [DEBUG] conjure-up/canonical-kubernetes - provider.py:387 - LXD query cmd: /snap/bin/lxc query --wait /1.0
2018-04-25 09:32:09,702 [DEBUG] conjure-up/canonical-kubernetes - events.py:53 - Setting LXDAvailable at conjureup/controllers/clouds/gui.py:101
2018-04-25 09:32:11,995 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:31 - Cloud selection: cloud-openstack-5ea 
2018-04-25 09:32:12,012 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:17 - Showing screen: New Credential Creation
2018-04-25 09:32:37,418 [DEBUG] conjure-up/canonical-kubernetes - events.py:53 - Setting Error at conjureup/events.py:148
2018-04-25 09:32:37,419 [ERROR] conjure-up/canonical-kubernetes - events.py:160 - Unhandled exception in <Task finished coro=<CredentialsController._save_credential() done, defined at /snap/conjure-up/990/lib/python3.6/site-packages/conjureup/controllers/credentials/gui.py:77> exception=NotImplementedError()>
Traceback (most recent call last):
  File "/snap/conjure-up/990/lib/python3.6/site-packages/conjureup/controllers/credentials/gui.py", line 110, in _save_credential
    juju.get_cloud(app.provider.cloud)
  File "/snap/conjure-up/990/lib/python3.6/site-packages/conjureup/juju.py", line 529, in get_cloud
    raise LookupError("Unable to locate cloud: {}".format(name))
LookupError: Unable to locate cloud: cloud-openstack-5ea
```

**Comment by dvenza** [comment]
Same problem, but my cloud is called "cloud-openstack-022.

In the credentials screen, conjure is asking for the the user name and password and the EC2 credentials. To access OpenStack one or the other should be sufficient, so why is that?
Are those really the EC2 credentials (access and secret key)? It is not documented anywhere I could find.

**Comment by amirdhaoui** [comment]
I am facing the same issue also, I can't find from where I can get the access and secret keys!

**Comment by battlemidget** [comment]
Selecting openstack for your cloud means you would've already deployed an openstack cloud. If that's not the case you'll want to do that first as that is where you retrieve your access/secret keys.

**Comment by battlemidget** [comment]
I see, I think it's supposed to be either or (not easily seen here), we should fix our provider to honor this.

**Comment by lachlancampbell** [comment]
Facing the same issue.

**Comment by ElanHasson** [comment]
` Unhandled exception in <Task finished coro=<CredentialsController._save_credential() done, defined at /snap/conjure-up/1015/lib/python3.6/site-packages/conjureup/controllers/juju/credentials/gui.py:77> exception=NotImplementedError()>
`

Is what I am getting. Appears to Not be Implemented.

**Comment by mwik** [comment]
I'm gettting the same error. Is it supposed to work or is conjure-up kubernetes not implemented for openstack yet?
