### ISSUE TITLE
"Failure in step 02_get-kubectl after-deploy"

### ISSUE THREAD

**Issue by bigjools** [conjure-up/conjure-up#1457]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [N] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [Y ] Is conjure-up running inside a virtual machine?
- [? ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
`/snap/bin/juju`
juju version
`2.3.7-xenial-amd64`

which conjure-up
`/snap/bin/conjure-up`
conjure-up --version
`conjure-up 2.5.6`

which lxc
`/snap/bin/lxc`
/snap/bin/lxc config show
`config:
  core.https_address: '[::]:8443'
  core.trust_password: true
`

/snap/bin/lxc version
`
Client version: 3.1
Server version: 3.1
`

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

## What Spell was Selected?
kubernetes

## What provider (aws, maas, localhost, etc)?
localhost

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:
Just "conjure-up" and select appropriate options.

## Additional Information
Here's the error in the log. Very hard to figure out from this where the script is failing.

```
2018-06-04 23:00:42,728 [DEBUG] conjure-up/kubernetes-core - step.py:265 - Executing script: /home/juledwar/.cache/conjure-up/kubernetes-core/steps/02_get-kubectl/after-deploy
2018-06-04 23:00:44,048 [DEBUG] conjure-up/kubernetes-core - events.py:53 - Setting Error at conjureup/events.py:149
2018-06-04 23:00:44,049 [ERROR] conjure-up/kubernetes-core - events.py:161 - Unhandled exception in <Task finished coro=<RunStepsController.run_steps() done, defined at /snap/conjure-up/999/lib/python3.6/site-packages/conjureup/controllers/runsteps/gui.py:14> exception=Exception('Failure in step 02_get-kubectl after-deploy',)>
Traceback (most recent call last):
  File "/snap/conjure-up/999/lib/python3.6/site-packages/conjureup/controllers/runsteps/gui.py", line 19, in run_steps
    step.result = await step.after_deploy(view.set_footer)
  File "/snap/conjure-up/999/lib/python3.6/site-packages/conjureup/models/step.py", line 137, in after_deploy
    return await self.run(PHASES.AFTER_DEPLOY, msg_cb)
  File "/snap/conjure-up/999/lib/python3.6/site-packages/conjureup/models/step.py", line 280, in run
    phase.value))
Exception: Failure in step 02_get-kubectl after-deploy
```

**Comment by bigjools** [comment]
I have no idea how to attach a file here for the requested files.

**Comment by battlemidget** [comment]
Hey @bigjools 

Mind trying with `sudo snap refresh conjure-up --edge`? We have several enhancements coming that provide you a much better k8s experience. Me and @johnsca can take a look at this issue in the meantime

**Comment by bigjools** [comment]
Yep I'll have a go at that in the next day or so - I hacked the kube config out for now and I'm still using the cluster. It would be interesting to see if you can recreate this.

As an aside I tried to run the after-deploy script manually and it failed because the python script that it calls was trying to import yaml, however the python3-yaml package was not installed. I did try again after installing that package but it still failed. Dunno if it's related but worth mentioning.

**Comment by daveamit** [comment]
@battlemidget 
I had this exact issue, I destroyed the cluster, did `sudo snap refresh conjure-up --edge` and was able to successfully re-create the kubernetes cluster.

**Comment by ik9999** [comment]
Have the similar issue with conjure-up 2.6.4 from edge

```
  2019-01-10 20:10:00,021 [DEBUG] conjure-up/canonical-kubernetes - step.py:268 - Executing script: /home/eq/.cache/conjure-up/canonical-kubernetes/steps/02_get-kubectl/after-deploy
  2019-01-10 20:10:06,725 [DEBUG] conjure-up/canonical-kubernetes - events.py:52 - Setting Error at conjureup/events.py:149
  2019-01-10 20:10:06,726 [ERROR] conjure-up/canonical-kubernetes - events.py:161 - Unhandled exception in <Task finished coro=<RunStepsController.run_steps() done, defined at /snap/conjure-up/1039/lib/python3.6/site-packages/conjureup/controllers/juju/runsteps/gui.py:14> exception=Exception('Failure in step 02_get-kubectl after-deploy',)>
  Traceback (most recent call last):
  File "/snap/conjure-up/1039/lib/python3.6/site-packages/conjureup/controllers/juju/runsteps/gui.py", line 19, in run_steps
  step.result = await step.after_deploy(view.set_footer)
  File "/snap/conjure-up/1039/lib/python3.6/site-packages/conjureup/models/step.py", line 137, in after_deploy
  return await self.run(PHASES.AFTER_DEPLOY, msg_cb)
  File "/snap/conjure-up/1039/lib/python3.6/site-packages/conjureup/models/step.py", line 283, in run
  phase.value))
  Exception: Failure in step 02_get-kubectl after-deploy
             2019-01-10 20:10:06,754 [DEBUG] conjure-up/canonical-kubernetes - __init__.py:27 - Showing dialog for exception: Failure in step 02_get-kubectl after-deploy
```

**Comment by captn3m0** [comment]
Same issue:

```
2019-02-06 01:40:53,146 [DEBUG] conjure-up/canonical-kubernetes - events.py:52 - Setting Error at conjureup/events.py:149
2019-02-06 01:40:53,146 [ERROR] conjure-up/canonical-kubernetes - events.py:161 - Unhandled exception in <Task finished coro=<RunStepsController.run_steps() done, defined at /snap/conjure-up/1040/lib/python3.6/site-packages/conjureup/controllers/juju/runsteps/gui.py:14> exception=Exception('Failure in step 02_get-kubectl after-deploy',)>
Traceback (most recent call last):
  File "/snap/conjure-up/1040/lib/python3.6/site-packages/conjureup/controllers/juju/runsteps/gui.py", line 19, in run_steps
    step.result = await step.after_deploy(view.set_footer)
  File "/snap/conjure-up/1040/lib/python3.6/site-packages/conjureup/models/step.py", line 137, in after_deploy
    return await self.run(PHASES.AFTER_DEPLOY, msg_cb)
  File "/snap/conjure-up/1040/lib/python3.6/site-packages/conjureup/models/step.py", line 283, in run
    phase.value))
Exception: Failure in step 02_get-kubectl after-deploy
2019-02-06 01:40:53,167 [DEBUG] conjure-up/canonical-kubernetes - __init__.py:27 - Showing dialog for exception: Failure in step 02_get-kubectl after-deploy
```
