### ISSUE TITLE
juju add-worker kubernetes-worker stuck on 'Waiting for kubelet to start'

### ISSUE THREAD

**Issue by publiccloudeng** [conjure-up/conjure-up#1462]
## juju add-worker kubernetes-worker stuck on 'Waiting for kubelet to start'

When trying to scale my kub cluster, the new units seems to go through the setup process fine. 
However, as soon as they get their ports assigned, its gets stuck on 'Waiting for kubelet to start.'
Need help please!

`unit-kubernetes-worker-3: 15:56:22 INFO unit.kubernetes-worker/3.juju-log Failed to apply label juju-application=kubernetes-worker. Will retry.`
`unit-kubernetes-worker-3: 15:56:23 DEBUG unit.kubernetes-worker/3.update-status Error from server (NotFound): nodes "ip-172-31-24-216.ec2.internal" not found`

Thanks

```
which juju
2.3.7-xenial-amd64

which conjure-up
conjure-up 2.5.6

## What provider (aws, maas, localhost, etc)?
aws

**Comment by battlemidget** [comment]
Hi,

Can you please grab `cdk-field-agent` and attach the output compressed file to this issue?

More information on cdk-field-agent can be found https://github.com/juju-solutions/cdk-field-agent

Thanks

**Comment by publiccloudeng** [comment]
It's not on localhost so I won't be able to send over any files on this platform. :(

**Comment by battlemidget** [comment]
We've got some new cloud integration work that's in our edge,beta,candidate channels if you want to tear down the current cluster and try with that? I am pushing this to stable today so having this feedback would be appreciated.

Thanks

**Comment by hyperbolic2346** [comment]
Just linking these two: https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/591

**Comment by kwmonroe** [comment]
Confirming the latest spell with AWS integration solves this.

```
$ conjure-up --version
conjure-up 2.5.6
$ git clone https://github.com/conjure-up/spells.git /tmp/myspells
$ conjure-up --nosync --spells-dir=/tmp/myspells
$ conjure-up canonical-kubernetes
-- stuff happens --
$ juju add-unit -n 2 kubernetes-worker
$ juju status
Model                         Controller  Cloud/Region   Version  SLA
conjure-canonical-kubern-5ef  aws-e       aws/us-east-1  2.3.7    unsupported

App                    Version  Status  Scale  Charm                  Store       Rev  OS      Notes
aws                             active      1  aws                    jujucharms    1  ubuntu
easyrsa                3.0.1    active      1  easyrsa                jujucharms   44  ubuntu
etcd                   3.2.9    active      3  etcd                   jujucharms   87  ubuntu
flannel                0.9.1    active      6  flannel                jujucharms   59  ubuntu
kubeapi-load-balancer  1.10.3   active      1  kubeapi-load-balancer  jujucharms   62  ubuntu  exposed
kubernetes-master      1.10.3   active      1  kubernetes-master      jujucharms  113  ubuntu
kubernetes-worker      1.10.3   active      5  kubernetes-worker      jujucharms  128  ubuntu  exposed

Unit                      Workload  Agent  Machine  Public address  Ports           Message
aws/0*                    active    idle   0        54.167.249.174                  ready
easyrsa/0*                active    idle   1        54.84.70.240                    Certificate Authority connected.
etcd/0*                   active    idle   2        52.90.251.255   2379/tcp        Healthy with 3 known peers
etcd/1                    active    idle   3        52.200.168.147  2379/tcp        Healthy with 3 known peers
etcd/2                    active    idle   4        34.227.47.71    2379/tcp        Healthy with 3 known peers
kubeapi-load-balancer/0*  active    idle   5        34.237.91.248   443/tcp         Loadbalancer ready.
kubernetes-master/0*      active    idle   6        35.171.186.92   6443/tcp        Kubernetes master running.
  flannel/0*              active    idle            35.171.186.92                   Flannel subnet 10.1.17.1/24
kubernetes-worker/0*      active    idle   7        34.201.47.125   80/tcp,443/tcp  Kubernetes worker running.
  flannel/1               active    idle            34.201.47.125                   Flannel subnet 10.1.15.1/24
kubernetes-worker/1       active    idle   8        54.210.61.44    80/tcp,443/tcp  Kubernetes worker running.
  flannel/2               active    idle            54.210.61.44                    Flannel subnet 10.1.3.1/24
kubernetes-worker/2       active    idle   9        52.204.1.210    80/tcp,443/tcp  Kubernetes worker running.
  flannel/3               active    idle            52.204.1.210                    Flannel subnet 10.1.86.1/24
kubernetes-worker/3       active    idle   10       34.239.149.255  80/tcp,443/tcp  Kubernetes worker running.
  flannel/5               active    idle            34.239.149.255                  Flannel subnet 10.1.24.1/24
kubernetes-worker/4       active    idle   11       34.204.87.62    80/tcp,443/tcp  Kubernetes worker running.
  flannel/4               active    idle            34.204.87.62                    Flannel subnet 10.1.28.1/24

Machine  State    DNS             Inst id              Series  AZ          Message
0        started  54.167.249.174  i-07724b9a5e05fb40a  xenial  us-east-1b  running
1        started  54.84.70.240    i-08ae15a431a5bc2ed  xenial  us-east-1c  running
2        started  52.90.251.255   i-0f67a508b587edd5f  xenial  us-east-1b  running
3        started  52.200.168.147  i-0011f9894a053b238  xenial  us-east-1d  running
4        started  34.227.47.71    i-0f44b03c78543334b  xenial  us-east-1c  running
5        started  34.237.91.248   i-0531829aa0c2a311e  xenial  us-east-1e  running
6        started  35.171.186.92   i-05844f0c22ec9fa77  xenial  us-east-1d  running
7        started  34.201.47.125   i-0806edf24b213608f  xenial  us-east-1a  running
8        started  54.210.61.44    i-00de73eba7621e44a  xenial  us-east-1b  running
9        started  52.204.1.210    i-02c4a16acdda2a9de  xenial  us-east-1c  running
10       started  34.239.149.255  i-0e50a45092eb3813a  xenial  us-east-1f  running
11       started  34.204.87.62    i-085f71e2a4f16cdca  xenial  us-east-1d  running
```

**Comment by battlemidget** [comment]
This has been released to stable now. @publiccloudeng Unfortunatelym youll need to tear down the cluster and re-deploy to make use of the new aws charm

**Comment by publiccloudeng** [comment]
I updated my conjure-up to `conjure-up 2.5.7-20180606.1806`
On a `conjure-up` now I am even unable to run the installer.
As soon as I select Kubernetes Core, I am led to this error:
`AttributeError: 'Localhost' object has no attribute 'lxd_bin'`
Don't even get the option to choose a cloud.

**Comment by publiccloudeng** [comment]
```
2018-06-08 09:59:02,037 [DEBUG] conjure-up/kubernetes-core - utils.py:512 - Pulling bundle for kubernetes-core from channel: stable
2018-06-08 09:59:03,534 [DEBUG] conjure-up/kubernetes-core - gui.py:78 - Starting watcher for verifying LXD server is available.
2018-06-08 09:59:03,535 [DEBUG] conjure-up/kubernetes-core - telemetry.py:17 - Showing screen: Choose a Cloud
2018-06-08 09:59:03,538 [DEBUG] conjure-up/kubernetes-core - provider.py:355 - LXD environment set: binary /usr/bin/lxc lxd_dir /var/lib/lxd
2018-06-08 09:59:03,651 [DEBUG] conjure-up/kubernetes-core - provider.py:371 - LXD query cmd: /usr/bin/lxc query --wait /1.0
2018-06-08 09:59:03,671 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Setting Error at conjureup/events.py:149
2018-06-08 09:59:03,674 [ERROR] conjure-up/kubernetes-core - events.py:161 - Unhandled exception in <Task finished coro=<CloudsController._monitor_localhost() done, defined at /snap/conjure-up/1006/lib/python3.6/site-packages/conjureup/controllers/clouds/gui.py:85> exception=AttributeError("'Localhost' object has no attribute 'lxd_bin'",)>
Traceback (most recent call last):
  File "/snap/conjure-up/1006/lib/python3.6/site-packages/conjureup/models/provider.py", line 373, in query
    return json.loads(out)
  File "/snap/conjure-up/1006/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/snap/conjure-up/1006/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/snap/conjure-up/1006/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/conjure-up/1006/lib/python3.6/site-packages/conjureup/controllers/clouds/gui.py", line 94, in _monitor_localhost
    server_compatible = await provider.is_server_compatible()
  File "/snap/conjure-up/1006/lib/python3.6/site-packages/conjureup/models/provider.py", line 418, in is_server_compatible
    out = await self.query()
  File "/snap/conjure-up/1006/lib/python3.6/site-packages/conjureup/models/provider.py", line 375, in query
    raise errors.LXDParseError(self.lxd_bin)
AttributeError: 'Localhost' object has no attribute 'lxd_bin'
2018-06-08 09:59:03,684 [DEBUG] conjure-up/kubernetes-core - __init__.py:29 - Showing dialog for exception: 'Localhost' object has no attribute 'lxd_bin'
2018-06-08 09:59:16,725 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Setting Shutdown at conjureup/events.py:145
2018-06-08 09:59:16,726 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Received Shutdown at conjureup/events.py:176
2018-06-08 09:59:16,726 [INFO] conjure-up/kubernetes-core - events.py:180 - Shutting down

**Comment by battlemidget** [comment]
Thanks I'll get this addressed now

**Comment by publiccloudeng** [comment]
Hi,
I am able to complete the kubernetes deploy with a workaround.
However, when I try an app and expose it externally via a service resource, the service never spins up and is stuck on pending.
Would anyone know what the issue is in this case?

URGENT:
Further, is there a way for me to use an older version of conjure-up? I need a solution to this asap if possible.
Thanks
