### ISSUE TITLE
Failing to conjure-up kubernetes [Errno 113] Connect call failed ('x.x.x.x', 17070)

### ISSUE THREAD

**Issue by SDAdham** [conjure-up/conjure-up#1476]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems No
- [ ] Is conjure-up running inside a virtual machine? No
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`? Yes

## Please provide the output of the following commands

```
which juju
/snap/bin/juju

juju version
2.3.8-xenial-amd64

which conjure-up
/snap/bin/conjure-up

conjure-up --version
conjure-up 2.5.8

which lxc
/usr/bin/lxc

/snap/bin/lxc config show
config: {}

/snap/bin/lxc version
Client version: 3.1
Server version: 3.1

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up

[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2129670/conjure-up.tar.gz) after trying to remove any traces for kubernetes i.e in .kube
[conjure-up-backup.tar.gz](https://github.com/conjure-up/conjure-up/files/2129671/conjure-up-backup.tar.gz)

```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
sosreport (version 3.5)

no valid plugins were enabled
```

The resulting output file can be attached to this issue.

## What Spell was Selected?
kubernetes

## What provider (aws, maas, localhost, etc)?
localhost maas

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

## Additional Information

I have installed The Canonical Distribution of Kubernetes using conjure-up, came across an issue here https://stackoverflow.com/questions/50970133/installed-kubernetes-on-ubuntu-and-i-see-a-lot-of-nodes-are-getting-created-in-m so I deleted the VMs manually, since then kubernetes does not start.

conjure-down kubernetes and conjure-up kubernetes do not work

**Comment by SDAdham** [comment]
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2145811/conjure-up.tar.gz)
[Uploading conjure-up-backup.tar.gz…]()

**Comment by FaeezBorman** [comment]
I am having the same issue on my setup

Is there a work-around for this

**Comment by LeviSchuck** [comment]
Also encountered issue, removed and reinstalled lxd too, no luck

**Comment by jbalasko** [comment]
I have same issue after removing conjure-up, all lxc containers and re-installing conjure-up

which juju
/snap/bin/juju

juju version
2.5.0-bionic-amd64

conjure-up --version
conjure-up 2.6.6

**Comment by dosoos** [comment]
i have same issue

`
~# juju version
2.5.0-bionic-amd64
`

`
~$ conjure-up --version
conjure-up 2.6.6
`

`
~# uname -a
Linux home-server 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by dosoos** [comment]
detail for this


2019-04-10 15:56:45,839 [DEBUG] conjure-up/openstack-novalxd - gui.py:78 - Starting watcher for verifying LXD server is available.
2019-04-10 15:56:45,840 [DEBUG] conjure-up/openstack-novalxd - telemetry.py:17 - Showing screen: Choose a Cloud
2019-04-10 15:56:45,845 [DEBUG] conjure-up/openstack-novalxd - provider.py:355 - LXD environment set: binary /snap/bin/lxc lxd_dir /var/snap/lxd/common/lxd
2019-04-10 15:56:45,938 [DEBUG] conjure-up/openstack-novalxd - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0
2019-04-10 15:56:46,038 [DEBUG] conjure-up/openstack-novalxd - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/networks
2019-04-10 15:56:46,158 [DEBUG] conjure-up/openstack-novalxd - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/networks/lxdbr0
2019-04-10 15:56:46,281 [DEBUG] conjure-up/openstack-novalxd - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/networks/lo
2019-04-10 15:56:46,385 [DEBUG] conjure-up/openstack-novalxd - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/networks/eno1
2019-04-10 15:56:46,494 [DEBUG] conjure-up/openstack-novalxd - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/networks/tun0
2019-04-10 15:56:46,598 [DEBUG] conjure-up/openstack-novalxd - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/storage-pools
2019-04-10 15:56:46,718 [DEBUG] conjure-up/openstack-novalxd - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/storage-pools/default
2019-04-10 15:56:46,853 [DEBUG] conjure-up/openstack-novalxd - events.py:52 - Setting LXDAvailable at conjureup/controllers/juju/clouds/gui.py:104
2019-04-10 15:56:47,349 [DEBUG] conjure-up/openstack-novalxd - provider.py:355 - LXD environment set: binary /snap/bin/lxc lxd_dir /var/snap/lxd/common/lxd
2019-04-10 15:56:47,734 [DEBUG] conjure-up/openstack-novalxd - telemetry.py:32 - Cloud selection: localhost
2019-04-10 15:56:47,764 [DEBUG] conjure-up/openstack-novalxd - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/networks
2019-04-10 15:56:47,865 [DEBUG] conjure-up/openstack-novalxd - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/networks/lxdbr0
2019-04-10 15:56:47,978 [DEBUG] conjure-up/openstack-novalxd - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/networks/lo
2019-04-10 15:56:48,082 [DEBUG] conjure-up/openstack-novalxd - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/networks/eno1
2019-04-10 15:56:48,202 [DEBUG] conjure-up/openstack-novalxd - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/networks/tun0
2019-04-10 15:56:48,321 [DEBUG] conjure-up/openstack-novalxd - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/storage-pools
2019-04-10 15:56:48,434 [DEBUG] conjure-up/openstack-novalxd - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/storage-pools/default
2019-04-10 15:56:48,559 [DEBUG] conjure-up/openstack-novalxd - telemetry.py:17 - Showing screen: LXD Configuration
2019-04-10 15:56:51,168 [DEBUG] conjure-up/openstack-novalxd - telemetry.py:17 - Showing screen: Choose a Controller
2019-04-10 15:56:51,294 [DEBUG] conjure-up/openstack-novalxd - utils.py:665 - Parsing 4: lxdbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 66:6e:98:1c:23:8c brd ff:ff:ff:ff:ff:ff
    inet 10.17.219.1/24 scope global lxdbr0
       valid_lft forever preferred_lft forever
    inet6 fe80::646e:98ff:fe1c:238c/64 scope link
       valid_lft forever preferred_lft forever
 for IPv4 address
2019-04-10 15:56:51,307 [DEBUG] conjure-up/openstack-novalxd - gui.py:69 - LXD Info set: (name: lxdbr0) (network: 10.17.219.0/24) (gateway: 10.17.219.1) (dhcp-range-start: 10.17.219.2) (dhcp-range-stop: 10.17.219.254)
2019-04-10 15:56:52,089 [DEBUG] conjure-up/openstack-novalxd - telemetry.py:17 - Showing screen: Configure Spell
2019-04-10 15:56:53,207 [DEBUG] conjure-up/openstack-novalxd - telemetry.py:17 - Showing screen: Configure Applications
2019-04-10 15:56:58,768 [DEBUG] conjure-up/openstack-novalxd - telemetry.py:17 - Showing screen: Creating Model
2019-04-10 15:56:58,917 [DEBUG] conjure-up/openstack-novalxd - events.py:52 - Awaiting Bootstrapped at conjureup/controllers/juju/bootstrap/gui.py:43
2019-04-10 15:57:02,003 [DEBUG] conjure-up/openstack-novalxd - events.py:52 - Setting Error at conjureup/events.py:149
2019-04-10 15:57:02,008 [ERROR] conjure-up/openstack-novalxd - events.py:161 - Unhandled exception in <Task finished coro=<BaseBootstrapController.run() done, defined at /snap/conjure-up/1045/lib/python3.6/site-packages/conjureup/controllers/juju/bootstrap/common.py:15> exception=OSError(113, "Connect call failed ('10.17.219.19', 17070)")>
Traceback (most recent call last):
  File "/snap/conjure-up/1045/lib/python3.6/site-packages/conjureup/controllers/juju/bootstrap/common.py", line 19, in run
    await self.do_add_model()
  File "/snap/conjure-up/1045/lib/python3.6/site-packages/conjureup/controllers/juju/bootstrap/common.py", line 24, in do_add_model
    if await juju.model_available():
  File "/snap/conjure-up/1045/lib/python3.6/site-packages/conjureup/juju.py", line 154, in model_available
    await controller.connect(app.provider.controller)
  File "/snap/conjure-up/1045/lib/python3.6/site-packages/juju/controller.py", line 101, in connect
    await self._connector.connect_controller(controller_name, **kwargs)
  File "/snap/conjure-up/1045/lib/python3.6/site-packages/juju/client/connector.py", line 99, in connect_controller
    bakery_client=self.bakery_client_for_controller(controller_name),
  File "/snap/conjure-up/1045/lib/python3.6/site-packages/juju/client/connector.py", line 68, in connect
    self._connection = await Connection.connect(**kwargs)
  File "/snap/conjure-up/1045/lib/python3.6/site-packages/juju/client/connection.py", line 178, in connect
    await self._connect_with_redirect([(endpoint, cacert)])
  File "/snap/conjure-up/1045/lib/python3.6/site-packages/juju/client/connection.py", line 535, in _connect_with_redirect
    login_result = await self._connect_with_login(endpoints)
  File "/snap/conjure-up/1045/lib/python3.6/site-packages/juju/client/connection.py", line 502, in _connect_with_login
    await self._connect(endpoints)
  File "/snap/conjure-up/1045/lib/python3.6/site-packages/juju/client/connection.py", line 462, in _connect
    result = await task
  File "/snap/conjure-up/1045/usr/lib/python3.6/asyncio/tasks.py", line 458, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/snap/conjure-up/1045/lib/python3.6/site-packages/juju/client/connection.py", line 451, in _try_endpoint
    return await self._open(endpoint, cacert)
  File "/snap/conjure-up/1045/lib/python3.6/site-packages/juju/client/connection.py", line 205, in _open
    max_size=self.max_frame_size,
  File "/snap/conjure-up/1045/lib/python3.6/site-packages/websockets/py35/client.py", line 12, in __await_impl__
    transport, protocol = await self._creating_connection
  File "/snap/conjure-up/1045/usr/lib/python3.6/asyncio/base_events.py", line 778, in create_connection
    raise exceptions[0]
  File "/snap/conjure-up/1045/usr/lib/python3.6/asyncio/base_events.py", line 765, in create_connection
    yield from self.sock_connect(sock, address)
  File "/snap/conjure-up/1045/usr/lib/python3.6/asyncio/selector_events.py", line 450, in sock_connect
    return (yield from fut)
  File "/snap/conjure-up/1045/usr/lib/python3.6/asyncio/selector_events.py", line 480, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
OSError: [Errno 113] Connect call failed ('10.17.219.19', 17070)
2019-04-10 15:57:02,028 [DEBUG] conjure-up/openstack-novalxd - __init__.py:27 - Showing dialog for exception: [Errno 113] Connect call failed ('10.17.219.19', 17070)

**Comment by dosoos** [comment]
oh, maybe not have juju controller, you can run this code
`juju status`

and run
`juju bootstrap`

choice create a location controller, so successed
