### ISSUE TITLE
 list index out of range

### ISSUE THREAD

**Issue by OceanChen2012** [conjure-up/conjure-up#1510]
2018-09-10 14:19:10,698 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:32 - Cloud selection: localhost 
2018-09-10 14:19:10,714 [DEBUG] conjure-up/canonical-kubernetes - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/networks
2018-09-10 14:19:10,857 [DEBUG] conjure-up/canonical-kubernetes - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/networks/lxdbr0
2018-09-10 14:19:10,998 [DEBUG] conjure-up/canonical-kubernetes - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/networks/lo
2018-09-10 14:19:11,142 [DEBUG] conjure-up/canonical-kubernetes - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/networks/eth0
2018-09-10 14:19:11,286 [DEBUG] conjure-up/canonical-kubernetes - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/networks/eth1
2018-09-10 14:19:11,442 [DEBUG] conjure-up/canonical-kubernetes - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/networks/eth2
2018-09-10 14:19:11,578 [DEBUG] conjure-up/canonical-kubernetes - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/networks/eth3
2018-09-10 14:19:11,738 [DEBUG] conjure-up/canonical-kubernetes - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/networks/eth4
2018-09-10 14:19:11,881 [DEBUG] conjure-up/canonical-kubernetes - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/networks/eth5
2018-09-10 14:19:12,026 [DEBUG] conjure-up/canonical-kubernetes - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/storage-pools
2018-09-10 14:19:12,165 [DEBUG] conjure-up/canonical-kubernetes - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/storage-pools/default
2018-09-10 14:19:12,307 [DEBUG] conjure-up/canonical-kubernetes - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/storage-pools/juju-btrfs
2018-09-10 14:19:12,471 [DEBUG] conjure-up/canonical-kubernetes - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/storage-pools/juju-zfs
2018-09-10 14:19:12,622 [DEBUG] conjure-up/canonical-kubernetes - provider.py:372 - LXD query cmd: /snap/bin/lxc query --wait /1.0/storage-pools/local
2018-09-10 14:19:12,760 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:17 - Showing screen: LXD Configuration
2018-09-10 14:19:31,236 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:17 - Showing screen: Choose a Controller
2018-09-10 14:19:31,511 [DEBUG] conjure-up/canonical-kubernetes - utils.py:665 - Parsing 11: lxdbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether fe:ef:a8:14:b8:aa brd ff:ff:ff:ff:ff:ff
    inet 10.91.29.1/24 scope global lxdbr0
       valid_lft forever preferred_lft forever
    inet6 fe80::cce9:94ff:fe0f:9af3/64 scope link 
       valid_lft forever preferred_lft forever
 for IPv4 address
2018-09-10 14:19:31,519 [DEBUG] conjure-up/canonical-kubernetes - gui.py:69 - LXD Info set: (name: lxdbr0) (network: 10.91.29.0/24) (gateway: 10.91.29.1) (dhcp-range-start: 10.91.29.2) (dhcp-range-stop: 10.91.29.254)
2018-09-10 14:19:48,223 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:17 - Showing screen: Configure Spell
2018-09-10 14:19:51,510 [INFO] conjure-up/canonical-kubernetes - step.py:220 - Running Canonical Distribution of Kubernetes step: 01_select-network after-input.
2018-09-10 14:19:51,728 [DEBUG] conjure-up/canonical-kubernetes - step.py:262 - Storing environment
2018-09-10 14:19:51,748 [DEBUG] conjure-up/canonical-kubernetes - step.py:268 - Executing script: /home/halo_op/.cache/conjure-up/canonical-kubernetes/steps/01_select-network/after-input
2018-09-10 14:19:59,182 [INFO] conjure-up/canonical-kubernetes - step.py:220 - Running Canonical Distribution of Kubernetes step: 04_enable-cni before-config.
2018-09-10 14:19:59,378 [DEBUG] conjure-up/canonical-kubernetes - step.py:262 - Storing environment
2018-09-10 14:19:59,398 [DEBUG] conjure-up/canonical-kubernetes - step.py:268 - Executing script: /home/halo_op/.cache/conjure-up/canonical-kubernetes/steps/04_enable-cni/before-config
2018-09-10 14:19:59,437 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:17 - Showing screen: Configure Applications
2018-09-10 14:20:07,222 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:17 - Showing screen: Creating Model
2018-09-10 14:20:07,341 [DEBUG] conjure-up/canonical-kubernetes - events.py:52 - Setting Error at conjureup/events.py:149
2018-09-10 14:20:07,342 [ERROR] conjure-up/canonical-kubernetes - events.py:161 - Unhandled exception in <Task finished coro=<BaseBootstrapController.run() done, defined at /snap/conjure-up/1015/lib/python3.6/site-packages/conjureup/controllers/juju/bootstrap/common.py:15> exception=IndexError('list index out of range',)>
Traceback (most recent call last):
  File "/snap/conjure-up/1015/lib/python3.6/site-packages/conjureup/controllers/juju/bootstrap/common.py", line 19, in run
    await self.do_add_model()
  File "/snap/conjure-up/1015/lib/python3.6/site-packages/conjureup/controllers/juju/bootstrap/common.py", line 24, in do_add_model
    if await juju.model_available():
  File "/snap/conjure-up/1015/lib/python3.6/site-packages/conjureup/juju.py", line 154, in model_available
    await controller.connect(app.provider.controller)
  File "/snap/conjure-up/1015/lib/python3.6/site-packages/juju/controller.py", line 100, in connect
    await self._connector.connect_controller(controller_name, **kwargs)
  File "/snap/conjure-up/1015/lib/python3.6/site-packages/juju/client/connector.py", line 90, in connect_controller
    endpoint = controller['api-endpoints'][0]
IndexError: list index out of range
2018-09-10 14:20:07,360 [DEBUG] conjure-up/canonical-kubernetes - __init__.py:27 - Showing dialog for exception: list index out of range
2018-09-10 14:20:07,371 [DEBUG] conjure-up/canonical-kubernetes - events.py:52 - Awaiting Bootstrapped at conjureup/controllers/juju/bootstrap/gui.py:43
2018-09-10 14:25:32,413 [DEBUG] conjure-up/canonical-kubernetes - events.py:52 - Setting Shutdown at conjureup/ui/views/shutdown.py:36
2018-09-10 14:25:32,416 [DEBUG] conjure-up/canonical-kubernetes - events.py:52 - Received Shutdown at conjureup/events.py:176
2018-09-10 14:25:32,416 [INFO] conjure-up/canonical-kubernetes - events.py:180 - Shutting down
2018-09-10 14:25:32,416 [INFO] conjure-up/canonical-kubernetes - app_config.py:192 - Storing conjure-up state
2018-09-10 14:25:32,419 [INFO] conjure-up/canonical-kubernetes - app_config.py:207 - State saved
2018-09-10 14:25:32,420 [DEBUG] conjure-up/canonical-kubernetes - events.py:200 - Cancelling pending task: <Task pending coro=<BootstrapController.wait() running at /snap/conjure-up/1015/lib/python3.6/site-packages/conjureup/controllers/juju/bootstrap/gui.py:43> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f5354983c48>()]>>

**Comment by OceanChen2012** [comment]
halo_op@dp-hpjh-dn-378:~$ which juju
/snap/bin/juju
halo_op@dp-hpjh-dn-378:~$ juju version
2.4.0-xenial-amd64
halo_op@dp-hpjh-dn-378:~$ which conjure-up
/snap/bin/conjure-up
halo_op@dp-hpjh-dn-378:~$ conjure-up --version
conjure-up 2.6.0
halo_op@dp-hpjh-dn-378:~$ which lxc
/snap/bin/lxc
halo_op@dp-hpjh-dn-378:~$ /snap/bin/lxc config show
config:
  core.https_address: '[::]'
halo_op@dp-hpjh-dn-378:~$ /snap/bin/lxc version
Client version: 3.4
Server version: 3.4
halo_op@dp-hpjh-dn-378:~$ /snap/bin/lxc version
Client version: 3.4
Server version: 3.4
halo_op@dp-hpjh-dn-378:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
halo_op@dp-hpjh-dn-378:~$

**Comment by OceanChen2012** [comment]
halo_op@dp-hpjh-dn-378:$ which juju
/snap/bin/juju
halo_op@dp-hpjh-dn-378:$ juju version
2.4.0-xenial-amd64
halo_op@dp-hpjh-dn-378:$ which conjure-up
/snap/bin/conjure-up
halo_op@dp-hpjh-dn-378:$ conjure-up --version
conjure-up 2.6.0
halo_op@dp-hpjh-dn-378:$ which lxc
/snap/bin/lxc
halo_op@dp-hpjh-dn-378:$ /snap/bin/lxc config show
config:
core.https_address: '[::]'
halo_op@dp-hpjh-dn-378:$ /snap/bin/lxc version
Client version: 3.4
Server version: 3.4
halo_op@dp-hpjh-dn-378:$ /snap/bin/lxc version
Client version: 3.4
Server version: 3.4
halo_op@dp-hpjh-dn-378:$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
halo_op@dp-hpjh-dn-378:$****
