### ISSUE TITLE
Cannot bootstrap juju controller

### ISSUE THREAD

**Issue by sreeve29** [conjure-up/conjure-up#1513]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems

I didn't see it there.

- [ ] Is conjure-up running inside a virtual machine?

Yes

- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

Still happens after that command is run.

## Please provide the output of the following commands

```
which juju
juju version

which conjure-up
conjure-up --version

which lxc
/snap/bin/lxc config show
/snap/bin/lxc version

cat /etc/lsb-release


sreeve@conjureup1:~$ juju --version
2.4.0-xenial-amd64
sreeve@conjureup1:~$ which juju
/snap/bin/juju
sreeve@conjureup1:~$ which conjure-up
/snap/bin/conjure-up
sreeve@conjureup1:~$ conjure-up --version
conjure-up 2.6.0
sreeve@conjureup1:~$ which lxc
/snap/bin/lxc
sreeve@conjureup1:~$ lxc --version
3.5
sreeve@conjureup1:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
[conjureLog.txt](https://github.com/conjure-up/conjure-up/files/2405746/conjureLog.txt)


sreeve@conjureup1:~$ /snap/bin/lxc config show
config:
  core.https_address: '[::]'
sreeve@conjureup1:~$ /snap/bin/lxc version
Client version: 3.5
Server version: 3.5
sreeve@conjureup1:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"





```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

Not sure what to make of this:

sreeve@conjureup1:~$ sosreport
sosreport (version 3.5)
no valid plugins were enabled
sreeve@conjureup1:~

The resulting output file can be attached to this issue.

## What Spell was Selected?

"OpenStack with NovaLXD"

## What provider (aws, maas, localhost, etc)?

localhost

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

conjure-up

## Additional Information

This is the first occurrence of an error in the log file:

2018-09-20 10:05:21,827 [DEBUG] conjure-up/openstack-novalxd - events.py:52 - Awaiting Bootstrapped at conjureup/controllers/juju/bootstrap/gui.py:43
2018-09-20 10:32:29,948 [ERROR] conjure-up/openstack-novalxd - common.py:60 - Error bootstrapping controller: ['Creating Juju controller "conjure-up-localhost-4c3" on localhost/localhost', 'Looking for packaged Juju agent version 2.4.0 for amd64', 'To configure your system to better support LXD containers, please see: https://github.com/lxc/lxd/blob/master/doc/production-setup.md', 'Launching controller instance(s) on localhost/localhost...', ' - acquiring LXD image', '

**Comment by sreeve29** [comment]
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2405785/conjure-up.tar.gz)
[conjureLog.txt](https://github.com/conjure-up/conjure-up/files/2405787/conjureLog.txt)

**Comment by sreeve29** [comment]
No proxy servers are involved at all.
This is a fresh/clean install of Ubuntu Server 16, installed lxd 3.0, installed conjure-up.
Already ran lxd init, etc.  
The Ubuntu Server is a VM with 16GB RAM and 100GB hard drive in a VirtualBox environment.

**Comment by battlemidget** [comment]
```
ERROR failed to bootstrap model: waited for 20m0s without being able to connect: ssh: connect to host 192.168.1.128 port 22: No route to host
```

Is LXD listening on this network? `lxd init --auto` usually defines a lxdbr0 with a 10.x.x.x

**Comment by sreeve29** [comment]
Thank you that certainly seemed to help.  I somehow got into a GUI version of lxd init and it started prompting me for a 10.x for lxdbr0. 

Then lxdbr0 seemed to look like that:

3: lxdbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether fe:a7:b7:50:cf:fa brd ff:ff:ff:ff:ff:ff
    inet 10.108.21.1/24 scope global lxdbr0

But now I get this error:

2018-09-21 11:44:19,295 [INFO] conjure-up/openstack-novalxd - common.py:47 - Waiting for deployment to settle.
2018-09-21 12:03:08,145 [DEBUG] conjure-up/openstack-novalxd - events.py:52 - Setting Error at conjureup/events.py:149
**2018-09-21 12:03:08,145 [ERROR] conjure-up/openstack-novalxd - events.py:161 - Unhandled exception
Traceback (most recent call last):
  File "/snap/conjure-up/1015/usr/lib/python3.6/asyncio/selector_events.py", line 727, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out**
2018-09-21 12:03:08,167 [DEBUG] conjure-up/openstack-novalxd - __init__.py:27 - Showing dialog for exception: [Errno 110] Connection timed out
2018-09-21 12:03:08,168 [ERROR] conjure-up/openstack-novalxd - websockets.protocol: protocol.py:565 - Error in data transfer
Traceback (most recent call last):
  File "/snap/conjure-up/1015/lib/python3.6/site-packages/websockets/protocol.py", line 528, in transfer_data
    msg = yield from self.read_message()
  File "/snap/conjure-up/1015/lib/python3.6/site-packages/websockets/protocol.py", line 580, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/snap/conjure-up/1015/lib/python3.6/site-packages/websockets/protocol.py", line 645, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/snap/conjure-up/1015/lib/python3.6/site-packages/websockets/protocol.py", line 710, in read_frame
    extensions=self.extensions,
  File "/snap/conjure-up/1015/lib/python3.6/site-packages/websockets/framing.py", line 100, in read
    data = yield from reader(2)
  File "/snap/conjure-up/1015/usr/lib/python3.6/asyncio/streams.py", line 674, in readexactly
    yield from self._wait_for_data('readexactly')
  File "/snap/conjure-up/1015/usr/lib/python3.6/asyncio/streams.py", line 464, in _wait_for_data
    yield from self._waiter
  File "/snap/conjure-up/1015/usr/lib/python3.6/asyncio/selector_events.py", line 727, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
2018-09-21 12:03:08,171 [WARNING] conjure-up/openstack-novalxd - juju.client.connection: connection.py:227 - Receiver: Connection closed, reconnecting
2018-09-21 12:04:02,954 [ERROR] conjure-up/openstack-novalxd - juju.py:745 - DEBUG:root:neutron-api/0 juju agent status is allocating since 2018-09-21 15:43:11Z
DEBUG:root:neutron-gateway/0 juju agent status is allocating since 2018-09-21 15:43:15Z
DEBUG:root:nova-cloud-controller/0 juju agent status is allocating since 2018-09-21 15:43:17Z
DEBUG:root:nova-compute/0 juju agent status is allocating since 2018-09-21 15:43:19Z
DEBUG:root:openstack-dashboard/0 juju agent status is allocating since 2018-09-21 15:43:39Z
DEBUG:root:rabbitmq-server/0 juju agent status is allocating since 2018-09-21 15:43:46Z
ERROR:root:ERROR health ping timed out after 30s
ERROR codec.ReadHeader error: error receiving message: read tcp 10.108.21.1:38098->10.108.21.83:17070: read: connection timed out

ERROR:root:juju status --format=json failed: 1


and now lxdbr0 looks like this:


3: lxdbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether fe:04:5f:91:0d:76 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.222/24 scope global lxdbr0
       valid_lft forever preferred_lft forever

**Comment by dosoos** [comment]
i have this question but i don't know how to fixed it, why close this issue?

**Comment by dosoos** [comment]
set ip6 is none fixed thsi issue
