### ISSUE TITLE
 Unable to bootstrap (cloud type: maas)

### ISSUE THREAD

**Issue by gdumo22** [conjure-up/conjure-up#1532]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [No] Is conjure-up running inside a virtual machine?
- [No] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju: **/snap/bin/juju**
juju version: **2.4.3-bionic-amd64**

which conjure-up: /snap/bin/conjure-up
conjure-up --version: conjure-up 2.6.1

which lxc: /usr/bin/lxc
/snap/bin/lxc config show
/snap/bin/lxc version

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"

```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
/home/naab113maas/.cache/conjure-up/
/home/naab113maas/.cache/conjure-up/.state.db
/home/naab113maas/.cache/conjure-up/openstack-base/
/home/naab113maas/.cache/conjure-up/openstack-base/metadata.yaml
/home/naab113maas/.cache/conjure-up/openstack-base/conjure-up-cloud-maas-b89-94b-bootstrap.out
/home/naab113maas/.cache/conjure-up/openstack-base/steps/
/home/naab113maas/.cache/conjure-up/openstack-base/steps/novarc
/home/naab113maas/.cache/conjure-up/openstack-base/steps/01_glance/
/home/naab113maas/.cache/conjure-up/openstack-base/steps/01_glance/after-deploy
/home/naab113maas/.cache/conjure-up/openstack-base/steps/01_glance/metadata.yaml
/home/naab113maas/.cache/conjure-up/openstack-base/steps/01_glance/glance.sh
/home/naab113maas/.cache/conjure-up/openstack-base/steps/04_horizon/
/home/naab113maas/.cache/conjure-up/openstack-base/steps/04_horizon/after-deploy
/home/naab113maas/.cache/conjure-up/openstack-base/steps/04_horizon/metadata.yaml
/home/naab113maas/.cache/conjure-up/openstack-base/steps/02_keypair/
/home/naab113maas/.cache/conjure-up/openstack-base/steps/02_keypair/after-deploy
/home/naab113maas/.cache/conjure-up/openstack-base/steps/02_keypair/metadata.yaml
/home/naab113maas/.cache/conjure-up/openstack-base/steps/02_keypair/keypair.sh
/home/naab113maas/.cache/conjure-up/openstack-base/steps/03_neutron/
/home/naab113maas/.cache/conjure-up/openstack-base/steps/03_neutron/after-deploy
/home/naab113maas/.cache/conjure-up/openstack-base/steps/03_neutron/metadata.yaml
/home/naab113maas/.cache/conjure-up/openstack-base/steps/03_neutron/neutron.sh
/home/naab113maas/.cache/conjure-up/openstack-base/tests/
/home/naab113maas/.cache/conjure-up/openstack-base/tests/verify
/home/naab113maas/.cache/conjure-up/openstack-base/conjure-up-cloud-maas-b89-94b-bootstrap.err
/home/naab113maas/.cache/conjure-up/conjure-up.log

```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
sosreport (version 3.5)

no valid plugins were enabled

```

The resulting output file can be attached to this issue.

## What provider (aws, maas, localhost, etc)?
Maas

### MAAS Users
Which version of MAAS?

## Commands ran
conjure-up

Please outline what commands were run to install and execute conjure-up:
conjure-up

**Comment by gdumo22** [comment]
Nova KVM.
[ERROR] conjure-up/openstack-base - common.py:60 - Error bootstrapping controller: ['Creating Juju controller "conjure-up-cloud-maas-b89-33f" on cloud-maas-b89', 'Looking for packaged Juju agent version 2.4.3 for amd64', 'Launching controller instance(s) on cloud-maas-b89...', 'ERROR failed to bootstrap model: cannot start bootstrap instance in availability zone "default": failed to acquire node: No available machine matches constraints: [(\'agent_name\', [\'8b0a19e5-906c-4312-860e-e9f25dcecfe5\']), (\'mem\', [\'3584\']), (\'zone\', [\'default\'])] (resolved to "mem=3584.0 zone=default")']

[ERROR] conjure-up/openstack-base - events.py:161 - Unhandled exception in <Task finished coro=<BaseBootstrapController.run() done, defined at /snap/conjure-up/1031/lib/python3.6/site-packages/conjureup/controllers/juju/bootstrap/common.py:15> exception=BootstrapError('Unable to bootstrap (cloud type: maas)',)>
Traceback (most recent call last):
  File "/snap/conjure-up/1031/lib/python3.6/site-packages/conjureup/controllers/juju/bootstrap/common.py", line 21, in run
    await self.do_bootstrap()
  File "/snap/conjure-up/1031/lib/python3.6/site-packages/conjureup/controllers/juju/bootstrap/common.py", line 65, in do_bootstrap
    app.provider.cloud_type))
conjureup.errors.BootstrapError: Unable to bootstrap (cloud type: maas)
