### ISSUE TITLE
Can't deploy Canonical K8S to OpenStack using conjure-up

### ISSUE THREAD

**Issue by mlbiam** [conjure-up/conjure-up#1533]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [x ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [no ] Is conjure-up running inside a virtual machine?
- [X ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju /snap/bin/juju
juju version 2.4.3-bionic-amd64

which conjure-up /snap/bin/conjure-up
conjure-up --version conjure-up 2.6.1

which lxc /snap/bin/lxc
/snap/bin/lxc config show

config:
  core.https_address: '[::]'

/snap/bin/lxc version

Client version: 3.6
Server version: 3.6

cat /etc/lsb-release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

Please attach tarball of **~/.cache/conjure-up
[conjure-up-tarball.tar.gz](https://github.com/conjure-up/conjure-up/files/2522078/conjure-up-tarball.tar.gz)

**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport

sosreport

sosreport (version 3.5)

no valid plugins were enabled
```

The resulting output file can be attached to this issue.

## What Spell was Selected?

Kubernetes

## What provider (aws, maas, localhost, etc)?

openstack

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

Trying to deploy Canonical k8s on Canonical OpenStack on 18.04. I:

1.  Deployed OpenStack on a box with 16G memory, 512G disk with a bridged network
2.  Login to horizon: a. Create a domain called "k8s_domain" b. Create project in k8s_domain called "kubernetes" c. Create user "k8s" thats a user in kubernetes/k8s_domain d. Make k8s an admin in kubernetes/k8s_domain e. Download the openstack v3 rc file
3.  Source k8s' rc file
4.  Create ec2 credentials "openstack ec2 credentials create"
5.  on the server, run conjure-up kubernetes
6.  choose openstack for my cloud username = k8s password = **** domain name = k8s_domain project domain name = kubernetes access key = **** secret key = ****
7.  When clicking "save" - Review log messages at /home/os/.cache/conjure-up/conjure-up.log If appropriate, please submit a bug here:
https://github.com/conjure-up/conjure-up/issues/new

Here's the log:
```
2018-10-14 20:49:56,198 [ERROR] conjure-up/canonical-kubernetes - events.py:161 - Unhandled exception in <Task finished coro=<CredentialsController._save_credential() done, defined at /snap/conjure-up/1030/lib/python3.6/site-packages/conjureup/controllers/juju/credentials/gui.py:76> exception=NotImplementedError()>
Traceback (most recent call last):
  File "/snap/conjure-up/1030/lib/python3.6/site-packages/conjureup/controllers/juju/credentials/gui.py", line 109, in _save_credential
    juju.get_cloud(app.provider.cloud)
  File "/snap/conjure-up/1030/lib/python3.6/site-packages/conjureup/juju.py", line 533, in get_cloud
    raise LookupError("Unable to locate cloud: {}".format(name))
LookupError: Unable to locate cloud: cloud-openstack-5c0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/conjure-up/1030/lib/python3.6/site-packages/conjureup/controllers/juju/credentials/gui.py", line 112, in _save_credential
    await app.provider.cloud_config())
  File "/snap/conjure-up/1030/lib/python3.6/site-packages/conjureup/models/provider.py", line 170, in cloud_config
    raise NotImplementedError
NotImplementedError
```

**Comment by battlemidget** [comment]
Ah, we just don't handle that provider. We'll need to add support for that, sorry!

**Comment by mlbiam** [comment]
As in the deployer for openstack isn't implemented yet?
