### ISSUE TITLE
can't deploy instance in conjure'd openstack-novalxd localhost

### ISSUE THREAD

**Issue by hyacin75** [conjure-up/conjure-up#1540]
Brand new fresh install of 18.04 Workstation directly onto an i7-7xxx box with 16 GB of RAM, with a 120 GB SSD dedicated to Ubuntu.  conjure-up goes great, and when it is done the Horizon console works perfectly - I can log in and do absolutely everything, but when I try to launch an instance is always fails.  It appears to be failing because "Image  could not be found.", but I've included the full output from the nova-conductor.log at the time I am trying to launch, below.

## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ No ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ No ] Is conjure-up running inside a virtual machine?
- [ Trying that next ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
rob@i7-Laptop:~$ which juju
/snap/bin/juju
rob@i7-Laptop:~$ which conjure-up
/snap/bin/conjure-up
rob@i7-Laptop:~$ which lxd
/snap/bin/lxd
rob@i7-Laptop:~$ juju version
2.4.3-bionic-amd64
rob@i7-Laptop:~$ conjure-up --version
conjure-up 2.6.1
rob@i7-Laptop:~$ lxd --version
3.6
rob@i7-Laptop:~$ lxc config show
config:
  core.https_address: '[::]'
  core.trust_password: true
rob@i7-Laptop:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
rob@i7-Laptop:~$
```

Please attach tarball of **~/.cache/conjure-up**:

[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2567405/conjure-up.tar.gz)

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```
[sosreport-hyacin75-20181109152700.tar.zip](https://github.com/conjure-up/conjure-up/files/2567423/sosreport-hyacin75-20181109152700.tar.zip)

## What Spell was Selected?
OpenStack with NovaLXD

## What provider (aws, maas, localhost, etc)?
localhost

## Commands ran

I followed the instructions here -
https://www.ubuntu.com/openstack/install#workstation-deployment

With only the following exceptions -

Skipped sudo lxd.migrate as I learned after much fighting with it that it doesn't work and isn't needed.
Specified no ipv6 on the bridge interface as I've already learned that breaks conjure-up.

## Additional Information
nova-conductor logs from when I try to launch it and it fails -

```
2018-11-09 19:38:33.230 15164 ERROR nova.scheduler.utils [req-af236df1-2973-4cce-b35a-31b2cc03f61e ef04640543a74fce9ac9e465c9f1e688 33d8b8ecbc85499bb9196fe0e1459e9a - 56a7064922b342918db6696c21739d81 56a7064922b342918db6696c21739d81] [instance: a9ada324-0717-41a3-9cca-bd868b7f904f] Error from last host: juju-4d09cd-14 (node juju-4d09cd-14): [u'Traceback (most recent call last):\n', u'  File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 1840, in _do_build_and_run_instance\n    filter_properties, request_spec)\n', u'  File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 2120, in _build_and_run_instance\n    instance_uuid=instance.uuid, reason=six.text_type(e))\n', u'RescheduledException: Build of instance a9ada324-0717-41a3-9cca-bd868b7f904f was re-scheduled: Image  could not be found.\n']
2018-11-09 19:38:33.232 15164 WARNING nova.scheduler.utils [req-af236df1-2973-4cce-b35a-31b2cc03f61e ef04640543a74fce9ac9e465c9f1e688 33d8b8ecbc85499bb9196fe0e1459e9a - 56a7064922b342918db6696c21739d81 56a7064922b342918db6696c21739d81] Failed to compute_task_build_instances: Exceeded maximum number of retries. Exhausted all hosts available for retrying build failures for instance a9ada324-0717-41a3-9cca-bd868b7f904f.: MaxRetriesExceeded: Exceeded maximum number of retries. Exhausted all hosts available for retrying build failures for instance a9ada324-0717-41a3-9cca-bd868b7f904f.
2018-11-09 19:38:33.232 15164 WARNING nova.scheduler.utils [req-af236df1-2973-4cce-b35a-31b2cc03f61e ef04640543a74fce9ac9e465c9f1e688 33d8b8ecbc85499bb9196fe0e1459e9a - 56a7064922b342918db6696c21739d81 56a7064922b342918db6696c21739d81] [instance: a9ada324-0717-41a3-9cca-bd868b7f904f] Setting instance to ERROR state.: MaxRetriesExceeded: Exceeded maximum number of retries. Exhausted all hosts available for retrying build failures for instance a9ada324-0717-41a3-9cca-bd868b7f904f.
2018-11-09 19:38:33.380 15164 ERROR nova.conductor.manager [req-7d21b40c-2304-41e3-a706-3aa7c75e4d09 - - - - -] [instance: a9ada324-0717-41a3-9cca-bd868b7f904f] Failed to deallocate networks: NoSuchOptError: no such option keystone_authtoken in group [DEFAULT]
2018-11-09 19:38:33.380 15164 ERROR nova.conductor.manager [instance: a9ada324-0717-41a3-9cca-bd868b7f904f] Traceback (most recent call last):
2018-11-09 19:38:33.380 15164 ERROR nova.conductor.manager [instance: a9ada324-0717-41a3-9cca-bd868b7f904f]   File "/usr/lib/python2.7/dist-packages/nova/conductor/manager.py", line 366, in _cleanup_allocated_networks
2018-11-09 19:38:33.380 15164 ERROR nova.conductor.manager [instance: a9ada324-0717-41a3-9cca-bd868b7f904f]     context, instance, requested_networks=requested_networks)
2018-11-09 19:38:33.380 15164 ERROR nova.conductor.manager [instance: a9ada324-0717-41a3-9cca-bd868b7f904f]   File "/usr/lib/python2.7/dist-packages/nova/network/neutronv2/api.py", line 1270, in deallocate_for_instance
2018-11-09 19:38:33.380 15164 ERROR nova.conductor.manager [instance: a9ada324-0717-41a3-9cca-bd868b7f904f]     self._unbind_ports(context, ports_to_skip, neutron)
2018-11-09 19:38:33.380 15164 ERROR nova.conductor.manager [instance: a9ada324-0717-41a3-9cca-bd868b7f904f]   File "/usr/lib/python2.7/dist-packages/nova/network/neutronv2/api.py", line 527, in _unbind_ports
2018-11-09 19:38:33.380 15164 ERROR nova.conductor.manager [instance: a9ada324-0717-41a3-9cca-bd868b7f904f]     port_client = get_client(context, admin=True)
2018-11-09 19:38:33.380 15164 ERROR nova.conductor.manager [instance: a9ada324-0717-41a3-9cca-bd868b7f904f]   File "/usr/lib/python2.7/dist-packages/nova/network/neutronv2/api.py", line 153, in get_client
2018-11-09 19:38:33.380 15164 ERROR nova.conductor.manager [instance: a9ada324-0717-41a3-9cca-bd868b7f904f]     _ADMIN_AUTH = _load_auth_plugin(CONF)
2018-11-09 19:38:33.380 15164 ERROR nova.conductor.manager [instance: a9ada324-0717-41a3-9cca-bd868b7f904f]   File "/usr/lib/python2.7/dist-packages/nova/network/neutronv2/api.py", line 70, in _load_auth_plugin
2018-11-09 19:38:33.380 15164 ERROR nova.conductor.manager [instance: a9ada324-0717-41a3-9cca-bd868b7f904f]     nova.conf.neutron.NEUTRON_GROUP)
2018-11-09 19:38:33.380 15164 ERROR nova.conductor.manager [instance: a9ada324-0717-41a3-9cca-bd868b7f904f]   File "/usr/lib/python2.7/dist-packages/keystoneauth1/loading/conf.py", line 122, in load_from_conf_options
2018-11-09 19:38:33.380 15164 ERROR nova.conductor.manager [instance: a9ada324-0717-41a3-9cca-bd868b7f904f]     name = conf[group].auth_type
2018-11-09 19:38:33.380 15164 ERROR nova.conductor.manager [instance: a9ada324-0717-41a3-9cca-bd868b7f904f]   File "/usr/lib/python2.7/dist-packages/oslo_config/cfg.py", line 2523, in __getitem__
2018-11-09 19:38:33.380 15164 ERROR nova.conductor.manager [instance: a9ada324-0717-41a3-9cca-bd868b7f904f]     return self.__getattr__(key)
2018-11-09 19:38:33.380 15164 ERROR nova.conductor.manager [instance: a9ada324-0717-41a3-9cca-bd868b7f904f]   File "/usr/lib/python2.7/dist-packages/oslo_config/cfg.py", line 2519, in __getattr__
2018-11-09 19:38:33.380 15164 ERROR nova.conductor.manager [instance: a9ada324-0717-41a3-9cca-bd868b7f904f]     raise NoSuchOptError(name)
2018-11-09 19:38:33.380 15164 ERROR nova.conductor.manager [instance: a9ada324-0717-41a3-9cca-bd868b7f904f] NoSuchOptError: no such option keystone_authtoken in group [DEFAULT]
2018-11-09 19:38:33.380 15164 ERROR nova.conductor.manager [instance: a9ada324-0717-41a3-9cca-bd868b7f904f]
```

**Comment by hyacin75** [comment]
Ok, the first time I tried it with --edge the conjure hung ... sat there for more than three hours with all the boxes green, but 8 that were still blue.  I blew the whole thing away, again, and tried, again, this time with --edge --classic (I hope those don't conflict, it said "refreshed to edge" or whatever) ... this time the conjure worked fine, but again the exact same "Image could not be found" error in the logs when I try to launch an instance :(

**Comment by hyacin75** [comment]
I did another fresh install from scratch, 18.04, updated to 18.04.1, followed [these](https://www.ubuntu.com/openstack/install#workstation-deployment) instructions - but this time I used only wired networking, just in case that was the problem ... I got the exact same error when I tried to launch an instance.

**Comment by crbertoldo** [comment]
I'm facing the same issue in a similar environmemt.

**Comment by hyacin75** [comment]
Tried again, with a fresh server install, wired networking, and a static IPv4 IP instead of DHCP ... again, same error when trying to launch an instance :-(

**Comment by hyacin75** [comment]
conjure-down also completely fails on either of the entries in the menu.

**Comment by hyacin75** [comment]
Does anyone care?  Is anyone going to at least take a look or acknowledge this, or should I just stop checking this page twice a day and give up on conjure-up entirely?

**Comment by crbertoldo** [comment]
Conjure-up Team, please help us.

**Comment by battlemidget** [comment]
@ryan-beisner @ChrisMacNaughton One of you mind taking a look at this?

**Comment by gnuoy** [comment]
I have followed the guide and it worked for me. I think the error that was seen in the conductor log may be caused by a failure to ensure "Create New Volume: No" is set when launching an instance through horizon.

```
ubuntu@model-crow:~$ which juju
/snap/bin/juju
ubuntu@model-crow:~$ which conjure-up
/snap/bin/conjure-up
ubuntu@model-crow:~$ which lxd
/snap/bin/lxd
ubuntu@model-crow:~$ juju version
2.4.3-bionic-amd64
ubuntu@model-crow:~$ conjure-up --version
conjure-up 2.6.1
ubuntu@model-crow:~$ lxd --version
3.7
ubuntu@model-crow:~$ lxc config show
config:
  core.https_address: '[::]'
ubuntu@model-crow:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
ubuntu@model-crow:~$ juju ssh nova-cloud-controller/0 "source ~/novarc; openstack image list"
+--------------------------------------+------------+--------+
| ID                                   | Name       | Status |
+--------------------------------------+------------+--------+
| 01358ac5-5678-476a-a503-d2b2b402cee2 | bionic-lxd | active |
| 2e32c7d5-cac8-4779-8b6c-064fc2eeaccd | xenial-lxd | active |
+--------------------------------------+------------+--------+
Connection to 10.8.8.90 closed.
ubuntu@model-crow:~$ juju ssh nova-cloud-controller/0 "source ~/novarc; openstack server list"
+--------------------------------------+------+--------+-------------------+------------+---------+
| ID                                   | Name | Status | Networks          | Image      | Flavor  |
+--------------------------------------+------+--------+-------------------+------------+---------+
| c5c6fdce-5855-46af-8042-2f090af2e3a2 | test | ACTIVE | internal=10.5.5.8 | bionic-lxd | m1.tiny |
+--------------------------------------+------+--------+-------------------+------------+---------+
Connection to 10.8.8.90 closed.
```

**Comment by hyacin75** [comment]
Oh awesome, thanks.  I think I've got CentOS and a non-functional PackStack installed on there now.  I'll try to get it flipped back over and give this a try tonight.

**Comment by crbertoldo** [comment]
@gnuoy thanks for https://github.com/conjure-up/spells/commit/93bceac3fb63fa10dcb3ec3b9733c2e9ebb1ab93
Anyway I didn't understand thru official docs the cons of setting it no 'no'

**Comment by hyacin75** [comment]
@gnuoy Yep, that was it, thank you.

I have a whole suite of new issues now - but as they're not bugs, this isn't really the place to discuss them.  Is there such a place which is conjure-up specific, as we all have the same deployment so we probably all work through the same issues?  The general OpenStack forums, as well as Reddit thus far, have been absolutely zero help (and zero replies).

Thanks.

**Comment by battlemidget** [comment]
I think it's fine here or over https://discourse.jujucharms.com/c/conjure-up traffic is light to that discourse board though.

**Comment by hyacin75** [comment]
Perfect, thanks, I'll bring the remainder of my issues there!
