### ISSUE TITLE
conjure-down 'NoneType' object has no attribute 'controller'

### ISSUE THREAD

**Issue by joedborg** [conjure-up/conjure-up#1548]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [x] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [x] Is conjure-up running inside a virtual machine?
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
/snap/bin/juju

juju version
2.4.7-bionic-amd64

which conjure-up
/snap/bin/conjure-up

conjure-up --version
conjure-up 2.6.1

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

```

Please attach tarball of **~/.cache/conjure-up**:

```
2018-12-04 13:55:18,968 [DEBUG] conjure-up/_unspecified_spell - juju.py:35 - bin_path candidate found
2018-12-04 13:55:18,970 [INFO] conjure-up/_unspecified_spell - events.py:173 - Watching for shutdown
2018-12-04 13:55:19,020 [DEBUG] conjure-up/_unspecified_spell - events.py:52 - Awaiting Shutdown at conjureup/events.py:176
2018-12-04 13:55:19,277 [DEBUG] conjure-up/_unspecified_spell - telemetry.py:17 - Showing screen: Destroy Controller
2018-12-04 13:55:23,887 [DEBUG] conjure-up/_unspecified_spell - events.py:52 - Setting Error at conjureup/events.py:149
2018-12-04 13:55:23,893 [ERROR] conjure-up/_unspecified_spell - events.py:161 - Unhandled exception
Traceback (most recent call last):
  File "/snap/conjure-up/1031/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/snap/conjure-up/1031/lib/python3.6/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/snap/conjure-up/1031/lib/python3.6/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/snap/conjure-up/1031/lib/python3.6/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/snap/conjure-up/1031/lib/python3.6/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/snap/conjure-up/1031/lib/python3.6/site-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/snap/conjure-up/1031/lib/python3.6/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/snap/conjure-up/1031/lib/python3.6/site-packages/conjureup/ui/views/destroy.py", line 26, in keypress
    return super().keypress(size, key)
  File "/snap/conjure-up/1031/lib/python3.6/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/snap/conjure-up/1031/lib/python3.6/site-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/snap/conjure-up/1031/lib/python3.6/site-packages/urwid/decoration.py", line 836, in keypress
    return self._original_widget.keypress((maxcol,), key)
  File "/snap/conjure-up/1031/lib/python3.6/site-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/snap/conjure-up/1031/lib/python3.6/site-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/snap/conjure-up/1031/lib/python3.6/site-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/snap/conjure-up/1031/lib/python3.6/site-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/snap/conjure-up/1031/lib/python3.6/site-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/snap/conjure-up/1031/lib/python3.6/site-packages/conjureup/ui/views/destroy.py", line 101, in submit
    self.cb(controller, model)
  File "/snap/conjure-up/1031/lib/python3.6/site-packages/conjureup/controllers/juju/destroy/gui.py", line 13, in finish
    return controllers.use('destroyconfirm').render(controller, model)
  File "/snap/conjure-up/1031/lib/python3.6/site-packages/conjureup/controllers/juju/destroyconfirm/gui.py", line 50, in render
    app.provider.controller = controller
AttributeError: 'NoneType' object has no attribute 'controller'
2018-12-04 13:55:23,904 [DEBUG] conjure-up/_unspecified_spell - __init__.py:27 - Showing dialog for exception: 'NoneType' object has no attribute 'controller'
2018-12-04 13:55:47,974 [DEBUG] conjure-up/_unspecified_spell - events.py:52 - Setting Shutdown at conjureup/events.py:145
2018-12-04 13:55:47,975 [DEBUG] conjure-up/_unspecified_spell - events.py:52 - Received Shutdown at conjureup/events.py:176
2018-12-04 13:55:47,975 [INFO] conjure-up/_unspecified_spell - events.py:180 - Shutting down
```

## What Spell was Selected?

canonical-kubernetes on AWS

## Commands ran
`conjure-down`

**Comment by azalou** [comment]
Same Issue
## Report
Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [x] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems no
- [x] Is conjure-up running inside a virtual machine? yes
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`? yes

## Please provide the output of the following commands

```
which juju
/snap/bin/juju

juju version
2.4.3-cosmic-amd64

which conjure-up
/snap/bin/conjure-up

conjure-up --version
conjure-up 2.6.4

which lxc
/snap/bin/lxc

/snap/bin/lxc config show
core.https_address: 127.0.0.1

/snap/bin/lxc version
Client version: 3.9
Server version: 3.9

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.10
DISTRIB_CODENAME=cosmic
DISTRIB_DESCRIPTION="Ubuntu 18.10"
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2813211/conjure-up.tar.gz)

## Sosreport

Please attach a sosreport:


```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.


## What Spell was Selected?

## What provider (aws, maas, localhost, etc)?
localhost


## Commands ran
conjure-down
Please outline what commands were run to install and execute conjure-up:
snap install conjure-up --classic
## Additional Information
I also get sometimes 'NoneType' object is not subscriptable
[sosreport-azaloulinux.1548-20190130103257.tar.gz](https://github.com/conjure-up/conjure-up/files/2813244/sosreport-azaloulinux.1548-20190130103257.tar.gz)
