### ISSUE TITLE
conjure-up Unable to bootstrap (cloud type: maas)

### ISSUE THREAD

**Issue by rafise** [conjure-up/conjure-up#1567]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
juju version

which conjure-up
conjure-up --version

which lxc
/snap/bin/lxc config show
/snap/bin/lxc version

cat /etc/lsb-release
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

## Additional Information

Hello All,

I'm new to conjure-up and seams this issue is known but not clear how to fix it. Heres the error log I'm getting also I have 12 machines ready in maas thanks, guys. 

###################################################################
maas01:~$ cat .cache/conjure-up/conjure-up.log
2018-12-27 22:38:35,144 [DEBUG] conjure-up/_unspecified_spell - juju.py:35 - bin_path candidate found
2018-12-27 22:38:35,144 [DEBUG] conjure-up/_unspecified_spell - juju.py:35 - wait_path candidate found
2018-12-27 22:38:35,298 [DEBUG] conjure-up/_unspecified_spell - app.py:293 - Juju version: 2.4.3-bionic-amd64, conjure-up version: 2.6.4
2018-12-27 22:38:35,360 [INFO] conjure-up/_unspecified_spell - events.py:173 - Watching for shutdown
2018-12-27 22:38:35,502 [DEBUG] conjure-up/_unspecified_spell - events.py:52 - Awaiting Shutdown at conjureup/events.py:176
2018-12-27 22:38:35,502 [DEBUG] conjure-up/_unspecified_spell - telemetry.py:17 - Showing screen: Application Start
2018-12-27 22:38:35,518 [DEBUG] conjure-up/_unspecified_spell - telemetry.py:32 - OS: Linux-4.15.0-43-generic-x86_64-with-debian-buster-sid
2018-12-27 22:38:35,556 [DEBUG] conjure-up/_unspecified_spell - telemetry.py:17 - Showing screen: Spell Selection
2018-12-27 22:39:40,290 [DEBUG] conjure-up/_unspecified_spell - telemetry.py:32 - Spell Choice: openstack-base
2018-12-27 22:39:40,300 [DEBUG] conjure-up/openstack-base - download.py:60 - Path is local filesystem, copying /snap/conjure-up/1039/spells/openstack-base to /home/rafi/.cache/conjure-up/openstack-base
2018-12-27 22:39:40,655 [DEBUG] conjure-up/openstack-base - step.py:27 - steps: [<StepModel OpenStack with NovaKVM 01_glance v: True c: []>, <StepModel OpenStack with NovaKVM 02_keypair v: True c: []>, <StepModel OpenStack with NovaKVM 03_neutron v: True c: []>, <StepModel OpenStack with NovaKVM 04_horizon v: True c: []>]
2018-12-27 22:39:40,655 [DEBUG] conjure-up/openstack-base - __init__.py:126 - Pulling bundle for openstack-base from channel: stable
2018-12-27 22:39:43,033 [DEBUG] conjure-up/openstack-base - telemetry.py:17 - Showing screen: Choose a Cloud
2018-12-27 22:39:45,360 [DEBUG] conjure-up/openstack-base - telemetry.py:32 - Cloud selection: cloud-maas-1e7
2018-12-27 22:39:45,382 [DEBUG] conjure-up/openstack-base - telemetry.py:17 - Showing screen: New Credential Creation
2018-12-27 22:40:59,580 [DEBUG] conjure-up/openstack-base - juju.py:509 - {'clouds': {'cloud-maas-1e7': {'type': 'maas', 'auth-types': ['oauth1'], 'endpoint': 'http://10.1.1.1:5240/MAAS'}}}
2018-12-27 22:41:00,108 [DEBUG] conjure-up/openstack-base - telemetry.py:17 - Showing screen: Configure Spell
2018-12-27 22:41:17,271 [DEBUG] conjure-up/openstack-base - telemetry.py:17 - Showing screen: Configure Applications
2018-12-27 22:41:18,148 [DEBUG] conjure-up/openstack-base - maas.py:20 - Found endpoint: http://10.1.1.1:5240/MAAS for cloud: cloud-maas-1e7
2018-12-27 22:41:18,169 [DEBUG] conjure-up/openstack-base - events.py:52 - Setting MAASConnected at conjureup/controllers/juju/configapps/gui.py:39
2018-12-27 22:43:01,159 [DEBUG] conjure-up/openstack-base - telemetry.py:17 - Showing screen: Keyboard Navigation
2018-12-27 22:43:20,614 [DEBUG] conjure-up/openstack-base - telemetry.py:17 - Showing screen: Configure Applications
2018-12-27 22:43:25,648 [DEBUG] conjure-up/openstack-base - telemetry.py:17 - Showing screen: Bootstrapping Controller
2018-12-27 22:43:25,817 [INFO] conjure-up/openstack-base - common.py:74 - Bootstrapping Juju controller...
2018-12-27 22:43:25,818 [DEBUG] conjure-up/openstack-base - telemetry.py:32 - Juju Bootstrap: Started
2018-12-27 22:43:25,828 [DEBUG] conjure-up/openstack-base - juju.py:252 - bootstrap cmd: ['/snap/bin/juju', 'bootstrap', 'cloud-maas-1e7', 'conjure-up-cloud-maas-1e7-f31', '--default-model', 'conjure-openstack-base-940', '--config', 'image-stream=daily', '--credential', 'conjure-cloud-maas-1e7-79a']
2018-12-27 22:43:25,849 [DEBUG] conjure-up/openstack-base - events.py:52 - Awaiting Bootstrapped at conjureup/controllers/juju/bootstrap/gui.py:43
2018-12-27 23:03:27,506 [ERROR] conjure-up/openstack-base - common.py:60 - Error bootstrapping controller: ['Creating Juju controller "conjure-up-cloud-maas-1e7-f31" on cloud-maas-1e7', 'Looking for packaged Juju agent version 2.4.3 for amd64', 'Launching controller instance(s) on cloud-maas-1e7...', ' - 6ngwqr (arch=amd64 mem=48G cores=16)', 'Installing Juju agent on bootstrap instance', 'Fetching Juju GUI 2.14.0', 'ERROR failed to bootstrap model: bootstrap instance started but did not change to Deployed state: instance "6ngwqr" is started but not deployed']
2018-12-27 23:03:27,516 [DEBUG] conjure-up/openstack-base - events.py:52 - Setting Error at conjureup/events.py:149
2018-12-27 23:03:27,528 [ERROR] conjure-up/openstack-base - events.py:161 - Unhandled exception in <Task finished coro=<BaseBootstrapController.run() done, defined at /snap/conjure-up/1039/lib/python3.6/site-packages/conjureup/controllers/juju/bootstrap/common.py:15> exception=BootstrapError('Unable to bootstrap (cloud type: maas)',)>
Traceback (most recent call last):
  File "/snap/conjure-up/1039/lib/python3.6/site-packages/conjureup/controllers/juju/bootstrap/common.py", line 21, in run
    await self.do_bootstrap()
  File "/snap/conjure-up/1039/lib/python3.6/site-packages/conjureup/controllers/juju/bootstrap/common.py", line 65, in do_bootstrap
    app.provider.cloud_type))
conjureup.errors.BootstrapError: Unable to bootstrap (cloud type: maas)
2018-12-27 23:03:27,549 [DEBUG] conjure-up/openstack-base - __init__.py:27 - Showing dialog for exception: Unable to bootstrap (cloud type: maas)
2018-12-27 23:07:07,602 [DEBUG] conjure-up/openstack-base - events.py:52 - Setting Shutdown at conjureup/events.py:145
2018-12-27 23:07:07,605 [DEBUG] conjure-up/openstack-base - events.py:52 - Received Shutdown at conjureup/events.py:176
2018-12-27 23:07:07,605 [INFO] conjure-up/openstack-base - events.py:180 - Shutting down
2018-12-27 23:07:07,606 [INFO] conjure-up/openstack-base - app_config.py:192 - Storing conjure-up state
2018-12-27 23:07:07,622 [INFO] conjure-up/openstack-base - app_config.py:207 - State saved
2018-12-27 23:07:07,623 [DEBUG] conjure-up/openstack-base - events.py:200 - Cancelling pending task: <Task pending coro=<BootstrapController.wait() running at /snap/conjure-up/1039/lib/python3.6/site-packages/conjureup/controllers/juju/bootstrap/gui.py:43> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fbdb6797258>()]>>
rafi@maas01:

**Comment by rafise** [comment]
forgot to attach this info

rafi@maas01:~$ which juju
/snap/bin/juju
rafi@maas01:~$ juju version
2.4.3-bionic-amd64
rafi@maas01:~$ which conjure-up
/snap/bin/conjure-up
rafi@maas01:~$ conjure-up --version
conjure-up 2.6.4
rafi@maas01:~$ which lxc
/usr/bin/lxc
rafi@maas01:~$ /snap/bin/lxc config show
-bash: /snap/bin/lxc: No such file or directory
rafi@maas01:~$ /snap/bin/lxc version
-bash: /snap/bin/lxc: No such file or directory
rafi@maas01:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
rafi@maas01:~$

**Comment by rafise** [comment]
I was able to pull some logs, not sure what script is looking for?

12:28:13 INFO  cmd bootstrap.go:344 Connected to 10.0.0.2
12:28:13 INFO  juju.cloudconfig userdatacfg_unix.go:465 Fetching agent: curl -sSfw 'agent binaries from %{url_effective} downloaded: HTTP %{http_code}; time %{time_total}s; size %{size_download} bytes; speed %{speed_download} bytes/s ' --retry 10 -o $bin/tools.tar.gz <[https://streams.canonical.com/juju/tools/agent/2.4.3/juju-2.4.3-ubuntu-amd64.tgz]>
12:28:13 INFO  cmd bootstrap.go:414 Running machine configuration script...

**Comment by rafise** [comment]
Found the network setting was incorrect at the maas servers.
