### ISSUE TITLE
Error while installing grafana: Couldn't acquire DPKG lock

### ISSUE THREAD

**Issue by ik9999** [conjure-up/conjure-up#1569]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine? It runs on a vds
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
# which juju
/snap/bin/juju
#juju version
2.4.3-cosmic-amd64
#which conjure-up
/snap/bin/conjure-up 
#conjure-up --version
conjure-up 2.6.4
#which lxc
/snap/bin/lxc
#/snap/bin/lxc config show
config:
  core.https_address: '[::]'

#/snap/bin/lxc version
Client version: 3.6
Server version: 3.6 
# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.10
DISTRIB_CODENAME=cosmic
DISTRIB_DESCRIPTION="Ubuntu 18.10"

```

Please attach tarball of **~/.cache/conjure-up**:

Can do if needed.

## Sosreport

Please attach a sosreport:

```
#sudo apt install sosreport
#sosreport
no valid plugins were enabled
```

The resulting output file can be attached to this issue.

### MAAS Users
Which version of MAAS?

How can i check it?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

conjure-up

## Additional Information
Error in logs:
```
unit-grafana-0: 19:16:50 ERROR unit.grafana/0.juju-log Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-grafana-0/.venv/lib/python3.6/site-packages/charms/reactive/__init__.py", line 73, in main
  bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-grafana-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 382, in dispatch
  _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-grafana-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 358, in _invoke
  handler.invoke()
  File "/var/lib/juju/agents/unit-grafana-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 180, in invoke
  self._action(*args)
  File "/var/lib/juju/agents/unit-grafana-0/charm/reactive/grafana.py", line 113, in install_packages
  fetch.configure_sources(update=True)
  File "/var/lib/juju/agents/unit-grafana-0/.venv/lib/python3.6/site-packages/charmhelpers/fetch/__init__.py", line 147, in configure_sources
  _fetch_update(fatal=True)
  File "/var/lib/juju/agents/unit-grafana-0/.venv/lib/python3.6/site-packages/charmhelpers/fetch/ubuntu.py", line 237, in apt_update
  _run_apt_command(cmd, fatal)
  File "/var/lib/juju/agents/unit-grafana-0/.venv/lib/python3.6/site-packages/charmhelpers/fetch/ubuntu.py", line 576, in _run_apt_command
  retry_message="Couldn't acquire DPKG lock")
  File "/var/lib/juju/agents/unit-grafana-0/.venv/lib/python3.6/site-packages/charmhelpers/fetch/ubuntu.py", line 552, in _run_with_retries
  result = subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
  raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['apt-get', 'update']' returned non-zero exit status 100.

```

**Comment by kwmonroe** [comment]
@ik9999 the grafana charm had problem with its apt repo, and was fixed here:

https://git.launchpad.net/grafana-charm/commit/?id=e20740ccf84b68e329cb6be908f9a071196f0c3c

Which spell did you select to hit this error?  We may need to update it to ensure the latest grafana charm revision is being used:

https://jujucharms.com/grafana/

FYI, if you used a kubernetes spell and selected prometheus as an addon, you would have hit this.  That has been fixed in https://github.com/conjure-up/spells/pull/242 and will be released soon. If you need an immediate workaround to get this new spell, pass the branch option to conjure-up like this:
```bash
conjure-up -b feature/k8s-monitor-refresh
```
