### ISSUE TITLE
conjure-down fails to remove lxd openstack on localhost

### ISSUE THREAD

**Issue by MRZA-MRZA** [conjure-up/conjure-up#1587]
## Report

- [no] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [no] Is conjure-up running inside a virtual machine?
- [yes] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
/snap/bin/juju
juju version
2.5.0-cosmic-amd64

which conjure-up
/snap/bin/conjure-up
conjure-up --version
conjure-up 2.6.6

which lxc
/usr/bin/lxc
/snap/bin/lxc config show
config:
  core.https_address: '[::]'

/snap/bin/lxc version
Client version: 3.10
Server version: 3.10

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.10
DISTRIB_CODENAME=cosmic
DISTRIB_DESCRIPTION="Ubuntu 18.10"
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2871820/conjure-up.tar.gz)

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport

sosreport (version 3.6)

no valid plugins were enabled
```

## What Spell was Selected?
openstack-novalxd

## What provider (aws, maas, localhost, etc)?
localhost

### MAAS Users
Which version of MAAS?
No MAAS

## Commands ran
conjure-up failed to deploy openstack on localhost with following error:
```
DEBUG:root:mysql/0 workload status is error since 2019-02-15 20:58:07Z
ERROR:root:mysql/0 failed: workload status is error
2019-02-15 23:58:11,541 [DEBUG] conjure-up/openstack-novalxd - events.py:52 - Setting Error at conjureup/events.py:149
2019-02-15 23:58:11,541 [ERROR] conjure-up/openstack-novalxd - events.py:161 - Unhandled exception in <Task finished coro=<DeployController._wait_for_applications() done, defined at /snap/conjure-up/1
043/lib/python3.6/site-packages/conjureup/controllers/juju/deploy/gui.py:81> exception=DeploymentFailure('Some applications failed to start successfully.',)>
Traceback (most recent call last):
  File "/snap/conjure-up/1043/lib/python3.6/site-packages/conjureup/controllers/juju/deploy/gui.py", line 82, in _wait_for_applications
    await common.wait_for_applications(view.set_footer)
  File "/snap/conjure-up/1043/lib/python3.6/site-packages/conjureup/controllers/juju/deploy/common.py", line 50, in wait_for_applications
    await juju.wait_for_deployment()
  File "/snap/conjure-up/1043/lib/python3.6/site-packages/conjureup/juju.py", line 746, in wait_for_deployment
    "Some applications failed to start successfully.")
conjureup.errors.DeploymentFailure: Some applications failed to start successfully.
```
I noticed that I'm running out of space then tried to remove deployment with conjure-down but got the following error:
```
AttributeError: 'NoneType' object has no attribute 'controller'
```

**Comment by MRZA-MRZA** [comment]
I removed deployment with juju and tried again (with plenty of free disk space) but conjure-up failed again:
```
2019-02-20 00:21:22,370 [ERROR] conjure-up/openstack-novalxd - juju.py:744 - DEBUG:root:nova-cloud-controller/0 juju agent status is executing since 2019-02-19 21:02:09Z
DEBUG:root:nova-compute/0 juju agent status is executing since 2019-02-19 21:02:19Z
DEBUG:root:openstack-dashboard/0 juju agent status is executing since 2019-02-19 21:02:15Z
DEBUG:root:ceph-osd/1 workload status is waiting since 2019-02-19 20:25:26Z
DEBUG:root:ceph-radosgw/0 workload status is waiting since 2019-02-19 20:41:51Z
DEBUG:root:cinder/0 workload status is maintenance since 2019-02-19 21:16:08Z
DEBUG:root:glance/0 workload status is maintenance since 2019-02-19 21:14:31Z
DEBUG:root:keystone/0 workload status is maintenance since 2019-02-19 21:14:05Z
DEBUG:root:mysql/0 workload status is error since 2019-02-19 21:21:18Z
ERROR:root:mysql/0 failed: workload status is error
2019-02-20 00:21:22,536 [DEBUG] conjure-up/openstack-novalxd - events.py:52 - Setting Error at conjureup/events.py:149
2019-02-20 00:21:22,546 [ERROR] conjure-up/openstack-novalxd - events.py:161 - Unhandled exception in <Task finished coro=<DeployController._wait_for_applications() done, defined at /snap/conjure-up/1043/lib/python3.6/site-packages/conjureup/controllers/juju/deploy/gui.py:81> exception=DeploymentFailure('Some applications failed to start successfully.',)>
Traceback (most recent call last):
  File "/snap/conjure-up/1043/lib/python3.6/site-packages/conjureup/controllers/juju/deploy/gui.py", line 82, in _wait_for_applications
    await common.wait_for_applications(view.set_footer)
  File "/snap/conjure-up/1043/lib/python3.6/site-packages/conjureup/controllers/juju/deploy/common.py", line 50, in wait_for_applications
    await juju.wait_for_deployment()
  File "/snap/conjure-up/1043/lib/python3.6/site-packages/conjureup/juju.py", line 746, in wait_for_deployment
    "Some applications failed to start successfully.")
conjureup.errors.DeploymentFailure: Some applications failed to start successfully.
2019-02-20 00:21:22,559 [DEBUG] conjure-up/openstack-novalxd - __init__.py:27 - Showing dialog for exception: Some applications failed to start successfully.
2019-02-20 06:35:43,571 [DEBUG] conjure-up/openstack-novalxd - events.py:52 - Setting Shutdown at conjureup/events.py:145
2019-02-20 06:35:43,754 [DEBUG] conjure-up/openstack-novalxd - events.py:52 - Received Shutdown at conjureup/events.py:176
2019-02-20 06:35:43,754 [INFO] conjure-up/openstack-novalxd - events.py:180 - Shutting down
2019-02-20 06:35:43,754 [INFO] conjure-up/openstack-novalxd - app_config.py:192 - Storing conjure-up state
2019-02-20 06:35:44,303 [INFO] conjure-up/openstack-novalxd - app_config.py:207 - State saved
```
