### ISSUE TITLE
hostname 'x.x.x.x' doesn't match either of 'juju-apiserver', 'juju-mongodb', 'localhost'

### ISSUE THREAD

**Issue by 7ko7** [conjure-up/conjure-up#1604]
2019-05-22 09:57:32,067 [INFO] conjure-up/charmed-kubernetes - common.py:74 - Bootstrap complete.
2019-05-22 09:57:32,068 [DEBUG] conjure-up/charmed-kubernetes - telemetry.py:32 - Juju Bootstrap: Done
2019-05-22 09:57:32,133 [DEBUG] conjure-up/charmed-kubernetes - events.py:52 - Setting Error at conjureup/events.py:149
2019-05-22 09:57:32,134 [ERROR] conjure-up/charmed-kubernetes - events.py:161 - Unhandled exception
Traceback (most recent call last):
  File "/snap/conjure-up/1050/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/snap/conjure-up/1050/usr/lib/python3.6/asyncio/selector_events.py", line 734, in _read_ready
    self._protocol.data_received(data)
  File "/snap/conjure-up/1050/usr/lib/python3.6/asyncio/sslproto.py", line 505, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/snap/conjure-up/1050/usr/lib/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/snap/conjure-up/1050/usr/lib/python3.6/ssl.py", line 694, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/snap/conjure-up/1050/usr/lib/python3.6/ssl.py", line 327, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname '192.168.28.66' doesn't match either of 'juju-apiserver', 'juju-mongodb', 'localhost'
2019-05-22 09:57:32,165 [DEBUG] conjure-up/charmed-kubernetes - __init__.py:27 - Showing dialog for exception: hostname '192.168.28.66' doesn't match either of 'juju-a
piserver', 'juju-mongodb', 'localhost'
2019-05-22 09:58:54,792 [DEBUG] conjure-up/charmed-kubernetes - events.py:52 - Setting Shutdown at conjureup/events.py:145
2019-05-22 09:58:54,796 [DEBUG] conjure-up/charmed-kubernetes - events.py:52 - Received Shutdown at conjureup/events.py:176
2019-05-22 09:58:54,796 [INFO] conjure-up/charmed-kubernetes - events.py:180 - Shutting down

[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/3206927/conjure-up.tar.gz)

## Report

Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems

No

Is conjure-up running inside a virtual machine?

Yes

Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

Yes

## Please provide the output of the following commands

which juju
/snap/bin/juju

 juju version
2.6.2-bionic-amd64

which conjure-up
/snap/bin/conjure-up

conjure-up --version
conjure-up 2.6.7

which lxc
/snap/bin/lxc

/snap/bin/lxc config show
config: {}

/snap/bin/lxc version
Client version: 3.13
Server version: 3.13

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

tarball of **~/.cache/conjure-up** attached

sosreport attached

## What Spell was Selected?

Charmed Distribution of Kubernetes

## What provider (aws, maas, localhost, etc)?

vsphere

## Commands ran

conjure-up

NOTES:

ran conjure-up command line and used text ui to choose charmed distribution of kubernetes. Followed the steps and deployed. The Spell succesfully creates Juju Controller Folder and the Model Controller folder within.

It succesfully creates a VM called juju-024013-0
which gets a dhcp ip address 192.168.28.66

The text UI shows this error:

Oops, there was a problem with your install:
Reason:
                  hostname '192.168.28.66' doesn't match either of 'juju-apiserver', 'juju-mongodb', 'localhost'

Contents of dnsmasq dhcp lease:
 
cat /var/lib/dnsmasq/dnsmasq.leases
1558519390 00:50:56:1c:d0:81 192.168.28.66 juju-024013-0 ff:2d:1a:a1:33:00:02:00:00:ab:11:65:c8:a6:93:96:ba:c2:df

**Comment by battlemidget** [comment]
Yea we're hitting this in CI as well, will look into it

**Comment by 7ko7** [comment]
Ok great.

**Comment by johnsca** [comment]
Relevant issue on libjuju: https://github.com/juju/python-libjuju/issues/302

**Comment by battlemidget** [comment]
Should be available in the next hour
