### ISSUE TITLE
Waiting for X kube-system pods to start (vsphere)

### ISSUE THREAD

**Issue by parsifallo** [conjure-up/conjure-up#1616]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [X] Is conjure-up running inside a virtual machine?
- [X] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
admin @ jujusrv:~ $ which juju
/snap/bin/juju
admin @ jujusrv:~ $ juju version
2.6.5-bionic-amd64
admin @ jujusrv:~ $ which conjure-up
/snap/bin/conjure-up
admin @ jujusrv:~ $ conjure-up --version
conjure-up 2.6.8
admin @ jujusrv:~ $ which lxc
/usr/bin/lxc
admin @ jujusrv:~ $ /snap/bin/lxc config show
-bash: /snap/bin/lxc: No such file or directory
admin @ jujusrv:~ $ /snap/bin/lxc version
-bash: /snap/bin/lxc: No such file or directory
admin @ jujusrv:~ $ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

## What Spell was Selected?
charmed-kubernetes

## What provider (aws, maas, localhost, etc)?
vsphere

## Commands ran
sudo snap install conjure-up
conjure-up charmed-kubernetes

## Additional Information
In no way it is possible to deploy charmed-kubernetes on vsphere. I am using latest ESXi 6.7.u2 and vsphere 6.7.u2c. Everything is running except for the master which is wainting until I destroy the controller.

If I choose Prometheus during conjure-up it results in hook failed install.
If I choose flannel during conjure-up it results in Waiting for X kube-system pods to start
If I choose canel during conjure-up it results in Waiting for X kube-system pods to start

**Comment by parsifallo** [comment]
I found this in my logs:

```
goroutine 91920 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc003bfce00, 0x1f7)
        /build/kube-apiserver/parts/kube-apiserver/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:204 +0xc8
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc003bfce00, 0x1f7)
        /build/kube-apiserver/parts/kube-apiserver/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:183 +0x35
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc00643a180, 0x1f7)
        /build/kube-apiserver/parts/kube-apiserver/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:209 +0xa6
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.(*auditResponseWriter).WriteHeader(0xc00992e690, 0x1f7)
        /build/kube-apiserver/parts/kube-apiserver/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/audit.go:219 +0x63
net/http.Error(0x73a4640, 0xc009923550, 0x42fe607, 0x13, 0x1f7)
        /snap/go/3947/src/net/http/server.go:2007 +0x213
k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver.proxyError(0x73a4640, 0xc009923550, 0xc006b19200, 0x42fe607, 0x13, 0x1f7)
        /build/kube-apiserver/parts/kube-apiserver/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:86 +0x60
k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP(0xc0022521c0, 0x73a4640, 0xc009923550, 0xc006b19200)
        /build/kube-apiserver/parts/kube-apiserver/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:115 +0xdb
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc009d60180, 0x73a4640, 0xc009923550, 0xc006b19200)
        /build/kube-apiserver/parts/kube-apiserver/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:241 +0x548
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc0007a2460, 0x73a4640, 0xc009923550, 0xc006b19200)
        /build/kube-apiserver/parts/kube-apiserver/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x85
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x42ef742, 0xf, 0xc00741cb40, 0xc0007a2460, 0x73a4640, 0xc009923550, 0xc006b19200)
        /build/kube-apiserver/parts/kube-apiserver/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:154 +0x6c3
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAudit.func1(0x7f53e855de00, 0xc009923548, 0xc006b19100)
        /build/kube-apiserver/parts/kube-apiserver/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/audit.go:110 +0x50f
net/http.HandlerFunc.ServeHTTP(0xc0098e8140, 0x7f53e855de00, 0xc009923548, 0xc006b19100)
        /snap/go/3947/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7f53e855de00, 0xc009923548, 0xc006b19000)
        /build/kube-apiserver/parts/kube-apiserver/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:81 +0x
net/http.HandlerFunc.ServeHTTP(0xc000e218b0, 0x7f53e855de00, 0xc009923548, 0xc006b19000)
        /snap/go/3947/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc0059251a0, 0xc0098c8a60, 0x73b0340, 0xc009923548, 0xc006b19000)
        /build/kube-apiserver/parts/kube-apiserver/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:111 +0xb3
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
        /build/kube-apiserver/parts/kube-apiserver/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:98 +0x1b1
logging error output: "service unavailable\n"
 [kube-controller-manager/v1.15.0 (linux/amd64) kubernetes/e8462b5/generic-garbage-collector 127.0.0.1:53388]

```

**Comment by parsifallo** [comment]
As well as these:

```
            "message": "Failed to pull image \"image-registry.canonical.com:5000/cdk/coredns/coredns:1.4.0\": rpc error: code = Unknown desc = failed to resolve image \"image-registry.canonical.com:5000/cdk/coredns/coredns:1.4.0\": no available registry endpoint: failed to do request: Head https://image-registry.canonical.com:5000/v2/cdk/coredns/coredns/manifests/1.4.0: dial tcp 162.213.33.199:5000: i/o timeout",
            "message": "Failed to pull image \"image-registry.canonical.com:5000/cdk/coredns/coredns:1.4.0\": rpc error: code = Unknown desc = failed to resolve image \"image-registry.canonical.com:5000/cdk/coredns/coredns:1.4.0\": no available registry endpoint: failed to do request: Head https://image-registry.canonical.com:5000/v2/cdk/coredns/coredns/manifests/1.4.0: dial tcp 162.213.33.199:5000: i/o timeout",
            "message": "Failed to pull image \"image-registry.canonical.com:5000/cdk/coredns/coredns:1.4.0\": rpc error: code = Unknown desc = failed to resolve image \"image-registry.canonical.com:5000/cdk/coredns/coredns:1.4.0\": no available registry endpoint: failed to do request: Head https://image-registry.canonical.com:5000/v2/cdk/coredns/coredns/manifests/1.4.0: dial tcp 162.213.33.199:5000: i/o timeout",
            "message": "Failed create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image \"k8s.gcr.io/pause:3.1\": failed to pull image \"k8s.gcr.io/pause:3.1\": failed to resolve image \"k8s.gcr.io/pause:3.1\": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: dial tcp 64.233.167.82:443: i/o timeout",
            "message": "Failed to pull image \"image-registry.canonical.com:5000/cdk/coredns/coredns:1.4.0\": rpc error: code = Unknown desc = failed to resolve image \"image-registry.canonical.com:5000/cdk/coredns/coredns:1.4.0\": no available registry endpoint: failed to do request: Head https://image-registry.canonical.com:5000/v2/cdk/coredns/coredns/manifests/1.4.0: dial tcp 162.213.33.199:5000: i/o timeout",
            "message": "Failed create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image \"k8s.gcr.io/pause:3.1\": failed to pull image \"k8s.gcr.io/pause:3.1\": failed to resolve image \"k8s.gcr.io/pause:3.1\": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: dial tcp 64.233.167.82:443: i/o timeout",
            "message": "Failed to pull image \"image-registry.canonical.com:5000/cdk/heapster-amd64:v1.6.0-beta.1\": rpc error: code = Unknown desc = failed to resolve image \"image-registry.canonical.com:5000/cdk/heapster-amd64:v1.6.0-beta.1\": no available registry endpoint: failed to do request: Head https://image-registry.canonical.com:5000/v2/cdk/heapster-amd64/manifests/v1.6.0-beta.1: dial tcp 162.213.33.199:5000: i/o timeout",
            "message": "Failed to pull image \"image-registry.canonical.com:5000/cdk/heapster-amd64:v1.6.0-beta.1\": rpc error: code = Unknown desc = failed to resolve image \"image-registry.canonical.com:5000/cdk/heapster-amd64:v1.6.0-beta.1\": no available registry endpoint: failed to do request: Head https://image-registry.canonical.com:5000/v2/cdk/heapster-amd64/manifests/v1.6.0-beta.1: dial tcp 162.213.33.199:5000: i/o timeout",
            "message": "Failed to pull image \"image-registry.canonical.com:5000/cdk/heapster-amd64:v1.6.0-beta.1\": rpc error: code = Unknown desc = failed to resolve image \"image-registry.canonical.com:5000/cdk/heapster-amd64:v1.6.0-beta.1\": no available registry endpoint: failed to do request: Head https://image-registry.canonical.com:5000/v2/cdk/heapster-amd64/manifests/v1.6.0-beta.1: dial tcp 162.213.33.199:5000: i/o timeout",
            "message": "Failed to pull image \"image-registry.canonical.com:5000/cdk/kubernetes-dashboard-amd64:v1.10.1\": rpc error: code = Unknown desc = failed to resolve image \"image-registry.canonical.com:5000/cdk/kubernetes-dashboard-amd64:v1.10.1\": no available registry endpoint: failed to do request: Head https://image-registry.canonical.com:5000/v2/cdk/kubernetes-dashboard-amd64/manifests/v1.10.1: dial tcp 162.213.33.199:5000: i/o timeout",
            "message": "Failed to pull image \"image-registry.canonical.com:5000/cdk/kubernetes-dashboard-amd64:v1.10.1\": rpc error: code = Unknown desc = failed to resolve image \"image-registry.canonical.com:5000/cdk/kubernetes-dashboard-amd64:v1.10.1\": no available registry endpoint: failed to do request: Head https://image-registry.canonical.com:5000/v2/cdk/kubernetes-dashboard-amd64/manifests/v1.10.1: dial tcp 162.213.33.199:5000: i/o timeout",
            "message": "Failed to pull image \"image-registry.canonical.com:5000/cdk/metrics-server-amd64:v0.3.3\": rpc error: code = Unknown desc = failed to resolve image \"image-registry.canonical.com:5000/cdk/metrics-server-amd64:v0.3.3\": no available registry endpoint: failed to do request: Head https://image-registry.canonical.com:5000/v2/cdk/metrics-server-amd64/manifests/v0.3.3: dial tcp 162.213.33.199:5000: i/o timeout",
            "message": "Failed to pull image \"image-registry.canonical.com:5000/cdk/metrics-server-amd64:v0.3.3\": rpc error: code = Unknown desc = failed to resolve image \"image-registry.canonical.com:5000/cdk/metrics-server-amd64:v0.3.3\": no available registry endpoint: failed to do request: Head https://image-registry.canonical.com:5000/v2/cdk/metrics-server-amd64/manifests/v0.3.3: dial tcp 162.213.33.199:5000: i/o timeout",
            "message": "Failed create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image \"k8s.gcr.io/pause:3.1\": failed to pull image \"k8s.gcr.io/pause:3.1\": failed to resolve image \"k8s.gcr.io/pause:3.1\": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: dial tcp 64.233.167.82:443: i/o timeout",
            "message": "Failed to pull image \"image-registry.canonical.com:5000/cdk/heapster-influxdb-amd64:v1.3.3\": rpc error: code = Unknown desc = failed to resolve image \"image-registry.canonical.com:5000/cdk/heapster-influxdb-amd64:v1.3.3\": no available registry endpoint: failed to do request: Head https://image-registry.canonical.com:5000/v2/cdk/heapster-influxdb-amd64/manifests/v1.3.3: dial tcp 162.213.33.199:5000: i/o timeout"
```

**Comment by parsifallo** [comment]
Manual way with juju:
`juju deploy charmed-kubernetes` <- Same error
`juju deploy charmed-kubernetes-124` <- works without a problem
