### ISSUE TITLE
Openstack NovaLXD Ubuntu 18.04 localhost multiple hook failed: "install"

### ISSUE THREAD

**Issue by haferman** [conjure-up/conjure-up#1621]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [no] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [no] Is conjure-up running inside a virtual machine?
- [yes] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju /snap/bin/juju
juju version 2.6.5-bionic-amd64

which conjure-up /snap/bin/conjure-up
conjure-up --version conjure-up 2.6.8

which lxc /snap/bin/lxc
/snap/bin/lxc config show
config:
  core.https_address: '[::]'

/snap/bin/lxc version
Client version: 3.16
Server version: 3.16

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"

```

Please attach tarball of **~/.cache/conjure-up**:
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/3533052/conjure-up.tar.gz)
```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.
sosreport (version 3.6)

no valid plugins were enabled

## What Spell was Selected?
openstack with novaLXD

### MAAS Users
Which version of MAAS?   N/A

## Commands ran

Please outline what commands were run to install and execute conjure-up:
conjure-up
Select openstack with novaLXD
+
localhost
+
Options as listed at https://ubuntu.com/openstack/install#workstation-deployment

## Additional Information
Clues in the conjure-up.log:

2019-08-23 05:44:04,298 [ERROR] conjure-up/openstack-novalxd - juju.py:744 - DEBUG:root:ceph-osd/0 workload status is waiting since 2019-08-23 05:42:37Z
DEBUG:root:ceph-osd/1 workload status is maintenance since 2019-08-23 05:43:33Z
DEBUG:root:ceph-osd/2 workload status is maintenance since 2019-08-23 05:43:38Z
DEBUG:root:ceph-radosgw/0 workload status is waiting since 2019-08-23 05:43:08Z
DEBUG:root:glance/0 workload status is waiting since 2019-08-23 05:43:10Z
DEBUG:root:keystone/0 workload status is waiting since 2019-08-23 05:43:12Z
DEBUG:root:mysql/0 workload status is waiting since 2019-08-23 05:43:14Z
DEBUG:root:neutron-api/0 workload status is waiting since 2019-08-23 05:43:17Z
DEBUG:root:neutron-gateway/0 workload status is error since 2019-08-23 05:44:02Z
ERROR:root:neutron-gateway/0 failed: workload status is error
2019-08-23 05:44:04,300 [DEBUG] conjure-up/openstack-novalxd - events.py:52 - Setting Error at conjureup/events.py:149
2019-08-23 05:44:04,301 [ERROR] conjure-up/openstack-novalxd - events.py:161 - Unhandled exception in <Task finished coro=<DeployController._wait_for_applications() done, defined at /snap/conjure-up/1055/lib/python3.6/site-packages/conjureup/controllers/juju/deploy/gui.py:81> exception=DeploymentFailure('Some applications failed to start successfully.',)>
Traceback (most recent call last):
  File "/snap/conjure-up/1055/lib/python3.6/site-packages/conjureup/controllers/juju/deploy/gui.py", line 82, in _wait_for_applications
    await common.wait_for_applications(view.set_footer)
  File "/snap/conjure-up/1055/lib/python3.6/site-packages/conjureup/controllers/juju/deploy/common.py", line 50, in wait_for_applications
    await juju.wait_for_deployment()
  File "/snap/conjure-up/1055/lib/python3.6/site-packages/conjureup/juju.py", line 746, in wait_for_deployment
    "Some applications failed to start successfully.")
conjureup.errors.DeploymentFailure: Some applications failed to start successfully.
2019-08-23 05:44:04,332 [DEBUG] conjure-up/openstack-novalxd - __init__.py:27 - Showing dialog for exception: Some applications failed to start successfully.

**Comment by haferman** [comment]
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/3533050/conjure-up.tar.gz)

**Comment by haferman** [comment]
juju status:
<img width="1136" alt="Screen Shot 2019-08-22 at 11 17 47 PM" src="https://user-images.githubusercontent.com/15824156/63570774-1d793f00-c533-11e9-9e3a-1a2e069791e5.png">

**Comment by haferman** [comment]
Closing: Nova-LXD is EOL as of 19.10 release.
