### ISSUE TITLE
 Unable to bootstrap (cloud type: maas)

### ISSUE THREAD

**Issue by iagalmeida** [conjure-up/conjure-up#1635]
## Report

2019-10-10 13:48:40,814 [DEBUG] conjure-up/openstack-base - events.py:52 - Awaiting Bootstrapped at conjureup/controllers/juju/bootstrap/gui.py:43
2019-10-10 13:48:46,344 [ERROR] conjure-up/openstack-base - common.py:60 - Error bootstrapping controller: ['Creating Juju controller "conjure-up-cloud-maas-554-d8b" on cloud-maas-554', 'Looking for packaged Juju agent version 2.6.9 for amd64', 'Launching controller instance(s) on cloud-maas-554...', 'ERROR failed to bootstrap model: cannot start bootstrap instance in availability zone "default": failed to acquire node: No available machine matches constraints: [(\'agent_name\', [\'84f69046-44fd-4ea2-809d-d0c2d4236e5a\']), (\'mem\', [\'3584\']), (\'zone\', [\'default\'])] (resolved to "mem=3584.0 zone=default")']
2019-10-10 13:48:46,346 [DEBUG] conjure-up/openstack-base - events.py:52 - Setting Error at conjureup/events.py:149
2019-10-10 13:48:46,352 [ERROR] conjure-up/openstack-base - events.py:161 - Unhandled exception in <Task finished coro=<BaseBootstrapController.run() done, defined at /snap/conjure-up/1056/lib/python3.6/site-packages/conjureup/controllers/juju/bootstrap/common.py:15> exception=BootstrapError('Unable to bootstrap (cloud type: maas)',)>
Traceback (most recent call last):
  File "/snap/conjure-up/1056/lib/python3.6/site-packages/conjureup/controllers/juju/bootstrap/common.py", line 21, in run
    await self.do_bootstrap()
  File "/snap/conjure-up/1056/lib/python3.6/site-packages/conjureup/controllers/juju/bootstrap/common.py", line 65, in do_bootstrap
    app.provider.cloud_type))
conjureup.errors.BootstrapError: Unable to bootstrap (cloud type: maas)
2019-10-10 13:48:46,366 [DEBUG] conjure-up/openstack-base - __init__.py:27 - Showing dialog for exception: Unable to bootstrap (cloud type: maas)
2019-10-10 13:50:19,089 [DEBUG] conjure-up/openstack-base - events.py:52 - Setting Shutdown at conjureup/events.py:145
2019-10-10 13:50:19,090 [DEBUG] conjure-up/openstack-base - events.py:52 - Received Shutdown at conjureup/events.py:176
2019-10-10 13:50:19,091 [INFO] conjure-up/openstack-base - events.py:180 - Shutting down
2019-10-10 13:50:19,091 [INFO] conjure-up/openstack-base - app_config.py:192 - Storing conjure-up state
2019-10-10 13:50:19,101 [INFO] conjure-up/openstack-base - app_config.py:207 - State saved
2019-10-10 13:50:19,102 [DEBUG] conjure-up/openstack-base - events.py:200 - Cancelling pending task: <Task pending coro=<BootstrapController.wait() running at /snap/conjure-up/1056/lib/python3.6/site-packages/conjureup/controllers/juju/bootstrap/gui.py:43> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f93a33d52e8>()]>>

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
juju version

which conjure-up
conjure-up --version

which lxc
/snap/bin/lxc config show
/snap/bin/lxc version

cat /etc/lsb-release
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

**Comment by iagalmeida** [comment]
/snap/bin/juju
juju version
2.6.9-bionic-amd64

which conjure-up
/snap/bin/conjure-up
conjure-up --version
conjure-up 2.6.8

 which lxc
/usr/bin/lxc



DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"

What provider (aws, maas, localhost, etc)?   MAAS

MAAS version: 2.4.2 (7034-g2f5deb8b8-0ubuntu1)
