### ISSUE TITLE
[ERROR] conjure-up/openstack-novalxd - events.py:161

### ISSUE THREAD

**Issue by bvbek** [conjure-up/conjure-up#1636]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
juju version

which conjure-up
conjure-up --version

which lxc
/snap/bin/lxc config show
/snap/bin/lxc version

cat /etc/lsb-release
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

**Comment by bvbek** [comment]
[ERROR] conjure-up/openstack-novalxd - events.py:161 - Unhandled exception in <Task finished coro=<DeployController._wait_for_applications() done, defined at /snap/conjure-up/1056/lib/python3.6/site-packages/conjureup/controllers/juju/deploy/gui.py:81> exception=DeploymentFailure('Some applications failed to start successfully.',)>
Traceback (most recent call last):
  File "/snap/conjure-up/1056/lib/python3.6/site-packages/conjureup/controllers/juju/deploy/gui.py", line 82, in _wait_for_applications
    await common.wait_for_applications(view.set_footer)
  File "/snap/conjure-up/1056/lib/python3.6/site-packages/conjureup/controllers/juju/deploy/common.py", line 50, in wait_for_applications
    await juju.wait_for_deployment()
  File "/snap/conjure-up/1056/lib/python3.6/site-packages/conjureup/juju.py", line 746, in wait_for_deployment
    "Some applications failed to start successfully.")
conjureup.errors.DeploymentFailure: Some applications failed to start successfully.
2019-10-10 17:11:03,135 [DEBUG] conjure-up/openstack-novalxd - __init__.py:27 - Showing dialog for exception: Some applications failed to start successfully.
