### ISSUE TITLE
2.0.0.7-0~526~ubuntu16.04.1 does not start bootstraping

### ISSUE THREAD

**Issue by impfrost** [conjure-up/conjure-up#310]
```
baum@maas:~/.local/share/juju$ conjure-up openstack 
[info] Loading current openstack spells from Juju Charmstore, please wait.
Exception in ev.run():
Traceback (most recent call last):
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/share/conjure-up/conjureup/ui/views/deploystatus.py", line 29, in _refresh_nodes_on_main_thread
    status = model_status()
  File "/usr/share/conjure-up/conjureup/juju.py", line 34, in _decorator
    login()
  File "/usr/share/conjure-up/conjureup/juju.py", line 85, in login
    raise Exception("Tried to login with no current model set.")
Exception: Tried to login with no current model set.
```

```python-traceback
Traceback (most recent call last):
  File "/usr/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up==2.0.0.7', 'console_scripts', 'conjure-up')()
  File "/usr/share/conjure-up/conjureup/app.py", line 308, in main
    EventLoop.run()
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/share/conjure-up/conjureup/ui/views/deploystatus.py", line 29, in _refresh_nodes_on_main_thread
    status = model_status()
  File "/usr/share/conjure-up/conjureup/juju.py", line 34, in _decorator
    login()
  File "/usr/share/conjure-up/conjureup/juju.py", line 85, in login
    raise Exception("Tried to login with no current model set.")
Exception: Tried to login with no current model set.
```

i upgraded to this version because the xenial release was buggy and not deploying the nodes. now the landscape option is missing and it does not start at all.

**Comment by battlemidget** [comment]
The landscape option was removed until they become fully Juju/Maas 2.0 ready. For the current problem, could you run:

```
juju controllers
juju models
juju version
```

**Comment by impfrost** [comment]
sorry but i started clean because that was such a mess. currently I'm having other problems with conjure-up because now it doesnt support my proxies environment or has never i dont know. anyways now it fails with conjure-up openstack with a connection problem. i googled and found that i have to bootstrap config juju with proxy parameters..

after struggling with lxd because if you dont have configured that one nothing with juju works. this is what im getting.

```
baum@maas:~$ juju bootstrap conjure localhost --config apt-http-proxy=http://192.168.10.253:3128 --config apt-https-proxy=http://192.168.10.253:3128 --config no-proxy=10.14.162.1
Creating Juju controller "conjure" on localhost/localhost
Bootstrapping model "controller"
Starting new instance for initial controller
Launching instance
unable to get LXD image for ubuntu-xenial: Get https://cloud-images.ubuntu.com/releases//streams/v1/index.json: Unable to conneERROR failed to bootstrap model: cannot start bootstrap instance: unable to get LXD image for ubuntu-xenial: Get https://cloud-images.ubuntu.com/releases//streams/v1/index.json: Unable to connect to: cloud-images.ubuntu.com:443
```
 where should i go now and continue this neverending mess of buggy code?

**Comment by battlemidget** [comment]
You can try adding your proxy information to HTTP_PROXY HTTPS_PROXY, http_proxy, and https_proxy. You can also join #ubuntu-server on freenode for additional support

**Comment by mikemccracken** [comment]
I am closing this for lack of recent activity - please feel free to file a new issue in the future if you have further problems.
