### ISSUE TITLE
traceback in lxdsetup on snappy

### ISSUE THREAD

**Issue by mikemccracken** [conjure-up/conjure-up#346]
```python-traceback

Traceback (most recent call last):
  File "/snap/conjure-up/17/usr/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up==2.0.0.7', 'console_scripts', 'conjure-up')()
  File "/snap/conjure-up/17/usr/lib/python3/dist-packages/conjureup/app.py", line 234, in main
    EventLoop.run()
  File "/snap/conjure-up/17/usr/lib/python3/dist-packages/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/snap/conjure-up/17/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/snap/conjure-up/17/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/snap/conjure-up/17/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/snap/conjure-up/17/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/snap/conjure-up/17/usr/lib/python3/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/snap/conjure-up/17/usr/lib/python3/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/snap/conjure-up/17/usr/lib/python3/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/snap/conjure-up/17/usr/lib/python3/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/snap/conjure-up/17/usr/lib/python3/dist-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/snap/conjure-up/17/usr/lib/python3/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/snap/conjure-up/17/usr/lib/python3/dist-packages/conjureup/ui/views/lxdsetup.py", line 91, in keypress
    return super().keypress(size, key)
  File "/snap/conjure-up/17/usr/lib/python3/dist-packages/urwid/decoration.py", line 836, in keypress
    return self._original_widget.keypress((maxcol,), key)
  File "/snap/conjure-up/17/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/snap/conjure-up/17/usr/lib/python3/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/snap/conjure-up/17/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/snap/conjure-up/17/usr/lib/python3/dist-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/snap/conjure-up/17/usr/lib/python3/dist-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/snap/conjure-up/17/usr/lib/python3/dist-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/snap/conjure-up/17/usr/lib/python3/dist-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/snap/conjure-up/17/usr/lib/python3/dist-packages/conjureup/ui/views/lxdsetup.py", line 146, in submit
    self.app.config['spell'])
  File "/snap/conjure-up/17/usr/lib/python3.5/os.py", line 583, in execl
    execv(file, args)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by battlemidget** [comment]
fixed now that we require the user to setup lxd beforehand
