### ISSUE TITLE
conjure-up <spell> tracebacks

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#371]
```
ubuntu@riddick:~$ conjure-up openstack-novalxd
found spell {'key': 'openstack-novalxd', 'name': 'OpenStack with NovaLXD', 'description': 'Quickly and reliably build an enterprise-scale cloud run on Ubuntu - the most popular operating system for OpenStack.\n'}
Traceback (most recent call last):
  File "/usr/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up==2.0.0.8', 'console_scripts', 'conjure-up')()
  File "/usr/lib/python3/dist-packages/conjureup/app.py", line 178, in main
    spell_name))
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'dict'
```

**Comment by MariosSytel** [comment]
Hi guys, 

I am still getting the error how can i fix this? 
----------
found spell {'key': 'openstack-novalxd', 'name': 'OpenStack with NovaLXD'}
Traceback (most recent call last):
  File "/snap/conjure-up/25/usr/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up==2.0.0.7', 'console_scripts', 'conjure-up')()
  File "/snap/conjure-up/25/usr/lib/python3/dist-packages/conjureup/app.py", line 178, in main
    spell_name))
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'dict'
----------
