### ISSUE TITLE
Exception: Tried to login with no current model set.

### ISSUE THREAD

**Issue by ObiterDicta** [conjure-up/conjure-up#399]
```
$ juju controllers
CONTROLLER  MODEL    USER         CLOUD/REGION
piglet*     default  admin@local  localhost/localhost
$ juju version
2.0-beta17-xenial-amd64
```

Fresh install of Ubuntu 16.04.01
Fresh install lxd zfs
Followed https://insights.ubuntu.com/2016/08/15/lunch-learn-with-openstack-containers/
Host is  2 x hex core, 64GB RAM server, 4 TB disks as zpool
Nothing else running on server, minimal Ubuntu server install
`$conjure-up openstack`
ncurses interface appears
Choose OpenStack with NovaLXD
Choose localhost
Move down to [Deploy all 15 Remaining Applications] 
Press Enter
installer hangs - no activity
$ top shows nothing is happening
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3/dist-packages/conjureup/ui/views/deploystatus.py", line 31, in _refresh_nodes_on_main_thread
    status = model_status()
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 39, in _decorator
    login()
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 90, in login
    raise Exception("Tried to login with no current model set.")
Exception: Tried to login with no current model set.
```
I have tried multiple times purging lxd and conjure-up, removing all trace I can find of them, doing a reinstall of both. No joy.

Yesterday got a bit farther, about 8 out of 15 applications were up, the rest hung (for hours). Today the ncurses interface seems to have changed a little, looks like there may have been an update.

**Comment by battlemidget** [comment]
Yea I pushed a new update out yesterday but it was primarily UX changes. I'll see if I can reproduce here.

**Comment by mikemccracken** [comment]
@ObiterDicta - are you still seeing this? I believe we were unable to reproduce this specific issue

**Comment by battlemidget** [comment]
Please re-open if problem persists
