### ISSUE TITLE
conjure-up package should depend on git-core

### ISSUE THREAD

**Issue by dustinkirkland** [conjure-up/conjure-up#460]
kirkland@x230:~⟫ conjure-up canonical-kubernetes
[info] No spells found, syncing from registry, please wait.
/bin/sh: 1: git: not found
Traceback (most recent call last):
  File "/usr/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up==2.0.1b2', 'console_scripts', 'conjure-up')()
  File "/usr/lib/python3/dist-packages/conjureup/app.py", line 202, in main
    spells_dir)
  File "/usr/lib/python3/dist-packages/conjureup/download.py", line 172, in download_or_sync_registry
    shell=True, check=True)
  File "/usr/lib/python3/dist-packages/conjureup/utils.py", line 32, in run
    return _run(cmd, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'git clone -q --depth 1 https://github.com/conjure-up/spells.git /home/kirkland/.cache/conjure-up-spells' returned non-zero exit status 127

**Comment by dustinkirkland** [comment]
rather, maybe the "git" package.

**Comment by mikemccracken** [comment]
@dustinkirkland was this on trusty?

**Comment by dustinkirkland** [comment]
No, xenial-proposed.  But I was running it on a freshly installed Ubuntu Desktop, as opposed to an Ubuntu Server (where git is seeded).
