### ISSUE TITLE
traceback in TUI conjureing to maas

### ISSUE THREAD

**Issue by mikemccracken** [conjure-up/conjure-up#466]
```python-traceback
conjure-up -d elk-stack maas 
[info] Summoning elk-stack to maas
[info] Bootstrapping Juju controller
Traceback (most recent call last):
  File "/home/ubuntu/conjure-up/conjure-dev/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up', 'console_scripts', 'conjure-up')()
  File "/home/ubuntu/conjure-up/conjureup/app.py", line 310, in main
    _start()
  File "/home/ubuntu/conjure-up/conjureup/app.py", line 119, in _start
    controllers.use('clouds').render()
  File "/home/ubuntu/conjure-up/conjureup/controllers/clouds/tui.py", line 51, in render
    self.finish()
  File "/home/ubuntu/conjure-up/conjureup/controllers/clouds/tui.py", line 29, in finish
    return controllers.use('newcloud').render(app.argv.cloud)
  File "/home/ubuntu/conjure-up/conjureup/controllers/newcloud/tui.py", line 77, in render
    self.do_post_bootstrap()
  File "/home/ubuntu/conjure-up/conjureup/controllers/newcloud/tui.py", line 24, in do_post_bootstrap
    app.env['JUJU_PROVIDERTYPE'] = model_info('default')['provider-type']
  File "/home/ubuntu/conjure-up/conjureup/juju.py", line 32, in _decorator
    login(force=True)
  File "/home/ubuntu/conjure-up/conjureup/juju.py", line 103, in login
    uuid = get_model(app.current_controller, app.current_model)['model-uuid']
  File "/home/ubuntu/conjure-up/conjureup/juju.py", line 548, in get_model
    models = get_models(controller)['models']
  File "/home/ubuntu/conjure-up/conjureup/juju.py", line 582, in get_models
    "Unable to list models: {}".format(sh.stderr.decode('utf8')))
LookupError: Unable to list models: error: controller edith not found

```

**Comment by battlemidget** [comment]
Hmm may need to sync with you; I couldn't reproduce this:

```
[adam:~/Projects/conjure-up] [conjure-dev] master ± conjure-up -d elk-stack maas
[warning] Unknown Cloud: maas, please choose from one of the following: devmaas, localhost, azure, azure-china, aws-gov, rackspace, joyent, cloudsigma, google, aws-china, aws
[adam:~/Projects/conjure-up] [conjure-dev] master 1 ± conjure-up -d elk-stack devmaas
[info] Summoning elk-stack to devmaas
[warning] You attempted to do an install against a cloud that requires credentials that could not be found.  If you wish to supply those credentials please run `juju add-credential devmaas`.
```

**Comment by mikemccracken** [comment]
not actually fixed by https://github.com/conjure-up/conjure-up/commit/5e6515e911de0630d6a93dbb395306d8c8f6018b

**Comment by battlemidget** [comment]
So I couldn't reproduce this with my maas cloud:

```
[adam:~/Projects/conjure-up] [conjure-dev] master+ ± conjure-up -d elk-stack devmaas
[info] Summoning elk-stack to devmaas
[info] Bootstrapping Juju controller
[info] Deploying elasticsearch... 
[info] elasticsearch: deployed, installing.
[info] Deploying kibana... 
[info] kibana: deployed, installing.
[info] Deploying logstash... 
[info] logstash: deployed, installing.
[info] Deploying zulu8... 
[info] zulu8: deployed, installing.
[info] Setting application relations
[info] Completed setting application relations
[info] Waiting for applications to start
```

**Comment by mikemccracken** [comment]
not reproducible by me either. was caused by a broken juju setup I had.
