### ISSUE TITLE
handle error if ipv6 is enabled and localhost was selected

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#495]
http://paste.ubuntu.com/23345012/

```
conjure-up/_unspecified_spell: [ERROR] conjure-up/_unspecified_spell: ERROR creating LXD client: /etc/default/lxd-bridge has IPv6 enabled.

Juju doesn't currently support IPv6.



IPv6 can be disabled by running:



       sudo dpkg-reconfigure -p medium lxd



and then bootstrap again.

conjure-up/_unspecified_spell: [ERROR] conjure-up/_unspecified_spell: Showing dialog for exception:
NoneType
conjure-up/_unspecified_spell: [ERROR] conjure-up/_unspecified_spell: Showing dialog for exception:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/conjureup/controllers/deploy/gui.py", line 30, in _pre_deploy_exec
    app.current_model)['provider-type']
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 32, in _decorator
    login(force=True)
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 102, in login
    account = get_account(app.current_controller)
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 525, in get_account
    return get_accounts().get(controller, {})
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 537, in get_accounts
    "Unable to find: {}".format(env))
Exception: Unable to find: /home/ubuntu/.local/share/juju/accounts.yaml
conjure-up/_unspecified_spell: [ERROR] conjure-up/_unspecified_spell: Showing dialog for exception:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 32, in _decorator
    login(force=True)
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 102, in login
    account = get_account(app.current_controller)
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 525, in get_account
    return get_accounts().get(controller, {})
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 537, in get_accounts
    "Unable to find: {}".format(env))
Exception: Unable to find: /home/ubuntu/.local/share/juju/accounts.yaml
conjure-up/_unspecified_spell: [ERROR] conjure-up/_unspecified_spell: Showing dialog for exception:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/conjureup/controllers/deploy/gui.py", line 30, in _pre_deploy_exec
    app.current_model)['provider-type']
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 32, in _decorator
    login(force=True)
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 102, in login
    account = get_account(app.current_controller)
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 525, in get_account
    return get_accounts().get(controller, {})
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 537, in get_accounts
    "Unable to find: {}".format(env))
Exception: Unable to find: /home/ubuntu/.local/share/juju/accounts.yaml
conjure-up/_unspecified_spell: [ERROR] conjure-up/_unspecified_spell: Showing dialog for exception:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 32, in _decorator
    login(force=True)
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 102, in login
    account = get_account(app.current_controller)
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 525, in get_account
    return get_accounts().get(controller, {})
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 537, in get_accounts
    "Unable to find: {}".format(env))
Exception: Unable to find: /home/ubuntu/.local/share/juju/accounts.yaml
```

**Comment by castrojo** [comment]
Can we bump the priority on this? Had a user hit this in IRC.

**Comment by battlemidget** [comment]
Yea I'll try to get this fixed asap
