### ISSUE TITLE
more lxd polish necessary

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#538]
Copied from: https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/167

So I decided to try out the instructions to install the canonical-kubernetes like mentioned here;
https://insights.ubuntu.com/2016/12/16/announcing-canonical-kubernetes-1-5-1/
specifically I tried
the link in the article mentioned to setup a local env;
https://github.com/castrojo/kubernetes.github.io/blob/ubuntu-lifecycle-revisions/docs/getting-started-guides/ubuntu/local.md

I found some minor issues;
So I'm a newb, but I trried this and ran into some problems, most of them minor, but I think it should be mentioned;

apt-add-repository is not available on a vanilla ubuntu server install. It can be installed if you are lazy to edit the sources yourself (as I am)
sudo apt-get install software-properties-common
before running the conjuring-up lxd needs to be configured
sudo lxd init
A reboot is neccessay after that, else the conjure-up will fail (I forgot to note down which error, but It had to do with default accounts)
also, I assume a core install is intentioned? I assume yes as it is a local install. Does it matter?
But after those steps, I still got;
conjure-up/kubernetes: [ERROR] conjure-up/kubernetes: Failure in deploy done: Error in one of the applications deployment
conjure-up/kubernetes: [ERROR] conjure-up/kubernetes: Showing dialog for exception:
Traceback (most recent call last):
File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/lib/python3/dist-packages/conjureup/controllers/deploystatus/common.py", line 40, in wait_for_applications
raise Exception(result['message'])
Exception: Error in one of the applications deployment
this turned out to be a simple harddisk full issue, 20Gb which VMware workstation setups as default is not enough on a vanilla ubuntu server install. I'm counting 13G being used including ubuntu. Also, I would guess the installer/script should check this before install.
As I said, all minor issues, but I'm hoping I am saving someone time with this. Should i update the documentation?

I'm running this in a ubuntu VM 16.01.1 with VMware workstation 12.5.

**Comment by battlemidget** [comment]
The majority of these issues have been fixed with the latest snap package of conjure-up. We have a bug opened for warning the user about harware requirement/resources needed so the last point here will be addressed in the near future.
