### ISSUE TITLE
traceback during machine placement

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#540]
Traceback when selecting a machine in architecture view:

```
Traceback (most recent call last):
  File "/usr/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up==2.1.0', 'console_scripts', 'conjure-up')()
  File "/usr/lib/python3/dist-packages/conjureup/app.py", line 321, in main
    EventLoop.run()
  File "/usr/lib/python3/dist-packages/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3/dist-packages/conjureup/ui/views/app_architecture_view.py", line 68, in keypress
    rv = super().keypress(size, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 836, in keypress
    return self._original_widget.keypress((maxcol,), key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/lib/python3/dist-packages/conjureup/ui/widgets/juju_machine_widget.py", line 300, in show_pin_chooser
    self.controller.show_pin_chooser(self.juju_machine_id)
  File "/usr/lib/python3/dist-packages/conjureup/ui/views/app_architecture_view.py", line 207, in show_pin_chooser
    juju_machine_id, self.application, self)
  File "/usr/lib/python3/dist-packages/conjureup/ui/views/machine_pin_view.py", line 33, in __init__
    self.frame = Frame(body=self.build_widgets(),
  File "/usr/lib/python3/dist-packages/conjureup/ui/views/machine_pin_view.py", line 69, in build_widgets
    show_filter_box=True
  File "/usr/lib/python3/dist-packages/conjureup/ui/widgets/machines_list.py", line 83, in __init__
    self.update()
  File "/usr/lib/python3/dist-packages/conjureup/ui/widgets/machines_list.py", line 164, in update
    if not satisfies(m, self.constraints)[0]:
  File "/usr/lib/python3/dist-packages/conjureup/maas.py", line 459, in satisfies
    if kmap[k] == 'storage':
KeyError: KeyError('tags',)
```

Reproduce:

```
conjure-up -d
pick Ghost HA
click architecture on ghost, choose a machine
click achitecture on haproxy, attempt to choose a machine <failure>
```

**Comment by mikemccracken** [comment]
hey @battlemidget , I can't reproduce this on my end. Is this happening regularly?

I see in the code where if 'tags' was in the constraints for a machine in the bundle, it'd break the `satisfies` function, but that hasn't happened in my experience.  It's not set that way in the bundle in the spells repo, and you can't change that constraint key in the UI.

Is there any other context you can give about this? Thanks!

**Comment by battlemidget** [comment]
I'll reproduce with screenshots tonight probably, took a swap day today
