### ISSUE TITLE
Better JSON errors during processing scripts results

### ISSUE THREAD

**Issue by mikemccracken** [conjure-up/conjure-up#563]
```
Traceback (most recent call last):
  File                                            
                       "/home/ubuntu/.cache/conjure-up/kubernetes-core/steps/00_pre-deploy", line 42, in <module>
    error(profile_edit.stderr)
  File "/home/ubuntu/conjure-up/conjureup/hooklib/writer.py", line 43, in error
    \'isComplete\': False
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b"error: Failed to retrieve  profile=\'juju-ghost\'\\n" is not JSON serializable
```

**Comment by battlemidget** [comment]
Fixed with https://github.com/conjure-up/conjure-up/commit/1426def718fabc64ed52f5a37cad4515225bc56b
