### ISSUE TITLE
fails to deploy on s390x

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#592]
```
ubuntu@S2LP8:~$ uname -a
Linux S2LP8 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:05:09 UTC 2016 s390x s390x s390x GNU/Linux
ubuntu@S2LP8:~$ conjure-up openstack
Traceback (most recent call last):
  File "/usr/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up==2.0.0.8', 'console_scripts', 'conjure-up')()
  File "/usr/lib/python3/dist-packages/conjureup/app.py", line 163, in main
    app.spells_index = yaml.safe_load(fp.read())
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1970: ordinal not in range(128)
ubuntu@S2LP8:~$
```

**Comment by mikemccracken** [comment]
This is odd. I wonder if it's reproducible.
This might be a problem with connecting to github that wasn't properly as an error?
I'm guessing that the s390x is behind a firewall that doesn't reach github. It should time out and fail though.

**Comment by battlemidget** [comment]
https://bugs.launchpad.net/conjure-up/+bug/1621933
