### ISSUE TITLE
Crash when running conjure-down

### ISSUE THREAD

**Issue by castrojo** [conjure-up/conjure-up#644]
I have the conjure-snap installed with --classic, fired up a canonical-kubernetes with lxd, everything worked, then got this when tearing down.

```
conjure-down 
Exception in ev.run():
Traceback (most recent call last):
  File "/snap/conjure-up/37/lib/python3.5/site-packages/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/snap/conjure-up/37/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/snap/conjure-up/37/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/snap/conjure-up/37/lib/python3.5/site-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/snap/conjure-up/37/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/snap/conjure-up/37/lib/python3.5/site-packages/urwid/main_loop.py", line 164, in cb
    callback(self, user_data)
  File "/snap/conjure-up/37/lib/python3.5/site-packages/conjureup/destroy.py", line 49, in _start
    controllers.use('destroy').render()
  File "/snap/conjure-up/37/lib/python3.5/site-packages/conjureup/controllers/destroy/gui.py", line 29, in render
    cb=self.finish)
  File "/snap/conjure-up/37/lib/python3.5/site-packages/conjureup/ui/views/destroy.py", line 19, in __init__
    self.frame = Frame(body=self._build_widget(),
  File "/snap/conjure-up/37/lib/python3.5/site-packages/conjureup/ui/views/destroy.py", line 74, in _build_widget
    len(model['machines'].keys()),
KeyError: KeyError('machines',)
Traceback (most recent call last):
  File "/snap/conjure-up/37/bin/conjure-down", line 11, in <module>
    sys.exit(main())
  File "/snap/conjure-up/37/lib/python3.5/site-packages/conjureup/destroy.py", line 83, in main
    EventLoop.run()
  File "/snap/conjure-up/37/lib/python3.5/site-packages/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/snap/conjure-up/37/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/snap/conjure-up/37/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/snap/conjure-up/37/lib/python3.5/site-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/snap/conjure-up/37/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/snap/conjure-up/37/lib/python3.5/site-packages/urwid/main_loop.py", line 164, in cb
    callback(self, user_data)
  File "/snap/conjure-up/37/lib/python3.5/site-packages/conjureup/destroy.py", line 49, in _start
    controllers.use('destroy').render()
  File "/snap/conjure-up/37/lib/python3.5/site-packages/conjureup/controllers/destroy/gui.py", line 29, in render
    cb=self.finish)
  File "/snap/conjure-up/37/lib/python3.5/site-packages/conjureup/ui/views/destroy.py", line 19, in __init__
    self.frame = Frame(body=self._build_widget(),
  File "/snap/conjure-up/37/lib/python3.5/site-packages/conjureup/ui/views/destroy.py", line 74, in _build_widget
    len(model['machines'].keys()),
KeyError: KeyError('machines',)
```

**Comment by battlemidget** [comment]
Thanks! Well get this sorted today
