### ISSUE TITLE
Conjure-up openstack on Ubuntu 16.10 Crash

### ISSUE THREAD

**Issue by nobozo** [conjure-up/conjure-up#656]
For what it's worth, I just tried running 'conjure-up openstack' on a Ubuntu 16.10 system with 256GB of RAM and 32 cores. I choose the LXD option and got:

```
2017-02-07 16:43:59,767 conjure-up/openstack: [DEBUG] log.py:14 - conjure-up/openstack: Path is local filesystem, copying /snap/conj
ure-up/56/spells/openstack-novalxd to /home/jon.forrest/.cache/conjure-up/openstack-novalxd
2017-02-07 16:44:02,592 conjure-up/openstack: [DEBUG] log.py:14 - conjure-up/openstack: Running pre-deployment tasks.
2017-02-07 16:44:02,759 conjure-up/openstack: [ERROR] log.py:23 - conjure-up/openstack: Showing dialog for exception:
Traceback (most recent call last):
  File "/snap/conjure-up/56/lib/python3.6/site-packages/conjureup/controllers/deploy/gui.py", line 82, in _pre_deploy_done
    result = json.loads(future.result().stdout.decode())
  File "/snap/conjure-up/56/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/snap/conjure-up/56/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/snap/conjure-up/56/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by battlemidget** [comment]
Thank you for the report, I'll get a system spun up and try to reproduce.

**Comment by battlemidget** [comment]
Can you also pastebin your entire ~/.cache/conjure-up/conjure-up.log?

**Comment by nobozo** [comment]
That's what I posted above.

**Comment by battlemidget** [comment]
So I just did a fresh install of 16.10 and couldnt reproduce this. Were you deploying to an existing controller?

```
2017-02-08 04:06:37,441 conjure-up/openstack: [DEBUG] log.py:14 - conjure-up/openstack: Path is local filesystem, copying /snap/conjure-up/57/spells/openstack-novalxd to /home/ubuntu/.cache/conjure-up/openstack-novalxd
2017-02-08 04:06:42,217 conjure-up/openstack: [DEBUG] log.py:14 - conjure-up/openstack: Found an IPv4 address, assuming LXD is configured.
2017-02-08 04:06:42,218 conjure-up/openstack: [DEBUG] log.py:14 - conjure-up/openstack: Performing bootstrap: conjure-up-localhost-2dd localhost
2017-02-08 04:06:42,219 conjure-up/openstack: [DEBUG] log.py:14 - conjure-up/openstack: bootstrap cmd: juju bootstrap localhost conjure-up-localhost-2dd --config image-stream=daily --config enable-os-upgrade=false --default-model conjure-up-openstack-novalxd-c3b --bootstrap-series=xenial --debug
2017-02-08 04:06:44,470 conjure-up/openstack: [DEBUG] log.py:14 - conjure-up/openstack: Rendering bootstrap wait
```

You could try the edge version to see if that makes a difference:

```
sudo snap refresh conjure-up --edge
```

But I don't believe there were major lxd changes between revs.

**Comment by nobozo** [comment]
It's possible there was an existing controller, but since I don't really know what a controller is yet, I can't be sure. (I'm trying to learn OpenStack). I've tried several ways of installing it with conjure-up but they've both failed, although in different ways.  

I'll be happy to try your suggestion tomorrow.

**Comment by battlemidget** [comment]
You can also run:

```
conjure-down
```

And destroy any existing deployments and attempt to re-deploy. Im EST and am in https://rocket.ubuntu.com/channel/conjure-up please drop by tomorrow so I can help more.

**Comment by nobozo** [comment]
For the record, for some reason reinstalling snap core solved this.

**Comment by battlemidget** [comment]
Thanks!
