### ISSUE TITLE
conjure-up for openstack lxd fails: "No controllers registered."

### ISSUE THREAD

**Issue by sabaini** [conjure-up/conjure-up#659]
After running "snap run conjure-up openstack" and choosing NovaLXD on localhost, I'm getting an exception:

```
exception calling callback for <Future at 0x7f9beda1c780 state=finished raised LookupError>
Traceback (most recent call last):
  File "/snap/conjure-up/56/usr/lib/python3.6/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/snap/conjure-up/56/lib/python3.6/site-packages/conjureup/controllers/deploy/gui.py", line 90, in _pre_deploy_done
    future.result())))
  File "/snap/conjure-up/56/usr/lib/python3.6/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/snap/conjure-up/56/usr/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/snap/conjure-up/56/lib/python3.6/site-packages/conjureup/controllers/deploy/gui.py", line 82, in _pre_deploy_done
    result = json.loads(future.result().stdout.decode())
  File "/snap/conjure-up/56/usr/lib/python3.6/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/snap/conjure-up/56/usr/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/snap/conjure-up/56/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/snap/conjure-up/56/lib/python3.6/site-packages/conjureup/controllers/deploy/gui.py", line 59, in _pre_deploy_exec
    app.current_model)['provider-type']
  File "/snap/conjure-up/56/lib/python3.6/site-packages/conjureup/juju.py", line 28, in _decorator
    login(force=True)
  File "/snap/conjure-up/56/lib/python3.6/site-packages/conjureup/juju.py", line 119, in login
    uuid = get_model(app.current_controller, app.current_model)['model-uuid']
  File "/snap/conjure-up/56/lib/python3.6/site-packages/conjureup/juju.py", line 618, in get_model
    models = get_models(controller)['models']
  File "/snap/conjure-up/56/lib/python3.6/site-packages/conjureup/juju.py", line 676, in get_models
    "Unable to list models: {}".format(sh.stderr.decode('utf8')))
LookupError: Unable to list models: error: No controllers registered.

Please either create a new controller using "juju bootstrap" or connect to
another controller that you have been given access to using "juju register".
```

**Comment by battlemidget** [comment]
Can you pastebin your `~/.cache/conjure-up/conjure-up.log`?

**Comment by battlemidget** [comment]
Also you shouldn't need to do `snap run conjure-up`, maybe since you upgraded and installed snapd you need to logout and back in in order to have `/snap/bin` added to your $PATH.

**Comment by sabaini** [comment]
Ok so the snapd pkg places /snap/bin on bash's path via /etc/profile.d
I'm using zsh there however, which doesn't read /etc/profile (probably wise). There's a bug lp:1640514 about this

**Comment by sabaini** [comment]
FWIW I've executed

> $ bash -l # to get /snap/bin on $PATH
> $ conjure-up 

And have pretty similar results. Attaching logfile minus ssh pubkey

[conjure-up.log.gz](https://github.com/conjure-up/conjure-up/files/761895/conjure-up.log.gz)

**Comment by battlemidget** [comment]
```
21:28:37 ERROR cmd supercommand.go:458 enabling HTTPS listener: cannot listen on https socket: listen tcp [::]:8443: bind: address already in use
```

Ah try `sudo apt-get remove lxd` and re-run conjure-up. There are still a few conflicts here with deb installed LXD and snap installed LXD

**Comment by battlemidget** [comment]
Fixed in https://github.com/conjure-up/conjure-up/commit/816725593c360f1d32e64465f178d6a9bbb8dd7c

**Comment by mingderwang** [comment]
I think, I have to follow this step
To configure your system to better support LXD containers, please see: https://github.com/lxc/lxd/blob/master/doc/production-setup.md
