### ISSUE TITLE
conjure-up openstack crash

### ISSUE THREAD

**Issue by nobozo** [conjure-up/conjure-up#671]
(Ubuntu 16.10, 256GB RAM, 2TB SSD, 32 cores)

I ran 'conjure-up openstack' which hit the "Running step: Glance" step and ran for a while. All of a sudden I got the stack trace below. I'm running 'top' in another window and it looks like the install is still going on. I've added a copy of what top shows below the stack trace.

Exception in ev.run():
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'
Traceback (most recent call last):
  File "/usr/bin/conjure-up", line 11, in <module>
    load_entry_point('conjure-up==2.1.0', 'console_scripts', 'conjure-up')()
  File "/usr/lib/python3/dist-packages/conjureup/app.py", line 321, in main
    EventLoop.run()
  File "/usr/lib/python3/dist-packages/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'

27733 root      20   0  133960  58976   9384 S  79.4  0.0   0:02.66 quantum-network
28214 jonf      20   0  117156  63964   6720 S  37.5  0.0   0:01.22 neutron
44895 apt-cac+  20   0  353476 104516   7592 S  16.9  0.0   0:02.30 apache2
19570 ntp       20   0  328108 124436   4348 S  16.0  0.0   0:00.55 neutron-server
23389 ntp       20   0 5371056 398004   4028 S  14.8  0.2   2:00.76 beam.smp
44957 apt-cac+  20   0  339956  69700   7380 S  13.2  0.0   0:03.40 apache2
24703 root      20   0  208060  72056  11556 S   9.8  0.0   0:04.22 identity-servic
44924 apt-cac+  20   0  354252 106072   7564 S   7.7  0.0   0:03.69 apache2

**Comment by battlemidget** [comment]
Your paths `/usr/lib/python3/dist-packages/` indicate that you aren't using the snapped version of conjure-up?

**Comment by nobozo** [comment]
On 2/9/2017 4:16 PM, Adam Stokes wrote:
> Your paths |/usr/lib/python3/dist-packages/| indicate that you aren't
> using the snapped version of conjure-up?

I'm following the instructions on

https://insights.ubuntu.com/2016/08/15/lunch-learn-with-openstack-containers/

which say to install conjure-up using

sudo apt install conjure-up

which I did. Is this the snapped version of conjure-up?
I see the instructions on your web page say to run

snap install conjure-up --classic --beta
If I do that, will that be able to continue with what's already
been installed, or should I run conjure-down and then start all
over?

Jon

**Comment by battlemidget** [comment]
So we have a bug that we're going to be working on allowing you to run conjure-up against an existing deployment but that's not quite ready yet. So yes to answer your question you'll want to do:

```
conjure-down
sudo apt-get remove conjure-up
sudo apt-get remove juju
sudo snap install conjure-up --classic --beta
```

We provide a newer version of juju in the snap.

That bug for the next deploy is https://github.com/conjure-up/conjure-up/issues/624

**Comment by nobozo** [comment]
Running conjure-down also results in a stack trace. This appears to happen right after deletion is finish.

$ conjure-down
Exception in ev.run():
Traceback (most recent call last):
  File "/snap/conjure-up/61/lib/python3.6/site-packages/ubuntui/ev.py", line 82, in run
    cls.loop.run()
  File "/snap/conjure-up/61/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/snap/conjure-up/61/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/snap/conjure-up/61/lib/python3.6/site-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
TypeError: __init__() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "/snap/conjure-up/61/bin/conjure-down", line 11, in <module>
    sys.exit(main())
  File "/snap/conjure-up/61/lib/python3.6/site-packages/conjureup/destroy.py", line 83, in main
    EventLoop.run()
  File "/snap/conjure-up/61/lib/python3.6/site-packages/ubuntui/ev.py", line 82, in run
    cls.loop.run()
  File "/snap/conjure-up/61/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/snap/conjure-up/61/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/snap/conjure-up/61/lib/python3.6/site-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
TypeError: __init__() missing 1 required positional argument: 'response'

**Comment by nobozo** [comment]
Running the steps you suggested above resulted in

cat conjure-up.log
2017-02-09 19:55:51,871 [DEBUG] log.py:14 - conjure-up/openstack: Path is local filesystem, copying /snap/conjure-up/60/spells/openstack-novalxd to /home/jon.forrest/.cache/conjure-up/openstack-novalxd
2017-02-09 19:55:57,266 [DEBUG] log.py:14 - conjure-up/openstack: Running pre-deployment tasks.
2017-02-09 19:55:57,444 [ERROR] log.py:23 - conjure-up/openstack: Showing dialog for exception:
Traceback (most recent call last):
  File "/snap/conjure-up/60/lib/python3.6/site-packages/conjureup/controllers/deploy/gui.py", line 82, in _pre_deploy_done
    result = json.loads(future.result().stdout.decode())
  File "/snap/conjure-up/60/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/snap/conjure-up/60/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/snap/conjure-up/60/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by battlemidget** [comment]
Can you provide the output of 

```
juju controllers
```

**Comment by nobozo** [comment]
$ juju controllers
Use --refresh flag with this command to see the latest information.

Controller  Model                             User   Access     Cloud/Region         Models  Machines    HA  Version
zebra*      conjure-up-openstack-novalxd-fd2  admin  superuser  localhost/localhost       2         1  none  2.1-beta5


Using --refresh gave the same output.

**Comment by battlemidget** [comment]
Lets clean this out:

```
juju kill-controller zebra
rm -rf ~/.local/share/juju
```

If there are any LXD containers still running lets remove those:

```
lxc list
lxc delete --force <juju-abcde-0>
```

Make sure `which conjure-up` and `which juju` both point to `/snap/bin/conjure-up` and `/snap/bin/juju`.

From there re-run `conjure-up`

**Comment by nobozo** [comment]
juju was wrong:

% which juju
/usr/bin/juju

That was a link to something. I removed /usr/bin/juju and now 'which juju' points to /snap/bin/juju. I ran 'conjure-up openstack' and things started off OK, but then the installer crashed. Looking at the log I see a bunch of

2017-02-09 21:01:46,038 [ERROR] log.py:23 - conjure-up/openstack: Showing dialog for exception:
Traceback (most recent call last):
  File "/snap/conjure-up/60/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/snap/conjure-up/60/lib/python3.6/site-packages/conjureup/controllers/deploy/gui.py", line 257, in _do_ensure_machines
    self.ensure_machines_nonmaas(application, done_cb)
  File "/snap/conjure-up/60/lib/python3.6/site-packages/conjureup/controllers/deploy/gui.py", line 296, in ensure_machines_nonmaas
    result = f.result()
AttributeError: 'NoneType' object has no attribute 'result'


By the way, I really appreciate all your help.

**Comment by battlemidget** [comment]
Ah, whats the output of `snap list`? We've made some changes with how we're relying on LXD and I think you may have both LXD's installed. Do the following:

```
sudo snap remove lxd
sudo snap refresh conjure-up --edge
conjure-up
```

I'm still running tests against the edge channel and this will help me identify any other oddities with the snap.

**Comment by nobozo** [comment]
Now 'conjure-up openstack' hangs in the "Please select an existing controller" screen. I can't select the existing one ("conjure-up-localhost-db8") or move to "Create New".

**Comment by battlemidget** [comment]
@nobozo i think we've just got stale data laying around from the previous deb installation. Do this:

```
rm -rf .cache/conjure-up/conjure-up*
rm -rf .local/share/juju
conjure-up
```

**Comment by nobozo** [comment]
Some good progress. Now all the applications are ready and active, except for  nova-compute/0, which says "Incomplete relations: messaging, image". It's been this way for at least 15 minutes. Running 'ps aux | fgrep python | wc -l' shows that there are 535 python processes running. Is that normal?

**Comment by nobozo** [comment]
Good new! All the applications are now ready, but there are still 535 python processes.

One question - can I pause the Openstack environment so that none of it is running and then unpause it again?

**Comment by battlemidget** [comment]
So there are roughly 15 LXD instances running on your system, you would have to pause all 15 manually using the `lxc` related commands and then either reboot your system to bring them all back up(they are set to autostart on boot) or manually start the containers again.

**Comment by nobozo** [comment]
And more good news - I can connect to the dashboard. It's not real fast but this is a big accomplishment.
The one python process is still running, and there are 535 other python processes that don't appear to require any CPU time.

**Comment by battlemidget** [comment]
Yea openstack is a huge python project with a ton of moving parts. I'm not sure if the low to none CPU usage is a cause of them being inside LXD containers and may be skewing that utilization a bit.

But glad you got it all up and running! Can we close this out?

**Comment by nobozo** [comment]
I'm thinking of tearing down this install and then doing it again using the kvm option. I wonder if I'll hit the same problem with remnants of the previous install.

**Comment by battlemidget** [comment]
Thanks, in the coming week I'm going to have additional OpenStack spells completed which will cover both KVM and LXD
