### ISSUE TITLE
conjure-down 

### ISSUE THREAD

**Issue by mbruzek** [conjure-up/conjure-up#716]
- [ ] Is this problem already documented at http://conjure-up.io/docs/en/users/#_common_spell_problems - No
- [ ] Is conjure-up running inside a virtual machine? - No

Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available: 4 CPU 16GB RAM ~400GB available space.

What spell was selected?: canonical-kubernetes

What cloud provider was selected (this includes both MAAS and localhost)?: localhost

Please outline what commands were run to install and execute conjure-up: snap install conjure-up

Please post **~/.cache/conjure-up/conjure-up.log**
[conjure-down.log.zip](https://github.com/conjure-up/conjure-up/files/825957/conjure-down.log.zip)

Provide the output of the following commands:

```
$ which juju
/snap/bin/juju
$ which conjure-up
/snap/bin/conjure-up
$ which lxd
/usr/bin/lxd
$ juju vesion
ERROR unrecognized command: juju vesion
$ juju --version
2.2-alpha1-yakkety-amd64
$ conjure-up --version

Multiple LXD versions installed, please remove one before proceeding.

See http://conjure-up.io/docs/en/users/#a-note-for-lxd-users for more information.

$ lxd --version
2.10.1
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.10
DISTRIB_CODENAME=yakkety
DISTRIB_DESCRIPTION="Ubuntu 16.10"

```

**Summary of problem**: The command `conjure-down` failed on my system. Is this related to the 2 lxd packages on my system?

This is so weird. I am sure that I uninstalled the apt lxd package yesterday, but your checklist indicates that I have 2 installed.
```
$ dpkg -l | grep lxd
ii  lxd                                             2.10.1-0ubuntu1~ubuntu16.10.1~ppa1            amd6
4        Container hypervisor based on LXC - daemon
ii  lxd-client                                      2.10.1-0ubuntu1~ubuntu16.10.1~ppa1            amd6
4        Container hypervisor based on LXC - client
$ snap list
Name        Version  Rev   Developer  Notes
charm       2.2      11    charms     classic
conjure-up  2.2-dev  110   canonical  classic
core        16-2     1337  canonical  -
lxd         2.10.1   1463  canonical  -
```
I honestly don't know how I have 2 versions installed, the last time I conjured up a deployment (yesterday March 6) I apt purged lxd and lxd-client. @battlemidget asked me to snap install the lxd from --candidate. 

I use timestamps with my bash history:
```
 3054  2017-03-06 10:21:24 AM dpkg -l | grep lxd
 3055  2017-03-06 10:21:56 AM sudo apt-get purge lxd lxd-client
 3056  2017-03-06 10:22:17 AM sudo snap refresh lxd
 3057  2017-03-06 10:22:24 AM snap list
 3058  2017-03-06 10:22:35 AM sudo snap install lxd-client   # I didn't realize lxd-client was in the snap
 3059  2017-03-06 10:22:42 AM sudo snap install lxd-client --classic
 3060  2017-03-06 10:22:48 AM sudo snap install lxd-client --channel edge
 3075  2017-03-06 11:00:18 AM which lxd
 3078  2017-03-06 11:00:34 AM lxd version
 3101  2017-03-06 11:07:26 AM snap refresh lxd
 3102  2017-03-06 11:07:42 AM snap refresh lxd-client
 3103  2017-03-06 11:08:11 AM sudo snap refresh lxd --candidate
```
I have not performed an install of the apt package of lxd since then I have no idea how the lxd and lxd-client are apt-installed on my system now.

**Comment by battlemidget** [comment]
ah.. this is an issue with the configure hook in the snap install, lemme get a fix out

**Comment by mbruzek** [comment]
@battlemidget this error left the localhost controller running on my system. I am unable to destroy it using juju commands:

```
$ juju destroy-controller conjure-up-localhost-763
WARNING! This command will destroy the "conjure-up-localhost-763" controller.
This includes all machines, applications, data and other resources.

Continue? (y/N):y
ERROR getting controller environ: getting environ using bootstrap config from client store: Get https://10.168.36.1:8443/1.0: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "root@pandora")
```

Please advise. Should I run this command with root?

**Comment by battlemidget** [comment]
Try with just `juju kill-controller conjure-up-localhost-763`

**Comment by battlemidget** [comment]
Working on a fix for the first issue now

**Comment by mbruzek** [comment]
kill-controller does not work either:
```
$ juju kill-controller conjure-up-localhost-763
WARNING! This command will destroy the "conjure-up-localhost-763" controller.
This includes all machines, applications, data and other resources.

Continue? (y/N):y
ERROR getting controller environ: getting environ using bootstrap config from client store: Get https://10.168.36.1:8443/1.0: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "root@pandora")
```

**Comment by battlemidget** [comment]
You may have to delete the containers via `lxc delete`, sorry about that and thanks for finding this error :D

**Comment by battlemidget** [comment]
Ok, if you haven't gone through and deleted your containers I found where that certificate error was coming from.

In your `~/.local/share/juju/credentials.yaml` there is now a certificate craeted for 'localhost' or any type of cloud with the 'lxd' type. You'll want to remove those stanzas and then you should be able to remove those controllers like normal.

**Comment by mbruzek** [comment]
Hey @battlemidget I installed conjure-up from the beta channel (2.1.2 Rev 120) and tried to "conjure-down" today. The terminal appears to hang, and when I hit return I get a big stack trace:
```Exception in ev.run():
Traceback (most recent call last):
  File "/snap/conjure-up/120/lib/python3.6/site-packages/ubuntui/ev.py", line 82, in run
    cls.loop.run()
  File "/snap/conjure-up/120/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/snap/conjure-up/120/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/snap/conjure-up/120/lib/python3.6/site-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/snap/conjure-up/120/usr/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/snap/conjure-up/120/lib/python3.6/site-packages/urwid/main_loop.py", line 164, in cb
    callback(self, user_data)
  File "/snap/conjure-up/120/lib/python3.6/site-packages/conjureup/destroy.py", line 49, in _start
    controllers.use('destroy').render()
  File "/snap/conjure-up/120/lib/python3.6/site-packages/conjureup/controllers/destroy/gui.py", line 23, in render
    models_map[cname] = juju.get_models(cname)
  File "/snap/conjure-up/120/lib/python3.6/site-packages/conjureup/juju.py", line 685, in get_models
    "Unable to list models: {}".format(sh.stderr.decode('utf8')))
LookupError: Unable to list models: please enter password for mbruzek on jenkins-ci-google: 
ERROR cannot list models: invalid entity name or password

Traceback (most recent call last):
  File "/snap/conjure-up/120/bin/conjure-down", line 11, in <module>
    sys.exit(main())
  File "/snap/conjure-up/120/lib/python3.6/site-packages/conjureup/destroy.py", line 83, in main
    EventLoop.run()
  File "/snap/conjure-up/120/lib/python3.6/site-packages/ubuntui/ev.py", line 82, in run
    cls.loop.run()
  File "/snap/conjure-up/120/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/snap/conjure-up/120/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/snap/conjure-up/120/lib/python3.6/site-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/snap/conjure-up/120/usr/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/snap/conjure-up/120/lib/python3.6/site-packages/urwid/main_loop.py", line 164, in cb
    callback(self, user_data)
  File "/snap/conjure-up/120/lib/python3.6/site-packages/conjureup/destroy.py", line 49, in _start
    controllers.use('destroy').render()
  File "/snap/conjure-up/120/lib/python3.6/site-packages/conjureup/controllers/destroy/gui.py", line 23, in render
    models_map[cname] = juju.get_models(cname)
  File "/snap/conjure-up/120/lib/python3.6/site-packages/conjureup/juju.py", line 685, in get_models
    "Unable to list models: {}".format(sh.stderr.decode('utf8')))
LookupError: Unable to list models: please enter password for mbruzek on jenkins-ci-google: 
ERROR cannot list models: invalid entity name or password
```

I share a juju controller with someone and that one "jenkins-ci-google" and that one requires a password (not sure when or how to trigger that). I am guessing from this stack trace the conjure-down command does not anticipate the prompt for this controller password.

Please advise if you need any more information.

**Comment by mbruzek** [comment]
@battlemidget I can confirm that after I entered the password for the other controller, I was able to conjure-down the model that was deployed

**Comment by battlemidget** [comment]
So we need a way to prompt for a password?

**Comment by ladams00** [comment]
I'm posting to say I found this thread useful.  I too have been having trouble with conjure-down not removing the model.  The 'juju kill-controller <instance>' worked great.

**Comment by battlemidget** [comment]
This is something we'll try to address this cycle

**Comment by evgkarasev** [comment]
I'm posting to say I found this thread useful. I too have been having trouble with conjure-down not removing the controllers. And not 'juju kill-controller' neither 'lxc delete' are worked for me in this case.
After many tries I just removed the whole '~/.local/share/juju' directory and reinstalled the snaps.
