### ISSUE TITLE
Snap conjure-up fails to start

### ISSUE THREAD

**Issue by dpb1** [conjure-up/conjure-up#718]
Conjure up fails to start on xenial with snaps:

```
dpb@helo:~[0]$ snap install conjure-up --classic
conjure-up 2.1.1 from 'canonical' installed
dpb@helo:~[0]$ conjure-up
runtime/cgo: pthread_create failed: Resource temporarily unavailable
Traceback (most recent call last):
  File "/snap/conjure-up/107/bin/conjure-up", line 7, in <module>
    from conjureup.app import main
ImportError: No module named 'conjureup'

```

Looks like it's depending on a library not in the snap

**Comment by dpb1** [comment]
This is still present on the --stable, --beta and --edge version of the snap.  Near as I can tell, this library is not included in the snap at all.  Probably you are getting it from your local system when testing (since you are in --classic mode)??

```
conjure-up           2.1.2     133   canonical   classic
conjure-up           2.2-beta1  138   canonical   classic
```

**Comment by battlemidget** [comment]
Do you have an old version of conjure-up installed? Check your dpkg output

**Comment by battlemidget** [comment]
I can't reproduce this at all, can you provide me with some more information? `snap list; dpkg -l|grep conjure-up; dpkg -l|grep juju; which juju; which conjure-up`

**Comment by dpb1** [comment]
```
dpb@helo:trunk[0]$ snap list
Name                 Version    Rev   Developer   Notes
bundletester         0.9.4      x3                devmode
canonical-livepatch  7          21    canonical   -
conjure-up           2.2-beta1  138   canonical   classic
docker               1.11.2-9   56    docker-inc  -
emoj                 0.3.0      1     popey       -
hello-world-service  0.1        x1                -
termdown             1.12.0     3     dpb         -
tmate-esnow          1.8.10     3     esnow       -
ubuntu-core          16-2       1797  canonical   -
dpb@helo:trunk[0]$ dpkg -l |grep conjure-up
dpb@helo:trunk[0]$ dpkg -l |grep juju
ii  fake-juju                                            0.18.20170216-0~201702161432~ubuntu16.04.1                 amd64        A fake implementation of Juju using the dummy provider.
ii  juju                                                 1:2.1.1-0ubuntu1~16.04.1~juju1                             all          next generation service orchestration system
ii  juju-1.25                                            1.25.6-0ubuntu1.16.04.1                                    amd64        Juju is devops distilled - client
ii  juju-2.0                                             1:2.1.1-0ubuntu1~16.04.1~juju1                             amd64        Juju is devops distilled - client
ii  juju-core                                            1.25.6-0ubuntu1.16.04.1                                    all          transitional package for supporting multiple Juju versions
ii  juju-deployer                                        0.10.0~bzr210~60~ubuntu16.04.1                             amd64        A tool to deploy complex stacks of services using juju.
ii  juju-mongodb                                         2.4.10-0ubuntu6                                            amd64        MongoDB object/document-oriented database for Juju
ii  juju-quickstart                                      2.2.4+bzr147+ppa42~ubuntu15.10.1                           all          Easy configuration of Juju environments
ii  python-fakejuju                                      0.18.20170216-0~201702161432~ubuntu16.04.1                 all          Python bindings for managing fake-juju.
ii  python-jujubundlelib                                 0.5.2~ubuntu16.04.1~ppa1                                   all          A Python2 library for working with Juju bundles.
ii  python-jujuclient                                    0.53.3+bzr96+41~ubuntu16.04.1                              all          Python API client for juju-core
ii  python-txjuju                                        0.9.0a1-0~37~ubuntu16.04.1                                 amd64        A twisted-based Juju client.
ii  python3-jujuclient                                   0.53.3+bzr96+41~ubuntu16.04.1                              all          Python API client for Juju (Python 3)
dpb@helo:trunk[0]$ which conjure-up
/snap/bin/conjure-up
dpb@helo:trunk[0]$ conjure-up
Traceback (most recent call last):
  File "/snap/conjure-up/138/bin/conjure-up", line 7, in <module>
    from conjureup.app import main
ImportError: No module named 'conjureup'
```

**Comment by battlemidget** [comment]
Youre using an old core-image, you should have `core` rather than the previously named `ubuntu-core`.

**Comment by dpb1** [comment]
do you know how to fix that?

```
dpb@helo:current[0]$ snap remove ubuntu-core
error: cannot remove "ubuntu-core": snap "ubuntu-core" is not removable
dpb@helo:current[0]$ snap install core
error: cannot perform the following tasks:
- Mount snap "core" (1512) (cannot install core snap "core" when core snap "ubuntu-core" is already present)
```

**Comment by battlemidget** [comment]
Soon as you can get 'ubuntu-core' changed over to the latest 'core' snap image this will work.

**Comment by dpb1** [comment]
I have this filed.  I'll track the status there:

https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1674484
