### ISSUE TITLE
Conjure-up Openstack-novalxd fails to multiple errors

### ISSUE THREAD

**Issue by ekallberg** [conjure-up/conjure-up#726]
Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ x] Is this problem already documented at http://conjure-up.io/docs/en/users/#_common_spell_problems
- [ x] Is conjure-up running inside a virtual machine?

Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available:

xxxxxxx@ubuntu:~$ cat /proc/cpuinfo | grep processor | wc -l
12

xxxxxxx@ubuntu:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:          48292         248       45810           9        2233       47522
Swap:         49139           0       49139

xxxxxxx@ubuntu:~$ df -h
Filesystem                   Size  Used Avail Use% Mounted on
udev                         7.9G     0  7.9G   0% /dev
tmpfs                        1.6G  9.2M  1.6G   1% /run
/dev/mapper/ubuntu--vg-root  181G  2.0G  170G   2% /
tmpfs                        7.9G     0  7.9G   0% /dev/shm
tmpfs                        5.0M     0  5.0M   0% /run/lock
tmpfs                        7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/sda1                    472M  105M  344M  24% /boot
tmpfs                        1.6G     0  1.6G   0% /run/user/1000
/dev/loop0                    76M   76M     0 100% /snap/core/1337
/dev/loop1                    82M   82M     0 100% /snap/conjure-up/107
tmpfs                        100K     0  100K   0% /var/lib/lxd/shmounts
tmpfs                        100K     0  100K   0% /var/lib/lxd/devlxd

What spell was selected?:

Openstack NovaLXD

What cloud provider was selected (this includes both MAAS and localhost)?:

localhost

Please outline what commands were run to install and execute conjure-up:

sudo snap install conjure-up --classic
conjure-up

Please post **~/.cache/conjure-up/conjure-up.log**

2017-03-13 15:45:23,219 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: LXD version: 2.11, Juju version: 2.1.1-xenial-amd64
2017-03-13 15:45:25,622 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Path is local filesystem, copying /snap/conjure-up/107/spells/openstack-novalxd to /home/xxxxxxxx/.cache/conjure-up/openstack-novalxd
2017-03-13 15:45:29,361 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Found an IPv4 address, assuming LXD is configured.
2017-03-13 15:45:29,361 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Performing bootstrap: conjure-up-localhost-f73 localhost
2017-03-13 15:45:29,362 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: bootstrap cmd: juju bootstrap localhost conjure-up-localhost-f73 --config image-stream=daily --config enable-os-upgrade=false --default-model conjure-up-openstack-novalxd-cdf --bootstrap-series=xenial --debug
2017-03-13 15:46:41,506 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: handle bootstrap
2017-03-13 15:46:41,508 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Showing dialog for exception: Bootstrap killed by user: -15
2017-03-13 15:46:51,566 [DEBUG] log.py:14 - conjure-up/openstack: LXD version: 2.11, Juju version: 2.1.1-xenial-amd64
2017-03-13 15:46:56,056 [DEBUG] log.py:14 - conjure-up/openstack: Path is local filesystem, copying /snap/conjure-up/107/spells/openstack-novalxd to /home/xxxxxxxx/.cache/conjure-up/openstack-novalxd

Provide the output of the following commands:

```
which juju
which conjure-up
which lxd
juju version
conjure-up --version
lxd --version
cat /etc/lsb-release
```

xxxxxx@ubuntu:~$ snap version
snap    2.22.7
snapd   2.22.7
series  16
ubuntu  16.04
kernel  4.4.0-31-generic

xxxxxxx@ubuntu:~$ which juju
/snap/bin/juju

xxxxxxx@ubuntu:~$ which conjure-up
/snap/bin/conjure-up

xxxxxxx@ubuntu:~$ which lxd
/usr/bin/lxd

xxxxxxx@ubuntu:~$ juju version
2.1.1-xenial-amd64

xxxxxxx@ubuntu:~$ conjure-up --version
conjure-up 2.1.1

xxxxxxx@ubuntu:~$ lxd --version
2.11

xxxxxxx@ubuntu:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

Summary of problem:

Installation fails right after selecting Openstack NovaLXD and cloud provider "localhost"

Last week all was working still, today not anymore.

exception calling callback for <Future at 0x7f1450fe4a20 state=finished raised Exception>
Traceback (most recent call last):
  File "/snap/conjure-up/107/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/snap/conjure-up/107/lib/python3.6/site-packages/bundleplacer/charmstore_api.py", line 188, in _do_load
    charm_names_or_sources, url))
Exception: metadata loading failed: charms=['cs:xenial/ceph-mon', 'cs:xenial/ceph-osd', 'cs:xenial/ceph-radosgw', 'cs:xenial/glance', 'cs:xenial/keystone', 'cs:xenial/percona-cluster', 'cs:xenial/neutron-api', 'cs:xenial/neutron-gateway', 'cs:xenial/neutron-openvswitch', 'cs:xenial/nova-cloud-controller', 'cs:xenial/nova-compute', 'cs:xenial/ntp', 'cs:xenial/lxd', 'cs:xenial/openstack-dashboard', 'cs:xenial/rabbitmq-server'] url=https://api.jujucharms.com/v4/meta/any?include=charm-metadata&include=charm-config&id=cs:xenial/ceph-mon&id=cs:xenial/ceph-osd&id=cs:xenial/ceph-radosgw&id=cs:xenial/glance&id=cs:xenial/keystone&id=cs:xenial/percona-cluster&id=cs:xenial/neutron-api&id=cs:xenial/neutron-gateway&id=cs:xenial/neutron-openvswitch&id=cs:xenial/nova-cloud-controller&id=cs:xenial/nova-compute&id=cs:xenial/ntp&id=cs:xenial/lxd&id=cs:xenial/openstack-dashboard&id=cs:xenial/rabbitmq-server

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/conjure-up/107/usr/lib/python3.6/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/snap/conjure-up/107/lib/python3.6/site-packages/bundleplacer/async.py", line 43, in cb
    exc_callback(e)
  File "/snap/conjure-up/107/lib/python3.6/site-packages/bundleplacer/charmstore_api.py", line 305, in handle_search_error
    self.error_cb(e)
TypeError: 'NoneType' object is not callable

[error] Error deploying services: 'cs:xenial/ceph-mon'
Exception in worker
Traceback (most recent call last):
  File "/snap/conjure-up/107/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/snap/conjure-up/107/lib/python3.6/site-packages/conjureup/juju.py", line 29, in _decorator
    return f(*args, **kwargs)
  File "/snap/conjure-up/107/lib/python3.6/site-packages/conjureup/juju.py", line 446, in _deploy_async
    info = mc.get_charm_info(id_no_rev, lambda _: None)
  File "/snap/conjure-up/107/lib/python3.6/site-packages/bundleplacer/charmstore_api.py", line 257, in get_charm_info
    cb(self.charm_info[charm_name])
KeyError: 'cs:xenial/ceph-mon'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/conjure-up/107/usr/lib/python3.6/concurrent/futures/thread.py", line 66, in _worker
    work_item.run()
  File "/snap/conjure-up/107/usr/lib/python3.6/concurrent/futures/thread.py", line 57, in run
    self.future.set_exception(e)
  File "/snap/conjure-up/107/usr/lib/python3.6/concurrent/futures/_base.py", line 507, in set_exception
    self._invoke_callbacks()
  File "/snap/conjure-up/107/usr/lib/python3.6/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/snap/conjure-up/107/lib/python3.6/site-packages/conjureup/async.py", line 34, in cb
    exc_callback(e)
  File "/snap/conjure-up/107/lib/python3.6/site-packages/conjureup/controllers/deploy/tui.py", line 23, in __handle_exception
    sys.exit(1)
SystemExit: 1

This happens both on hardware and VMware virtual machine with latest version and updates of 16.04 Ubuntu.

Also with -beta and -edge versions

**Comment by battlemidget** [comment]
This is currently being addressed, something on charmstore side changed without notice.
