### ISSUE TITLE
Openstack fails to correctly deploy when network device is not eth0

### ISSUE THREAD

**Issue by canonical-cgregan** [conjure-up/conjure-up#728]
Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at http://conjure-up.io/docs/en/users/#_common_spell_problems
- [ ] Is conjure-up running inside a virtual machine?

Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available:

HP Gen9

What spell was selected?:

Openstack KVM

What cloud provider was selected (this includes both MAAS and localhost)?:

MAAS

Summary of problem:
Neutron gateway ran into trouble when ethernet was not eth1

2017-03-13 20:12:56 INFO juju-log Adding port eth1 to bridge br-ex
2017-03-13 20:12:56 INFO config-changed Cannot find device "eth1"
2017-03-13 20:12:56 INFO config-changed Traceback (most recent call last):
2017-03-13 20:12:56 INFO config-changed   File "/var/lib/juju/agents/unit-neutron-gateway-0/charm/hooks/config-changed", line 359, in <module>
2017-03-13 20:12:56 INFO config-changed     hooks.execute(sys.argv)
2017-03-13 20:12:56 INFO config-changed   File "/var/lib/juju/agents/unit-neutron-gateway-0/charm/hooks/charmhelpers/core/hookenv.py", line 731, in execute
2017-03-13 20:12:56 INFO config-changed     self._hooks[hook_name]()
2017-03-13 20:12:56 INFO config-changed   File "/var/lib/juju/agents/unit-neutron-gateway-0/charm/hooks/charmhelpers/contrib/openstack/utils.py", line 1864, in wrapped_f
2017-03-13 20:12:56 INFO config-changed     restart_functions)
2017-03-13 20:12:56 INFO config-changed   File "/var/lib/juju/agents/unit-neutron-gateway-0/charm/hooks/charmhelpers/core/host.py", line 655, in restart_on_change_helper
2017-03-13 20:12:56 INFO config-changed     r = lambda_f()
2017-03-13 20:12:56 INFO config-changed   File "/var/lib/juju/agents/unit-neutron-gateway-0/charm/hooks/charmhelpers/contrib/openstack/utils.py", line 1863, in <lambda>
2017-03-13 20:12:56 INFO config-changed     (lambda: f(*args, **kwargs)), restart_map, stopstart,
2017-03-13 20:12:56 INFO config-changed   File "/var/lib/juju/agents/unit-neutron-gateway-0/charm/hooks/charmhelpers/contrib/hardening/harden.py", line 79, in _harden_inner2
2017-03-13 20:12:56 INFO config-changed     return f(*args, **kwargs)
2017-03-13 20:12:56 INFO config-changed   File "/var/lib/juju/agents/unit-neutron-gateway-0/charm/hooks/config-changed", line 145, in config_changed
2017-03-13 20:12:56 INFO config-changed     configure_ovs()
2017-03-13 20:12:56 INFO config-changed   File "/var/lib/juju/agents/unit-neutron-gateway-0/charm/hooks/neutron_utils.py", line 856, in configure_ovs
2017-03-13 20:12:56 INFO config-changed     add_bridge_port(br, port, promisc=True)
2017-03-13 20:12:56 INFO config-changed   File "/var/lib/juju/agents/unit-neutron-gateway-0/charm/hooks/charmhelpers/contrib/network/ovs/__init__.py", line 47, in add_bridge_port
2017-03-13 20:12:56 INFO config-changed     subprocess.check_call(["ip", "link", "set", port, "up"])
2017-03-13 20:12:56 INFO config-changed   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
2017-03-13 20:12:56 INFO config-changed     raise CalledProcessError(retcode, cmd)
2017-03-13 20:12:56 INFO config-changed subprocess.CalledProcessError: Command '['ip', 'link', 'set', u'eth1', 'up']' returned non-zero exit status 1
2017-03-13 20:12:56 ERROR juju.worker.uniter.operation runhook.go:107 hook "config-changed" failed: exit status 1
2017-03-13 20:12:56 DEBUG juju.worker.uniter.operation executor.go:84 lock released
2017-03-13 20:12:56 INFO juju.worker.uniter resolver.go:100 awaiting error resolution for "config-changed" hook
2017-03-13 20:12:56 DEBUG juju.worker.uniter agent.go:17 [AGENT-STATUS] error: hook failed: "config-changed"

**Comment by battlemidget** [comment]
Is this a config option that can be set? I was under the impression you could do things like https://jujucharms.com/neutron-gateway/234#charm-config-data-port and https://jujucharms.com/neutron-gateway/234#charm-config-bridge-mappings to setup your network?

**Comment by canonical-cgregan** [comment]
I can look. My systems set all devices to Eno. Not sure you can pass device
names, only numbers.

**Comment by battlemidget** [comment]
Let me know, this readme seems to indicate you can do what you need:

```
Port Configuration

All network types (internal, external) are configured with bridge-mappings and
data-port and the flat-network-providers configuration option of the
neutron-api charm. Once deployed, you can configure the network specifics
using neutron net-create.

If the device name is not consistent between hosts, you can specify the same
bridge multiple times with MAC addresses instead of interface names. The charm
will loop through the list and configure the first matching interface.

Basic configuration of a single external network, typically used as floating IP
addresses combined with a GRE private network:

neutron-gateway:
    bridge-mappings:         physnet1:br-ex
    data-port:               br-ex:eth1
neutron-api:
    flat-network-providers:  physnet1

neutron net-create --provider:network_type flat \
    --provider:physical_network physnet1 --router:external=true \
    external
neutron router-gateway-set provider external
Alternative configuration with two networks, where the internal private
network is directly connected to the gateway with public IP addresses but a
floating IP address range is also offered.

neutron-gateway:
    bridge-mappings:         physnet1:br-data external:br-ex
    data-port:               br-data:eth1 br-ex:eth2
neutron-api:
    flat-network-providers:  physnet1 external
Alternative configuration with two external networks, one for public instance
addresses and one for floating IP addresses. Both networks are on the same
physical network connection (but they might be on different VLANs, that is
configured later using neutron net-create).

neutron-gateway:
    bridge-mappings:         physnet1:br-data
    data-port:               br-data:eth1
neutron-api:
    flat-network-providers:  physnet1

neutron net-create --provider:network_type vlan \
    --provider:segmentation_id 400 \
    --provider:physical_network physnet1 --shared external
neutron net-create --provider:network_type vlan \
    --provider:segmentation_id 401 \
    --provider:physical_network physnet1 --shared --router:external=true \
    floating
neutron router-gateway-set provider floating
This replaces the previous system of using ext-port, which always created a bridge
called br-ex for external networks which was used implicitly by external router
interfaces.
```

**Comment by battlemidget** [comment]
This should be overridable by either passing in a custom `bundle-custom.yaml` with the proper network device naming or making sure that in your maas kernel parameters you set `net.ifnames=0` to go back to the normal interface naming
