### ISSUE TITLE
conjure-up from edge r154 nonetype exception deploying landscape on maas

### ISSUE THREAD

**Issue by dpb1** [conjure-up/conjure-up#773]
conjure-up landscape, chose maas, input credentials, selected enter on everything, hit this error:

```
dpb@helo:~[0]$ conjure-up landscape
Exception in ev.run():
Traceback (most recent call last):
  File "/snap/conjure-up/154/lib/python3.6/site-packages/ubuntui/ev.py", line 82, in run
    cls.loop.run()
  File "/snap/conjure-up/154/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/snap/conjure-up/154/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/snap/conjure-up/154/lib/python3.6/site-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/snap/conjure-up/154/usr/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/snap/conjure-up/154/lib/python3.6/site-packages/conjureup/ui/views/deploystatus.py", line 31, in _refresh_nodes_on_main_thread
    status = model_status()
  File "/snap/conjure-up/154/lib/python3.6/site-packages/conjureup/juju.py", line 32, in _decorator
    login(force=True)
  File "/snap/conjure-up/154/lib/python3.6/site-packages/conjureup/juju.py", line 123, in login
    uuid = get_model(app.current_controller, app.current_model)['model-uuid']
  File "/snap/conjure-up/154/lib/python3.6/site-packages/conjureup/juju.py", line 751, in get_model
    models = get_models(controller)['models']
  File "/snap/conjure-up/154/lib/python3.6/site-packages/conjureup/juju.py", line 822, in get_models
    "Unable to list models: {}".format(sh.stderr.decode('utf8')))
LookupError: Unable to list models: error: controller conjure-up-maas-d87 not found

Traceback (most recent call last):
  File "/snap/conjure-up/154/bin/conjure-up", line 11, in <module>
    load_entry_point('conjure-up==2.2b1', 'console_scripts', 'conjure-up')()
  File "/snap/conjure-up/154/lib/python3.6/site-packages/conjureup/app.py", line 359, in main
    EventLoop.run()
  File "/snap/conjure-up/154/lib/python3.6/site-packages/ubuntui/ev.py", line 82, in run
    cls.loop.run()
  File "/snap/conjure-up/154/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/snap/conjure-up/154/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/snap/conjure-up/154/lib/python3.6/site-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/snap/conjure-up/154/usr/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/snap/conjure-up/154/lib/python3.6/site-packages/conjureup/ui/views/deploystatus.py", line 31, in _refresh_nodes_on_main_thread
    status = model_status()
  File "/snap/conjure-up/154/lib/python3.6/site-packages/conjureup/juju.py", line 32, in _decorator
    login(force=True)
  File "/snap/conjure-up/154/lib/python3.6/site-packages/conjureup/juju.py", line 123, in login
    uuid = get_model(app.current_controller, app.current_model)['model-uuid']
  File "/snap/conjure-up/154/lib/python3.6/site-packages/conjureup/juju.py", line 751, in get_model
    models = get_models(controller)['models']
  File "/snap/conjure-up/154/lib/python3.6/site-packages/conjureup/juju.py", line 822, in get_models
    "Unable to list models: {}".format(sh.stderr.decode('utf8')))
LookupError: Unable to list models: error: controller conjure-up-maas-d87 not found

exception calling callback for <Future at 0x7fc6d47367f0 state=finished returned NoneType>
Traceback (most recent call last):
  File "/snap/conjure-up/154/usr/lib/python3.6/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/snap/conjure-up/154/lib/python3.6/site-packages/conjureup/controllers/deploystatus/gui.py", line 29, in __wait_for_applications
    relations_done_future.result()
AttributeError: 'NoneType' object has no attribute 'result'
```

```
dpb@helo:~[0]$ snap list
Name                   Version    Rev   Developer  Notes
conjure-up             2.2-beta1  154   canonical  classic
core                   16-2       1441  canonical  -
documentation-builder  1.4.0      31    nottrobin  -
```

**Comment by battlemidget** [comment]
I think we should categorize these specific juju errors so we make sure that once migrated to libjuju we make sure these are solved, @johnsca what do you think?

**Comment by johnsca** [comment]
Maybe a "juju" tag?

**Comment by battlemidget** [comment]
We've finished migrating to libjuju, please re-open if this bug persists with conjure-up from the `edge` channel
