### ISSUE TITLE
maas deploy error in get_models

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#774]
```
Traceback (most recent call last):
  File "/home/ubuntu/conjure-up-modelpicker/conjure-dev/bin/conjure-up", line 11, in <module>
    load_entry_point('conjure-up', 'console_scripts', 'conjure-up')()
  File "/home/ubuntu/conjure-up-modelpicker/conjureup/app.py", line 359, in main
    EventLoop.run()
  File "/home/ubuntu/conjure-up-modelpicker/ubuntui/ev.py", line 82, in run
    cls.loop.run()
  File "/home/ubuntu/conjure-up-modelpicker/conjure-dev/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/ubuntu/conjure-up-modelpicker/conjure-dev/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/home/ubuntu/conjure-up-modelpicker/conjure-dev/lib/python3.5/site-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/ubuntu/conjure-up-modelpicker/conjureup/ui/views/deploystatus.py", line 31, in _refresh_nodes_on_main_thread
    status = model_status()
  File "/home/ubuntu/conjure-up-modelpicker/conjureup/juju.py", line 32, in _decorator
    login(force=True)
  File "/home/ubuntu/conjure-up-modelpicker/conjureup/juju.py", line 123, in login
    uuid = get_model(app.current_controller, app.current_model)['model-uuid']
  File "/home/ubuntu/conjure-up-modelpicker/conjureup/juju.py", line 751, in get_model
    models = get_models(controller)['models']
  File "/home/ubuntu/conjure-up-modelpicker/conjureup/juju.py", line 822, in get_models
    "Unable to list models: {}".format(sh.stderr.decode('utf8')))
LookupError: Unable to list models: error: controller conjure-up-maas-bc1 not found
```

**Comment by battlemidget** [comment]
https://github.com/conjure-up/conjure-up/commit/ab22ea79470eb86b6c74d8ecad37364b70bd62d0
