### ISSUE TITLE
on OSX conjure-up openstack throws traceback

### ISSUE THREAD

**Issue by mitechie** [conjure-up/conjure-up#779]
Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available:

mac air on OSX

What spell was selected?:

openstack with nova kvm

What cloud provider was selected (this includes both MAAS and localhost)?:

Provide the output of the following commands:

```
which juju
which conjure-up
which lxd
juju version
conjure-up --version
lxd --version
cat /etc/lsb-release
```

    % which juju                                                                                
    /usr/local/bin/juju
    % which conjure-up
    /usr/local/bin/conjure-up
    % juju --version
    2.2-beta1-elcapitan-amd64
    % conjure-up --version
    conjure-up 2.1.2

Summary of problem:

    Traceback (most recent call last):
      File "/usr/local/bin/conjure-up", line 11, in <module>
        load_entry_point('conjure-up==2.1.2', 'console_scripts', 'conjure-up')()
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/conjureup/app.py", line 358, in main
        EventLoop.run()
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/ubuntui/ev.py", line 82, in run
        cls.loop.run()
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
        self._run()
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
        self.event_loop.run()
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 1328, in run
        raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
      File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/events.py", line 127, in _run
        self._callback(*self._args)
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/urwid/raw_display.py", line 393, in <lambda>
        event_loop, callback, self.get_available_raw_input())
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/urwid/raw_display.py", line 493, in parse_input
        callback(processed, processed_codes)
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 403, in _update
        self.process_input(keys)
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/urwid/main_loop.py", line 503, in process_input
        k = self._topmost_widget.keypress(self.screen_size, k)
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/urwid/wimp.py", line 643, in keypress
        return self._current_widget.keypress(size, key)
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/urwid/container.py", line 1128, in keypress
        return self.body.keypress( (maxcol, remaining), key )
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/conjureup/ui/views/spellpicker.py", line 44, in keypress
        rv = super().keypress(size, key)
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/urwid/container.py", line 1128, in keypress
        return self.body.keypress( (maxcol, remaining), key )
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/urwid/decoration.py", line 621, in keypress
        return self._original_widget.keypress(maxvals, key)
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/urwid/decoration.py", line 836, in keypress
        return self._original_widget.keypress((maxcol,), key)
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/urwid/container.py", line 1587, in keypress
        key = self.focus.keypress(tsize, key)
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/urwid/wimp.py", line 535, in keypress
        self._emit('click')
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/urwid/widget.py", line 463, in _emit
        signals.emit_signal(self, name, self, *args)
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/urwid/signals.py", line 264, in emit
        result |= self._call_callback(callback, user_arg, user_args, args)
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/urwid/signals.py", line 294, in _call_callback
        return bool(callback(*args_to_pass))
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/conjureup/ui/views/spellpicker.py", line 128, in submit
        self.cb(result['key'])
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/conjureup/controllers/spellpicker/gui.py", line 24, in finish
        return controllers.use('controllerpicker').render()
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/conjureup/controllers/controllerpicker/gui.py", line 58, in render
        return controllers.use('clouds').render()
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/conjureup/controllers/clouds/gui.py", line 35, in render
        cb=self.finish)
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/conjureup/ui/views/cloud.py", line 24, in __init__
        self.frame = Frame(body=self._build_widget(),
      File "/usr/local/Cellar/conjure-up/2.1/libexec/lib/python3.6/site-packages/conjureup/ui/views/cloud.py", line 92, in _build_widget
        new_clouds.remove('localhost')
    KeyError: KeyError('localhost',)

**Comment by battlemidget** [comment]
Fixed with master
