### ISSUE TITLE
__init__() got an unexpected keyword argument 'default'

### ISSUE THREAD

**Issue by abiye1** [conjure-up/conjure-up#821]
MAAS: Version 2.1.3
Ubuntu 16.04
Name          Version  Rev   Developer  Notes
conjure-up  2.1.3     191    canonical  classic
core            16-2     1577  canonical

I get the following error when i run $ conjure-up --bootstrap-to Landscape.maas (Landscape.maas being the machine i have chosen for Landscape and is Listed on MAAS DNS)

 **__init__() got an unexpected keyword argument 'default'**

My logs:
```
2017-04-13 21:03:09,371 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: LXD version: 2.12, Juju version: 2.1.2-xenial-amd64
2017-04-13 21:03:16,589 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Path is local filesystem, copying /snap/conjure-up/191/spells/landscape t$
2017-04-13 21:03:16,596 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Pulling bundle for landscape-dense-maas from channel: stable
2017-04-13 21:06:28,788 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Performing bootstrap: conjure-up-maas-fc1 maas/10.3.1.100
2017-04-13 21:06:28,791 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: bootstrap cmd: juju bootstrap maas/10.3.1.100 conjure-up-maas-fc1 --confi$
2017-04-13 21:07:30,779 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Rendering bootstrap wait
2017-04-13 21:17:02,153 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: handle bootstrap
2017-04-13 21:17:03,236 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Checking for post bootstrap task: /home/john/.cache/conjure-up/landscape/$
2017-04-13 21:17:03,366 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: pre_deploy_done: {'message': 'No pre deploy necessary', 'returnCode': 0, $
2017-04-13 21:17:03,367 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: AddMachines: [{'series': 'xenial', 'constraints': {}, 'jobs': ['JobHostUn$
2017-04-13 21:17:30,863 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: AddMachines returned {'machines': [{'machine': '0'}]}
2017-04-13 21:17:30,868 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Adding Charm cs:xenial/haproxy-41
2017-04-13 21:17:34,847 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: AddCharm returned {}
2017-04-13 21:17:34,967 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Resources for charm id 'cs:xenial/haproxy-41': []
2017-04-13 21:17:34,970 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Deploying <Service haproxy>: {'applications': [{'charm-url': 'cs:xenial/h$
2017-04-13 21:17:42,917 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Deploy returned {'results': [{}]}
2017-04-13 21:17:42,918 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Expose: {'application': 'haproxy'}
2017-04-13 21:17:43,221 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Expose returned: {}
2017-04-13 21:17:43,221 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Adding Charm cs:xenial/landscape-server-21
2017-04-13 21:17:44,832 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: AddCharm returned {}
2017-04-13 21:17:44,975 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Resources for charm id 'cs:xenial/landscape-server-21': []
2017-04-13 21:17:44,981 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Deploying <Service landscape-server>: {'applications': [{'charm-url': 'cs$
2017-04-13 21:17:45,885 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Deploy returned {'results': [{}]}
2017-04-13 21:17:45,888 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Adding Charm cs:xenial/postgresql-101
2017-04-13 21:17:49,214 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: AddCharm returned {}
2017-04-13 21:17:49,344 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Resources for charm id 'cs:xenial/postgresql-101': []
2017-04-13 21:17:49,348 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Deploying <Service postgresql>: {'applications': [{'charm-url': 'cs:xenia$
2017-04-13 21:17:50,763 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Deploy returned {'results': [{}]}
2017-04-13 21:17:50,764 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Adding Charm cs:xenial/rabbitmq-server-5
2017-04-13 21:17:52,073 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: AddCharm returned {}
2017-04-13 21:17:52,204 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Resources for charm id 'cs:xenial/rabbitmq-server-5': []
2017-04-13 21:17:52,208 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Deploying <Service rabbitmq-server>: {'applications': [{'charm-url': 'cs:$
2017-04-13 21:17:53,520 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Deploy returned {'results': [{}]}
2017-04-13 21:17:53,521 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: AddRelation: {'Endpoints': ['landscape-server:db', 'postgresql:db-admin']}
2017-04-13 21:17:53,826 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: AddRelation returned: {'endpoints': {'landscape-server': {'name': 'db', '$
2017-04-13 21:17:53,826 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: AddRelation: {'Endpoints': ['landscape-server', 'rabbitmq-server']}
2017-04-13 21:17:54,234 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: AddRelation returned: {'endpoints': {'landscape-server': {'name': 'amqp',$
2017-04-13 21:17:54,235 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: AddRelation: {'Endpoints': ['landscape-server', 'haproxy']}
2017-04-13 21:17:54,642 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: AddRelation returned: {'endpoints': {'haproxy': {'name': 'reverseproxy', $
2017-04-13 21:46:57,197 [ERROR] log.py:23 - conjure-up/_unspecified_spell: __init__() got an unexpected keyword argument 'default'
Traceback (most recent call last):
  File "/snap/conjure-up/191/lib/python3.6/site-packages/conjureup/controllers/steps/gui.py", line 127, in render
    self.finish)
  File "/snap/conjure-up/191/lib/python3.6/site-packages/conjureup/ui/widgets/step.py", line 48, in __init__
    default=i.get('default'))
TypeError: __init__() got an unexpected keyword argument 'default'
2017-04-13 21:46:57,215 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Showing dialog for exception: __init__() got an unexpected keyword argume$
```

Any help appreciated thank you. Also i am not running conjure from a vm. syetem speck: all systems are 8cores AMD 3.2GHZ, 64GB RAM, 160GB HDD, i have SIX ready within maas. 

Selected Cloud Provider: maas

Provide the output of the following commands:

```
which juju
/snap/bin/juju

which conjure-up
/snap/bin/conjure-up

which lxd
/usr/bin/lxd

juju version
2.1.2-xenial-amd64

conjure-up --version
conjure-up 2.1.3

lxd --version
2.12

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
```

Summary of problem:

**Comment by battlemidget** [comment]
Thanks for the report, we'll get this addressed asap
