### ISSUE TITLE
Conjure-up fails to exit properly once deployment is completed

### ISSUE THREAD

**Issue by canonical-cgregan** [conjure-up/conjure-up#831]
/snap/bin/conjure-up
2.2-beta3+1a1052c (200) 98MB classic
MAAS version: 2.2.0~rc2 (bzr5983-0ubuntu1~16.04.1)
juju: 1:2.2~beta2-0ubuntu1~16.04.1~juju1
Kubernetes-core spell

Once the deployment is complete and the UI is quit out. The user is not returned to a working shell, but instead it seems conjure-up is still holding the terminal. Ctrl+c results in the following.

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/snap/conjure-up/200/usr/lib/python3.6/concurrent/futures/thread.py", line 39, in _python_exit
    t.join()
  File "/snap/conjure-up/200/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/snap/conjure-up/200/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Exception ignored in: <function ThreadPoolExecutor._adjust_thread_count.<locals>.weakref_cb at 0x7f129d866598>
Traceback (most recent call last):
  File "/snap/conjure-up/200/usr/lib/python3.6/concurrent/futures/thread.py", line 123, in weakref_cb
  File "/snap/conjure-up/200/usr/lib/python3.6/queue.py", line 145, in put
  File "/snap/conjure-up/200/usr/lib/python3.6/threading.py", line 347, in notify
TypeError: 'NoneType' object is not callable

**Comment by battlemidget** [comment]
Please re-try with rev 201 thanks!

**Comment by johnsca** [comment]
Can you provide the `~/.cache/conjure-up/conjure-up.log` file for that failure?

**Comment by canonical-cgregan** [comment]
Thought I did, but did not realize github does not support .log file type....what?
[conjure-up.txt](https://github.com/conjure-up/conjure-up/files/945330/conjure-up.txt)

**Comment by battlemidget** [comment]
We need to cleanup the rest of the threading code and transition to asyncio. This will have to be done post 2.2 GA.

**Comment by canonical-cgregan** [comment]
So this does eventually exit, but after pressing (Q) the user is reasonably expecting to get dumped to a free term. Instead conjure-up holds that term for several more minutes. You could delay the display of the Quit option or show some sort of "Closing up final tasks.........." on the term after quit

**Comment by battlemidget** [comment]
@canonical-cgregan @johnsca added some code to make this more obvious for the user to wait: https://github.com/conjure-up/conjure-up/commit/ce2e31c5fad52e3e7714289d879c9a4f2463f693 

It's currently being built in launchpad and should be available soon. Will keep this open though as a TODO to clear out the rest of the threaded calls we still make.
