### ISSUE TITLE
conjure-down stacktraces

### ISSUE THREAD

**Issue by canonical-cgregan** [conjure-up/conjure-up#832]
/snap/bin/conjure-up
2.2-beta3+1a1052c (200) 98MB classic
MAAS version: 2.2.0rc2 (bzr5983-0ubuntu116.04.1)
juju: 1:2.2beta2-0ubuntu116.04.1~juju1
Kubernetes-core spell

```
cdoqa@donphan:~$ conjure-down
Traceback (most recent call last):
  File "/snap/conjure-up/200/lib/python3.6/site-packages/ubuntui/ev.py", line 82, in run
    cls.loop.run()
  File "/snap/conjure-up/200/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/snap/conjure-up/200/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/snap/conjure-up/200/lib/python3.6/site-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/conjure-up/200/bin/conjure-down", line 11, in <module>
    load_entry_point('conjure-up==2.2b3+1a1052c', 'console_scripts', 'conjure-down')()
  File "/snap/conjure-up/200/lib/python3.6/site-packages/conjureup/destroy.py", line 84, in main
    EventLoop.run()
  File "/snap/conjure-up/200/lib/python3.6/site-packages/ubuntui/ev.py", line 84, in run
    log.exception("Exception in ev.run():")
  File "/snap/conjure-up/200/usr/lib/python3.6/logging/__init__.py", line 1341, in exception
    self.error(msg, *args, exc_info=exc_info, **kwargs)
  File "/snap/conjure-up/200/usr/lib/python3.6/logging/__init__.py", line 1335, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/snap/conjure-up/200/usr/lib/python3.6/logging/__init__.py", line 1441, in _log
    exc_info, func, extra, sinfo)
  File "/snap/conjure-up/200/usr/lib/python3.6/logging/__init__.py", line 1411, in makeRecord
    sinfo)
  File "/snap/conjure-up/200/lib/python3.6/site-packages/conjureup/log.py", line 16, in spell_record_factory
    spell_name = app.config.get('spell', consts.UNSPECIFIED_SPELL)
AttributeError: 'str' object has no attribute 'config'
```

(johnsca: Edited for formatting)

**Comment by battlemidget** [comment]
Please re-try with rev 201 thanks!
