### ISSUE TITLE
[ARM64] openstack spell failed to deploy.

### ISSUE THREAD

**Issue by manjo-git** [conjure-up/conjure-up#836]
## Report
I git cloned  https://github.com/conjure-up/conjure-up and created a snap for ARM64. Then tried to deploy openstack using LXD and localhost.

I got the screen where it said "please finish the installation...."  and I selected all the options it wanted to run, import glance, sshkeys etc etc, those were all running (hour glass icons) when it failed with the following message:
 expecting value: line1 column 1 (char 0)

Looking at the logs I can see this trace back:

2017-04-20 16:38:18,260 [ERROR] conjure-up/openstack-novalxd - events.py:96 - Unhandled exception
Traceback (most recent call last):
  File "/snap/conjure-up/x1/lib/python3.6/site-packages/conjureup/events.py", line 94, in handle_exception
    raise exc
  File "/snap/conjure-up/x1/lib/python3.6/site-packages/conjureup/controllers/steps/gui.py", line 99, in refresh
    w.update()
  File "/snap/conjure-up/x1/lib/python3.6/site-packages/conjureup/ui/widgets/step.py", line 87, in update
    result = json.loads(lines[-1])
  File "/snap/conjure-up/x1/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/snap/conjure-up/x1/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/snap/conjure-up/x1/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2017-04-20 16:38:18,277 [DEBUG] conjure-up/openstack-novalxd - __init__.py:29 - Showing dialog for exception: Expecting value: line 1 column 1 (char 0)

## Please provide the output of the following commands
lxd version is 2.12
conjure-up was built from source git clone on April 20 '17
## Summary of problem
[failed-openstack-conjure-up.log.tar.zip](https://github.com/conjure-up/conjure-up/files/945453/failed-openstack-conjure-up.log.tar.zip)

**Comment by manjo-git** [comment]
Here is the output from juju status after I hit "
[failed_openstack_juju_status.txt.gz](https://github.com/conjure-up/conjure-up/files/945457/failed_openstack_juju_status.txt.gz)
Quit"

**Comment by manjo-git** [comment]
One more thing to note.. I do not see the screen where it would display the different units being started, deployed etc .. after a couple of minutes on screen 2 where it said Adding machine it took me straight to finish install screen. juju status says things were being installed and setup.

**Comment by manjo-git** [comment]
I repeated the deployment and waited for the units to finish. But found that LXD/0 was failing with "install hook failed". Poking around I see in unit-lxd-0.log the following:

2017-04-20 22:00:42 INFO install E: Package 'criu' has no installation candidate
2017-04-20 22:00:43 INFO juju-log Couldn't acquire DPKG lock. Will retry in 10 seconds.
2017-04-20 22:00:53 INFO install Reading package lists...
2017-04-20 22:00:53 INFO install Building dependency tree...
2017-04-20 22:00:53 INFO install Reading state information...
2017-04-20 22:00:53 INFO install Package criu is not available, but is referred to by another package.
2017-04-20 22:00:53 INFO install This may mean that the package is missing, has been obsoleted, or
2017-04-20 22:00:53 INFO install is only available from another source
2017-04-20 22:00:53 INFO install
2017-04-20 22:00:53 INFO install E: Package 'criu' has no installation candidate
2017-04-20 22:00:53 INFO install Traceback (most recent call last):
2017-04-20 22:00:53 INFO install   File "/var/lib/juju/agents/unit-lxd-0/charm/hooks/install", line 140, in <module>
2017-04-20 22:00:53 INFO install     main()
2017-04-20 22:00:53 INFO install   File "/var/lib/juju/agents/unit-lxd-0/charm/hooks/install", line 134, in main
2017-04-20 22:00:53 INFO install     hooks.execute(sys.argv)
2017-04-20 22:00:53 INFO install   File "/var/lib/juju/agents/unit-lxd-0/charm/hooks/charmhelpers/core/hookenv.py", line 731, in execute
2017-04-20 22:00:53 INFO install     self._hooks[hook_name]()
2017-04-20 22:00:53 INFO install   File "/var/lib/juju/agents/unit-lxd-0/charm/hooks/install", line 66, in install
2017-04-20 22:00:53 INFO install     apt_install(determine_packages(), fatal=True)
2017-04-20 22:00:53 INFO install   File "/var/lib/juju/agents/unit-lxd-0/charm/hooks/charmhelpers/fetch/ubuntu.py", line 162, in install
2017-04-20 22:00:53 INFO install     _run_apt_command(cmd, fatal)
2017-04-20 22:00:53 INFO install   File "/var/lib/juju/agents/unit-lxd-0/charm/hooks/charmhelpers/fetch/ubuntu.py", line 313, in _run_apt_command
2017-04-20 22:00:53 INFO install     result = subprocess.check_call(cmd, env=env)
2017-04-20 22:00:53 INFO install   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
2017-04-20 22:00:53 INFO install     raise CalledProcessError(retcode, cmd)
2017-04-20 22:00:53 INFO install subprocess.CalledProcessError: Command '['apt-get', '--assume-yes', '--option=Dpkg::Options::=--force-confold', 'install', 'btrfs-tools', 'thin-provisioning-tools', 'zfsutils-linux', 'criu', 'lvm2', 'lxd', 'lxd-client']' returned non-zero exit status 100
2017-04-20 22:00:53 ERROR juju.worker.uniter.operation runhook.go:107 hook "install" failed: exit status 1

**Comment by manjo-git** [comment]
Also mysql/0 fails due to the following reasons:

Apr 20 22:20:06 juju-89a28c-0 systemd[1]: Started User Manager for UID 1000.
Apr 20 22:20:57 juju-89a28c-0 systemd[1]: Stopping LSB: Start and stop the mysql (Percona XtraDB Cluster) daemon...
Apr 20 22:20:57 juju-89a28c-0 systemd[1]: Failed to reset devices.list on /system.slice/run-user-1000.mount: Operation not permitted
Apr 20 22:20:57 juju-89a28c-0 mysql[12209]:  * Stopping MySQL (Percona XtraDB Cluster) mysqld
Apr 20 22:20:57 juju-89a28c-0 mysql[12209]:    ...done.
Apr 20 22:20:57 juju-89a28c-0 systemd[1]: Stopped LSB: Start and stop the mysql (Percona XtraDB Cluster) daemon.
Apr 20 22:20:57 juju-89a28c-0 systemd[1]: Failed to reset devices.list on /system.slice/mysql.service: Operation not permitted
Apr 20 22:20:57 juju-89a28c-0 systemd[1]: Starting LSB: Start and stop the mysql (Percona XtraDB Cluster) daemon...
Apr 20 22:20:57 juju-89a28c-0 mysql[12259]:  * Starting MySQL (Percona XtraDB Cluster) database server mysqld
Apr 20 22:20:59 juju-89a28c-0 /etc/init.d/mysql[12911]: MySQL PID not found, pid_file detected/guessed: /var/run/mysqld/mysqld.pid
Apr 20 22:20:59 juju-89a28c-0 mysql[12259]:  * Please take a look at the syslog.
Apr 20 22:20:59 juju-89a28c-0 mysql[12259]:    ...fail!
Apr 20 22:20:59 juju-89a28c-0 systemd[1]: mysql.service: Control process exited, code=exited status=1
Apr 20 22:20:59 juju-89a28c-0 systemd[1]: Failed to start LSB: Start and stop the mysql (Percona XtraDB Cluster) daemon.
Apr 20 22:20:59 juju-89a28c-0 systemd[1]: mysql.service: Unit entered failed state.
Apr 20 22:20:59 juju-89a28c-0 systemd[1]: mysql.service: Failed with result 'exit-code'.

**Comment by battlemidget** [comment]
Those issues probably should be filed with the charm so that they can get those fixed at the charm level

**Comment by manjo-git** [comment]
Install worked on ARM64

$ sudo snap install conjure-up --classic --edge
conjure-up (edge) 2.2-beta3+8c775ab from 'canonical' installed
