### ISSUE TITLE
[PPC64] Issue finish Openstack-lxd : glance/charms

### ISSUE THREAD

**Issue by epaumerat** [conjure-up/conjure-up#848]
Hi there trying to deploy openstack-lxd on a Power server (IBM OpenVM) via conjure-up

During the glance part, somehting is going wrong with the step-02_glance script : 

2017-04-27 09:59:28,018 [DEBUG] conjure-up/openstack-novalxd - common.py:21 - Set_env inputs: []
2017-04-27 09:59:28,020 [INFO] conjure-up/openstack-novalxd - utils.py:126 - Running Glance.
2017-04-27 09:59:28,020 [DEBUG] conjure-up/openstack-novalxd - utils.py:135 - Executing script: /home/constellation/.cache/conjure-up/openstack-novalxd/steps/step-02_glance
2017-04-27 10:00:09,235 [DEBUG] conjure-up/openstack-novalxd - events.py:18 - Setting Error
2017-04-27 10:00:09,237 [ERROR] conjure-up/openstack-novalxd - events.py:96 - Unhandled exception
Traceback (most recent call last):
  File "/snap/conjure-up/217/lib/python3.6/site-packages/conjureup/events.py", line 94, in handle_exception
    raise exc
  File "/snap/conjure-up/217/lib/python3.6/site-packages/conjureup/controllers/steps/gui.py", line 99, in refresh
    w.update()
  File "/snap/conjure-up/217/lib/python3.6/site-packages/conjureup/ui/widgets/step.py", line 87, in update
    result = json.loads(lines[-1])
  File "/snap/conjure-up/217/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/snap/conjure-up/217/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/snap/conjure-up/217/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2017-04-27 10:00:09,305 [DEBUG] conjure-up/openstack-novalxd - __init__.py:30 - Showing dialog for exception: Expecting value: line 1 column 1 (char 0)
2017-04-27 10:03:25,408 [DEBUG] conjure-up/openstack-novalxd - events.py:18 - Setting Shutdown
2017-04-27 10:03:25,408 [INFO] conjure-up/openstack-novalxd - events.py:113 - Shutting down
2017-04-27 10:03:25,409 [INFO] conjure-up/openstack-novalxd - events.py:121 - Disconnecting model
2017-04-27 10:03:25,411 [INFO] conjure-up/openstack-novalxd - events.py:123 - Disconnected
## Report

juju version 2.2-beta3-xenial-ppc64el
conjure-up version 2.2-beta3+8a4b943
lxd version 2.12
lxc config show
config:
  core.https_address: '[::]'
  core.https_allowed_credentials: "true"
  core.https_allowed_headers: Origin, X-Requested-With, Content-Type, Accept
  core.https_allowed_methods: GET, POST, PUT, DELETE, OPTIONS
  core.https_allowed_origin: https://0.0.0.0:8000
  core.trust_password: true
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

Thank you.

**Comment by battlemidget** [comment]
Can you add a tarball of `~/.cache/conjure-up`? It has logging associated with the step that I need to see.

Thanks!

**Comment by epaumerat** [comment]
Sorry I thought it was on the first message.
Thanks.

[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/961642/conjure-up.tar.gz)
