### ISSUE TITLE
Failures in automated tests

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#854]
Seeing a lot of these in our test runner:

```
[error] WebSocket connection is closed: code = 1006, no reason.
[warning] Shutting down
```

**Comment by battlemidget** [comment]
@johnsca

**Comment by battlemidget** [comment]
```
2017-04-29 01:25:29,334 [DEBUG] conjure-up/openstack-novalxd - utils.py:135 - Executing script: /home/ubuntu/.cache/conjure-up/openstack-novalxd/steps/00_deploy-done
2017-04-29 14:10:20,814 [INFO] conjure-up/openstack-novalxd - websockets.protocol: protocol.py:618 - Failing the WebSocket connection: 1006 
2017-04-29 14:10:20,815 [ERROR] conjure-up/openstack-novalxd - juju.model: model.py:641 - Error in watcher
Traceback (most recent call last):
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/model.py", line 630, in _start_watch
    self.loop)
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/utils.py", line 94, in run_with_interrupt
    result = [f.result() for f in done if f is not event_task]
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/utils.py", line 94, in <listcomp>
    result = [f.result() for f in done if f is not event_task]
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/client/facade.py", line 392, in wrapper
    reply = await f(*args, **kwargs)
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/client/_client1.py", line 59, in Next
    reply = await self.rpc(msg)
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/client/overrides.py", line 99, in rpc
    result =  await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/client/connection.py", line 237, in rpc
    result = await self.recv(msg['request-id'])
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/client/connection.py", line 174, in recv
    return await self.messages.get(request_id)
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/utils.py", line 63, in get
    raise value
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/client/connection.py", line 182, in receiver
    loop=self.loop)
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/utils.py", line 94, in run_with_interrupt
    result = [f.result() for f in done if f is not event_task]
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/utils.py", line 94, in <listcomp>
    result = [f.result() for f in done if f is not event_task]
  File "/snap/conjure-up/239/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006, no reason.
2017-04-29 14:10:20,820 [DEBUG] conjure-up/openstack-novalxd - events.py:18 - Setting Error
2017-04-29 14:10:20,821 [ERROR] conjure-up/openstack-novalxd - events.py:96 - Unhandled exception
Traceback (most recent call last):
  File "/snap/conjure-up/239/lib/python3.6/site-packages/conjureup/events.py", line 94, in handle_exception
    raise exc
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/model.py", line 630, in _start_watch
    self.loop)
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/utils.py", line 94, in run_with_interrupt
    result = [f.result() for f in done if f is not event_task]
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/utils.py", line 94, in <listcomp>
    result = [f.result() for f in done if f is not event_task]
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/client/facade.py", line 392, in wrapper
    reply = await f(*args, **kwargs)
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/client/_client1.py", line 59, in Next
    reply = await self.rpc(msg)
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/client/overrides.py", line 99, in rpc
    result =  await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/client/connection.py", line 237, in rpc
    result = await self.recv(msg['request-id'])
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/client/connection.py", line 174, in recv
    return await self.messages.get(request_id)
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/utils.py", line 63, in get
    raise value
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/client/connection.py", line 182, in receiver
    loop=self.loop)
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/utils.py", line 94, in run_with_interrupt
    result = [f.result() for f in done if f is not event_task]
  File "/snap/conjure-up/239/lib/python3.6/site-packages/juju/utils.py", line 94, in <listcomp>
    result = [f.result() for f in done if f is not event_task]
  File "/snap/conjure-up/239/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006, no reason.
2017-04-29 14:10:20,822 [DEBUG] conjure-up/openstack-novalxd - events.py:18 - Setting Shutdown
2017-04-29 14:10:20,823 [INFO] conjure-up/openstack-novalxd - events.py:113 - Shutting down
2017-04-29 14:10:20,824 [INFO] conjure-up/openstack-novalxd - events.py:121 - Disconnecting model
2017-04-29 14:10:20,824 [INFO] conjure-up/openstack-novalxd - events.py:123 - Disconnected
```

http://paste.ubuntu.com/24482246/

**Comment by battlemidget** [comment]
Have not been able to reproduce since the libjuju fix went in
