### ISSUE TITLE
charm not found error when deploying spell from an edge channel

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#862]
To reproduce:

```
conjure-up canonical-kubernetes --channel=edge
```

Traceback:
```
2017-05-03 20:26:45,399 [DEBUG] conjure-up/canonical-kubernetes - events.py:50 - Setting Error at conjureup/events.py:133
2017-05-03 20:26:45,399 [ERROR] conjure-up/canonical-kubernetes - events.py:141 - Unhandled exception
Traceback (most recent call last):
  File "/snap/conjure-up/253/lib/python3.6/site-packages/conjureup/events.py", line 139, in handle_exception
    raise exc
  File "/snap/conjure-up/253/lib/python3.6/site-packages/conjureup/controllers/deploy/gui.py", line 241, in _do_deploy
    await juju.deploy_service(application, default_series, msg_cb=msg_cb)
  File "/snap/conjure-up/253/lib/python3.6/site-packages/conjureup/juju.py", line 612, in deploy_service
    app_inst = await app.juju.client.deploy(**deploy_args)
  File "/snap/conjure-up/253/lib/python3.6/site-packages/juju/model.py", line 1039, in deploy
    await client_facade.AddCharm(channel, entity_id)
  File "/snap/conjure-up/253/lib/python3.6/site-packages/juju/client/facade.py", line 392, in wrapper
    reply = await f(*args, **kwargs)
  File "/snap/conjure-up/253/lib/python3.6/site-packages/juju/client/_client1.py", line 1253, in AddCharm
    reply = await self.rpc(msg)
  File "/snap/conjure-up/253/lib/python3.6/site-packages/juju/client/facade.py", line 514, in rpc
    result = await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/snap/conjure-up/253/lib/python3.6/site-packages/juju/client/connection.py", line 244, in rpc
    raise JujuAPIError(result)
juju.errors.JujuAPIError: cannot retrieve "cs:~containers/flannel-15": charm not found
```
Full log http://paste.ubuntu.com/24507964/

**Comment by battlemidget** [comment]
Flaky responses from charmstore caused this
