### ISSUE TITLE
Can not attach volume to an instance

### ISSUE THREAD

**Issue by ekalaya2015** [conjure-up/conjure-up#884]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [x] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
No
- [x] Is conjure-up running inside a virtual machine?
No
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?
Yes

## Please provide the output of the following commands

```
which juju
/snap/bin/juju

which conjure-up
/snap/bin/conjure-up

which lxd
/usr/bin/lxd

juju version
2.1.2-xenial-amd64

conjure-up --version
conjure-up 2.1.5

lxd --version
2.13

lxc config show
config: {}

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/995449/conjure-up.tar.gz)

```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

## What Spell was Selected?
Landscape

## What provider (aws, maas, localhost, etc)?
maas

### MAAS Users
Which version of MAAS?
MAAS Version 2.1.3+bzr5573-0ubuntu1 (16.04.1)

## Commands ran

Please outline what commands were run to install and execute conjure-up:
```
sudo snap install conjure-up --classic
conjure-up --bootstrap-to jujucontroller

```
## Additional Information
In Horizon, I could not create instance with 'boot source from image' and 'Create new volume' option enabled. It will work if I choose 'No' in 'Create new volume'  option.

![instance error](https://cloud.githubusercontent.com/assets/27433888/25990631/9b799768-372a-11e7-9804-45b3205335bc.png)

Similar problem happened when I tried to attach volume to an instance. 
Attaching process can be seen below

```
(openstack) server list
+--------------------------------------+------------+--------+----------------------------+
| ID                                   | Name       | Status | Networks                   |
+--------------------------------------+------------+--------+----------------------------+
| 1a8a00fb-94b6-4109-ae58-f44291626a46 | ubuntu1204 | ACTIVE | private_project=172.16.1.9 |
+--------------------------------------+------------+--------+----------------------------+
(openstack) volume list
+--------------------------------------+--------------+-----------+------+-------------+
| ID                                   | Display Name | Status    | Size | Attached to |
+--------------------------------------+--------------+-----------+------+-------------+
| 9036101a-8833-448f-8cdf-21ff1bc7dd76 | test_vol     | available |   10 |             |
+--------------------------------------+--------------+-----------+------+-------------+
(openstack) server add volume ubuntu1204 test_vol
(openstack) volume list
+--------------------------------------+--------------+-----------+------+-------------+
| ID                                   | Display Name | Status    | Size | Attached to |
+--------------------------------------+--------------+-----------+------+-------------+
| 9036101a-8833-448f-8cdf-21ff1bc7dd76 | test_vol     | available |   10 |             |
+--------------------------------------+--------------+-----------+------+-------------+
(openstack)

```
- no instance in column 'Attached to'

and here is nova.log 

```
2017-05-12 08:31:26.622 15969 ERROR nova.virt.libvirt.driver [req-ddcb2287-8fe9-4287-886d-4e23796d586e 0512742ccde048e0b56a754bf76fc8b2 646fc0cc134c4bb5b0e4747dd1971188 - - -] [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46] Failed to attach volume at mountpoint: /dev/vdb
2017-05-12 08:31:26.622 15969 ERROR nova.virt.libvirt.driver [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46] Traceback (most recent call last):
2017-05-12 08:31:26.622 15969 ERROR nova.virt.libvirt.driver [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 1232, in attach_volume
2017-05-12 08:31:26.622 15969 ERROR nova.virt.libvirt.driver [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     guest.attach_device(conf, persistent=True, live=live)
2017-05-12 08:31:26.622 15969 ERROR nova.virt.libvirt.driver [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/guest.py", line 304, in attach_device
2017-05-12 08:31:26.622 15969 ERROR nova.virt.libvirt.driver [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     device_xml = conf.to_xml()
2017-05-12 08:31:26.622 15969 ERROR nova.virt.libvirt.driver [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/config.py", line 77, in to_xml
2017-05-12 08:31:26.622 15969 ERROR nova.virt.libvirt.driver [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     root = self.format_dom()
2017-05-12 08:31:26.622 15969 ERROR nova.virt.libvirt.driver [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/config.py", line 765, in format_dom
2017-05-12 08:31:26.622 15969 ERROR nova.virt.libvirt.driver [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     uuid=self.auth_secret_uuid))
2017-05-12 08:31:26.622 15969 ERROR nova.virt.libvirt.driver [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "src/lxml/lxml.etree.pyx", line 2998, in lxml.etree.Element (src/lxml/lxml.etree.c:80607)
2017-05-12 08:31:26.622 15969 ERROR nova.virt.libvirt.driver [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "src/lxml/apihelpers.pxi", line 135, in lxml.etree._makeElement (src/lxml/lxml.etree.c:17604)
2017-05-12 08:31:26.622 15969 ERROR nova.virt.libvirt.driver [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "src/lxml/apihelpers.pxi", line 123, in lxml.etree._makeElement (src/lxml/lxml.etree.c:17452)
2017-05-12 08:31:26.622 15969 ERROR nova.virt.libvirt.driver [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "src/lxml/apihelpers.pxi", line 302, in lxml.etree._initNodeAttributes (src/lxml/lxml.etree.c:19840)
2017-05-12 08:31:26.622 15969 ERROR nova.virt.libvirt.driver [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "src/lxml/apihelpers.pxi", line 316, in lxml.etree._addAttributeToNode (src/lxml/lxml.etree.c:20196)
2017-05-12 08:31:26.622 15969 ERROR nova.virt.libvirt.driver [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "src/lxml/apihelpers.pxi", line 1437, in lxml.etree._utf8 (src/lxml/lxml.etree.c:32414)
2017-05-12 08:31:26.622 15969 ERROR nova.virt.libvirt.driver [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46] TypeError: Argument must be bytes or unicode, got 'NoneType'
2017-05-12 08:31:26.622 15969 ERROR nova.virt.libvirt.driver [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [req-ddcb2287-8fe9-4287-886d-4e23796d586e 0512742ccde048e0b56a754bf76fc8b2 646fc0cc134c4bb5b0e4747dd1971188 - - -] [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46] Driver failed to attach volume 9036101a-8833-448f-8cdf-21ff1bc7dd76 at /dev/vdb
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46] Traceback (most recent call last):
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/nova/virt/block_device.py", line 273, in attach
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     device_type=self['device_type'], encryption=encryption)
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 1243, in attach_volume
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     self._disconnect_volume(connection_info, disk_dev)
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     self.force_reraise()
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     six.reraise(self.type_, self.value, self.tb)
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 1232, in attach_volume
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     guest.attach_device(conf, persistent=True, live=live)
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/guest.py", line 304, in attach_device
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     device_xml = conf.to_xml()
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/config.py", line 77, in to_xml
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     root = self.format_dom()
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/config.py", line 765, in format_dom
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     uuid=self.auth_secret_uuid))
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "src/lxml/lxml.etree.pyx", line 2998, in lxml.etree.Element (src/lxml/lxml.etree.c:80607)
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "src/lxml/apihelpers.pxi", line 135, in lxml.etree._makeElement (src/lxml/lxml.etree.c:17604)
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "src/lxml/apihelpers.pxi", line 123, in lxml.etree._makeElement (src/lxml/lxml.etree.c:17452)
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "src/lxml/apihelpers.pxi", line 302, in lxml.etree._initNodeAttributes (src/lxml/lxml.etree.c:19840)
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "src/lxml/apihelpers.pxi", line 316, in lxml.etree._addAttributeToNode (src/lxml/lxml.etree.c:20196)
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "src/lxml/apihelpers.pxi", line 1437, in lxml.etree._utf8 (src/lxml/lxml.etree.c:32414)
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46] TypeError: Argument must be bytes or unicode, got 'NoneType'
2017-05-12 08:31:26.623 15969 ERROR nova.virt.block_device [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [req-ddcb2287-8fe9-4287-886d-4e23796d586e 0512742ccde048e0b56a754bf76fc8b2 646fc0cc134c4bb5b0e4747dd1971188 - - -] [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46] Failed to attach 9036101a-8833-448f-8cdf-21ff1bc7dd76 at /dev/vdb
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46] Traceback (most recent call last):
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 4788, in _attach_volume
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     do_check_attach=False, do_driver_attach=True)
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/nova/virt/block_device.py", line 48, in wrapped
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     ret_val = method(obj, context, *args, **kwargs)
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/nova/virt/block_device.py", line 282, in attach
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     connector)
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     self.force_reraise()
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     six.reraise(self.type_, self.value, self.tb)
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/nova/virt/block_device.py", line 273, in attach
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     device_type=self['device_type'], encryption=encryption)
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 1243, in attach_volume
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     self._disconnect_volume(connection_info, disk_dev)
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     self.force_reraise()
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     six.reraise(self.type_, self.value, self.tb)
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 1232, in attach_volume
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     guest.attach_device(conf, persistent=True, live=live)
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/guest.py", line 304, in attach_device
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     device_xml = conf.to_xml()
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/config.py", line 77, in to_xml
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     root = self.format_dom()
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/config.py", line 765, in format_dom
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]     uuid=self.auth_secret_uuid))
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "src/lxml/lxml.etree.pyx", line 2998, in lxml.etree.Element (src/lxml/lxml.etree.c:80607)
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "src/lxml/apihelpers.pxi", line 135, in lxml.etree._makeElement (src/lxml/lxml.etree.c:17604)
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "src/lxml/apihelpers.pxi", line 123, in lxml.etree._makeElement (src/lxml/lxml.etree.c:17452)
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "src/lxml/apihelpers.pxi", line 302, in lxml.etree._initNodeAttributes (src/lxml/lxml.etree.c:19840)
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "src/lxml/apihelpers.pxi", line 316, in lxml.etree._addAttributeToNode (src/lxml/lxml.etree.c:20196)
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]   File "src/lxml/apihelpers.pxi", line 1437, in lxml.etree._utf8 (src/lxml/lxml.etree.c:32414)
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46] TypeError: Argument must be bytes or unicode, got 'NoneType'
2017-05-12 08:31:27.033 15969 ERROR nova.compute.manager [instance: 1a8a00fb-94b6-4109-ae58-f44291626a46]
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server [req-ddcb2287-8fe9-4287-886d-4e23796d586e 0512742ccde048e0b56a754bf76fc8b2 646fc0cc134c4bb5b0e4747dd1971188 - - -] Exception during message handling
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server Traceback (most recent call last):
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/oslo_messaging/rpc/server.py", line 155, in _process_incoming
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     res = self.dispatcher.dispatch(message)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatcher.py", line 222, in dispatch
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     return self._do_dispatch(endpoint, method, ctxt, args)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatcher.py", line 192, in _do_dispatch
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     result = func(ctxt, **new_args)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/nova/exception_wrapper.py", line 75, in wrapped
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     function_name, call_dict, binary)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     self.force_reraise()
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     six.reraise(self.type_, self.value, self.tb)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/nova/exception_wrapper.py", line 66, in wrapped
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     return f(self, context, *args, **kw)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 216, in decorated_function
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     kwargs['instance'], e, sys.exc_info())
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     self.force_reraise()
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     six.reraise(self.type_, self.value, self.tb)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 204, in decorated_function
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     return function(self, context, *args, **kwargs)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 4778, in attach_volume
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     do_attach_volume(context, instance, driver_bdm)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py", line 274, in inner
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     return f(*args, **kwargs)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 4776, in do_attach_volume
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     bdm.destroy()
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     self.force_reraise()
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     six.reraise(self.type_, self.value, self.tb)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 4773, in do_attach_volume
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     return self._attach_volume(context, instance, driver_bdm)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 4796, in _attach_volume
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     self.volume_api.unreserve_volume(context, bdm.volume_id)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     self.force_reraise()
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     six.reraise(self.type_, self.value, self.tb)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 4788, in _attach_volume
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     do_check_attach=False, do_driver_attach=True)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/nova/virt/block_device.py", line 48, in wrapped
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     ret_val = method(obj, context, *args, **kwargs)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/nova/virt/block_device.py", line 282, in attach
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     connector)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     self.force_reraise()
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     six.reraise(self.type_, self.value, self.tb)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/nova/virt/block_device.py", line 273, in attach
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     device_type=self['device_type'], encryption=encryption)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 1243, in attach_volume
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     self._disconnect_volume(connection_info, disk_dev)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     self.force_reraise()
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     six.reraise(self.type_, self.value, self.tb)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 1232, in attach_volume
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     guest.attach_device(conf, persistent=True, live=live)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/guest.py", line 304, in attach_device
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     device_xml = conf.to_xml()
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/config.py", line 77, in to_xml
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     root = self.format_dom()
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/config.py", line 765, in format_dom
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server     uuid=self.auth_secret_uuid))
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "src/lxml/lxml.etree.pyx", line 2998, in lxml.etree.Element (src/lxml/lxml.etree.c:80607)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "src/lxml/apihelpers.pxi", line 135, in lxml.etree._makeElement (src/lxml/lxml.etree.c:17604)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "src/lxml/apihelpers.pxi", line 123, in lxml.etree._makeElement (src/lxml/lxml.etree.c:17452)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "src/lxml/apihelpers.pxi", line 302, in lxml.etree._initNodeAttributes (src/lxml/lxml.etree.c:19840)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "src/lxml/apihelpers.pxi", line 316, in lxml.etree._addAttributeToNode (src/lxml/lxml.etree.c:20196)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server   File "src/lxml/apihelpers.pxi", line 1437, in lxml.etree._utf8 (src/lxml/lxml.etree.c:32414)
2017-05-12 08:31:27.337 15969 ERROR oslo_messaging.rpc.server TypeError: Argument must be bytes or unicode, got 'NoneType'

```

**Comment by battlemidget** [comment]
This is really out of the scope of conjure-up and not necessarily a bug with conjure-up. For additional support you'll want to visit https://askubuntu.com/questions/tagged/openstack-autopilot for questions like these.

Thanks!

**Comment by ekalaya2015** [comment]
@battlemidget  Ok. Understood. Sorry for making this misplaced
