### ISSUE TITLE
Exception: Problem setting default profile: CompletedProcess(args='cat /tmp/tmpcpcb753i |conjure-up.lxc prof...

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#967]
https://sentry.io/canonical-pj/conjure-up/issues/298429577/

```
Exception: Problem setting default profile: CompletedProcess(args='cat /tmp/tmpcpcb753i |conjure-up.lxc profile edit default', returncode=1, stdout=b'', stderr=b"error: Failed to retrieve profile='default'\n")
(21 additional frame(s) were not displayed)
...
  File "conjureup/controllers/credentials/common.py", line 21, in finish
    controllers.use('lxdsetup').render()
  File "conjureup/controllers/lxdsetup/gui.py", line 11, in render
    return self.setup(self.ifaces[0])
  File "conjureup/controllers/lxdsetup/common.py", line 46, in setup
    self.lxd_init(iface)
  File "conjureup/controllers/lxdsetup/common.py", line 70, in lxd_init
    cmd()
  File "conjureup/controllers/lxdsetup/common.py", line 146, in set_default_profile
    out))

Exception: Problem setting default profile: CompletedProcess(args='cat /tmp/tmpcpcb753i |conjure-up.lxc profile edit default', returncode=1, stdout=b'', stderr=b"error: Failed to retrieve profile='default'\n")
```

**Comment by tvansteenburgh** [comment]
I hit something similar to this. The scenario was:

1. conjure-up kubernetes-core
2. I chose localhost
3. bootstrap failed (see attached log)
4. I quit and bootstrapped my own localhost controller to make sure that was working
5. conjure-up kubernetes-core
6. I chose localhost, and the controller I had just bootstrapped.
7. Failed in 00_pre-deploy step (see attached logs)

After looking at the logs I tried a couple things:
```
tvansteenburgh@xenial-vm:~/.cache/conjure-up/kubernetes-core/steps⟫ sed s/##MODEL##/conjure-kubernetes-core-e95/ /home/tvansteenburgh/.cache/conjure-up/kubernetes-core/steps/lxd-profile.yaml | conjure-up.lxc profile edit "juju-conjure-kubernetes-core-e95"
error: Failed to retrieve profile='juju-conjure-kubernetes-core-e95'
1 tvansteenburgh@xenial-vm:~/.cache/conjure-up/kubernetes-core/steps⟫ sed s/##MODEL##/conjure-kubernetes-core-e95/ /home/tvansteenburgh/.cache/conjure-up/kubernetes-core/steps/lxd-profile.yaml | lxc profile edit "juju-conjure-kubernetes-core-e95"
tvansteenburgh@xenial-vm:~/.cache/conjure-up/kubernetes-core/steps⟫ conjure-up.lxc version
2.14
tvansteenburgh@xenial-vm:~/.cache/conjure-up/kubernetes-core/steps⟫ lxc version
2.14
tvansteenburgh@xenial-vm:~/.cache/conjure-up/kubernetes-core/steps⟫ snap list conjure-up 
Name        Version  Rev  Developer  Notes
conjure-up  2.2.1    471  canonical  classic
```

It seems that `lxc profile edit` will create the profile if it's missing, but `conjure-up.lxc profile edit` won't?

[conjure-up.log.txt](https://github.com/conjure-up/conjure-up/files/1090281/conjure-up.log.txt)
[00_pre-deploy.err.txt](https://github.com/conjure-up/conjure-up/files/1090283/00_pre-deploy.err.txt)
[00_pre-deploy.out.txt](https://github.com/conjure-up/conjure-up/files/1090282/00_pre-deploy.out.txt)

**Comment by battlemidget** [comment]
@tvansteenburgh Can you try to reproduce with --edge?

**Comment by tvansteenburgh** [comment]
With the edge snap, it worked fine when I chose localhost and let conjure-up bootstrap a new controller. Same error as before when I try to use an existing localhost controller (plus a new, different error before that).

```
2017-06-22 17:00:38,043 [DEBUG] conjure-up/_unspecified_spell - app.py:243 - LXD version: 2.14, Juju version: 2.3-alpha1-xenial-amd64, conjure-up version: 2.3-alpha1
2017-06-22 17:00:38,055 [DEBUG] conjure-up/_unspecified_spell - app.py:299 - found spell {'key': 'kubernetes-core', 'name': 'Kubernetes Core', 'description': 'Kubernetes is an open-source platform for deploying, scaling, and operations of application containers across a cluster of hosts. This is a minimal Kubernetes cluster with intended usage for small deployments for testing and development.\n'}
2017-06-22 17:00:38,059 [DEBUG] conjure-up/kubernetes-core - download.py:60 - Path is local filesystem, copying /snap/conjure-up/498/spells/kubernetes-core to /home/tvansteenburgh/.cache/conjure-up/kubernetes-core
2017-06-22 17:00:38,079 [INFO] conjure-up/kubernetes-core - events.py:174 - Watching for shutdown
2017-06-22 17:00:38,111 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Awaiting Shutdown at conjureup/events.py:176
2017-06-22 17:00:38,112 [DEBUG] conjure-up/kubernetes-core - utils.py:390 - Pulling bundle for kubernetes-core from channel: stable
2017-06-22 17:00:39,265 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Setting Error at conjureup/events.py:143
2017-06-22 17:00:39,335 [ERROR] conjure-up/kubernetes-core - events.py:160 - Error reporting error
Traceback (most recent call last):
  File "/snap/conjure-up/498/lib/python3.6/site-packages/conjureup/events.py", line 156, in handle_exception
    'juju_version': utils.juju_version(),
  File "/snap/conjure-up/498/lib/python3.6/site-packages/conjureup/utils.py", line 216, in juju_version
    raise Exception("Could not determine Juju version.")
Exception: Could not determine Juju version.
2017-06-22 17:00:39,336 [ERROR] conjure-up/kubernetes-core - events.py:162 - Unhandled exception
Traceback (most recent call last):
  File "/snap/conjure-up/498/lib/python3.6/site-packages/conjureup/app.py", line 156, in _start
    controllers.use('clouds').render()
  File "/snap/conjure-up/498/lib/python3.6/site-packages/conjureup/controllers/clouds/gui.py", line 33, in render
    all_clouds = juju.get_clouds()
  File "/snap/conjure-up/498/lib/python3.6/site-packages/conjureup/juju.py", line 351, in get_clouds
    "Unable to list clouds: {}".format(sh.stderr.decode('utf8'))
Exception: Unable to list clouds: sh: 0: getcwd() failed: No such file or directory
ERROR getwd: no such file or directory

2017-06-22 17:00:39,338 [DEBUG] conjure-up/kubernetes-core - __init__.py:21 - Showing dialog for exception: Unable to list clouds: sh: 0: getcwd() failed: No such file or directory
ERROR getwd: no such file or directory

2017-06-22 17:01:04,093 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Setting Shutdown at conjureup/events.py:130
2017-06-22 17:01:04,094 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Received Shutdown at conjureup/events.py:176
2017-06-22 17:01:04,095 [INFO] conjure-up/kubernetes-core - events.py:180 - Shutting down
2017-06-22 17:44:55,287 [DEBUG] conjure-up/_unspecified_spell - app.py:243 - LXD version: 2.14, Juju version: 2.3-alpha1-xenial-amd64, conjure-up version: 2.3-alpha1
2017-06-22 17:44:55,305 [DEBUG] conjure-up/kubernetes-core - download.py:60 - Path is local filesystem, copying kubernetes-core to /home/tvansteenburgh/.cache/conjure-up/kubernetes-core
2017-06-22 17:44:55,311 [DEBUG] conjure-up/kubernetes-core - download.py:64 - Failed to download local spell: [Errno 2] No such file or directory: 'kubernetes-core'
2017-06-22 17:45:49,293 [DEBUG] conjure-up/_unspecified_spell - app.py:243 - LXD version: 2.14, Juju version: 2.3-alpha1-xenial-amd64, conjure-up version: 2.3-alpha1
2017-06-22 17:45:49,308 [DEBUG] conjure-up/_unspecified_spell - app.py:299 - found spell {'key': 'kubernetes-core', 'name': 'Kubernetes Core', 'description': 'Kubernetes is an open-source platform for deploying, scaling, and operations of application containers across a cluster of hosts. This is a minimal Kubernetes cluster with intended usage for small deployments for testing and development.\n'}
2017-06-22 17:45:49,311 [DEBUG] conjure-up/kubernetes-core - download.py:60 - Path is local filesystem, copying /snap/conjure-up/498/spells/kubernetes-core to /home/tvansteenburgh/.cache/conjure-up/kubernetes-core
2017-06-22 17:45:49,329 [INFO] conjure-up/kubernetes-core - events.py:174 - Watching for shutdown
2017-06-22 17:45:49,360 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Awaiting Shutdown at conjureup/events.py:176
2017-06-22 17:45:49,361 [DEBUG] conjure-up/kubernetes-core - utils.py:390 - Pulling bundle for kubernetes-core from channel: stable
2017-06-22 17:45:55,919 [DEBUG] conjure-up/kubernetes-core - utils.py:579 - Parsing 2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:bd:c3:a9 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic enp0s3
       valid_lft 80072sec preferred_lft 80072sec
    inet6 fe80::3ec8:55be:db38:f2bd/64 scope link 
       valid_lft forever preferred_lft forever
 for IPv4 address
2017-06-22 17:45:56,003 [DEBUG] conjure-up/kubernetes-core - utils.py:579 - Parsing 2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:bd:c3:a9 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic enp0s3
       valid_lft 80072sec preferred_lft 80072sec
    inet6 fe80::3ec8:55be:db38:f2bd/64 scope link 
       valid_lft forever preferred_lft forever
 for IPv4 address
2017-06-22 17:45:56,061 [DEBUG] conjure-up/kubernetes-core - common.py:93 - LXD Init: <bound method BaseLXDSetupController.set_lxd_init_auto of <conjureup.controllers.lxdsetup.gui.LXDSetupController object at 0x7f9e22d87cf8>>
2017-06-22 17:45:56,221 [DEBUG] conjure-up/kubernetes-core - common.py:93 - LXD Init: <bound method BaseLXDSetupController.set_lxc_config of <conjureup.controllers.lxdsetup.gui.LXDSetupController object at 0x7f9e22d87cf8>>
2017-06-22 17:45:56,460 [DEBUG] conjure-up/kubernetes-core - common.py:93 - LXD Init: <bound method BaseLXDSetupController.set_lxd_storage of <conjureup.controllers.lxdsetup.gui.LXDSetupController object at 0x7f9e22d87cf8>>
2017-06-22 17:45:56,497 [DEBUG] conjure-up/kubernetes-core - common.py:93 - LXD Init: functools.partial(<bound method BaseLXDSetupController.setup_bridge_network of <conjureup.controllers.lxdsetup.gui.LXDSetupController object at 0x7f9e22d87cf8>>, 'enp0s3')
2017-06-22 17:45:56,557 [DEBUG] conjure-up/kubernetes-core - common.py:93 - LXD Init: <bound method BaseLXDSetupController.setup_unused_bridge_network of <conjureup.controllers.lxdsetup.gui.LXDSetupController object at 0x7f9e22d87cf8>>
2017-06-22 17:45:56,595 [DEBUG] conjure-up/kubernetes-core - common.py:93 - LXD Init: <bound method BaseLXDSetupController.set_default_profile of <conjureup.controllers.lxdsetup.gui.LXDSetupController object at 0x7f9e22d87cf8>>
2017-06-22 17:46:01,625 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Setting Bootstrapped at conjureup/controllers/controllerpicker/common.py:40
2017-06-22 17:46:01,719 [INFO] conjure-up/kubernetes-core - gui.py:73 - Ignoring placement spec because we are deploying to LXD: ['lxd:0']
2017-06-22 17:46:01,719 [INFO] conjure-up/kubernetes-core - gui.py:73 - Ignoring placement spec because we are deploying to LXD: ['0']
2017-06-22 17:46:01,719 [INFO] conjure-up/kubernetes-core - gui.py:73 - Ignoring placement spec because we are deploying to LXD: ['0']
2017-06-22 17:46:01,720 [INFO] conjure-up/kubernetes-core - gui.py:73 - Ignoring placement spec because we are deploying to LXD: ['1']
2017-06-22 17:46:01,842 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Awaiting ModelConnected at conjureup/controllers/deploy/common.py:23
2017-06-22 17:46:02,781 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Setting ModelAvailable at conjureup/juju.py:783
2017-06-22 17:46:02,781 [INFO] conjure-up/kubernetes-core - juju.py:118 - Connecting to model test967:conjure-kubernetes-core-687...
2017-06-22 17:46:02,870 [INFO] conjure-up/kubernetes-core - websocket: connection.py:160 - Driver connected to juju wss://10.0.4.15:17070/model/98a431fe-7db4-44bf-8d1d-ede7aff873ca/api
2017-06-22 17:46:02,896 [INFO] conjure-up/kubernetes-core - websocket: connection.py:354 - Authenticated
2017-06-22 17:46:02,914 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Setting ModelConnected at conjureup/juju.py:121 in task add_model at conjureup/juju.py:784
2017-06-22 17:46:02,914 [INFO] conjure-up/kubernetes-core - juju.py:122 - Connected
2017-06-22 17:46:02,915 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Received ModelConnected at conjureup/controllers/deploy/common.py:23
2017-06-22 17:46:02,915 [INFO] conjure-up/kubernetes-core - utils.py:141 - Running step: pre-deploy.
2017-06-22 17:46:02,915 [DEBUG] conjure-up/kubernetes-core - utils.py:149 - Executing script: /home/tvansteenburgh/.cache/conjure-up/kubernetes-core/steps/00_pre-deploy
2017-06-22 17:46:03,265 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Setting Error at conjureup/events.py:143
2017-06-22 17:46:03,386 [ERROR] conjure-up/kubernetes-core - events.py:162 - Unhandled exception
Traceback (most recent call last):
  File "/snap/conjure-up/498/lib/python3.6/site-packages/conjureup/controllers/deploy/common.py", line 35, in pre_deploy
    msg_cb)
  File "/snap/conjure-up/498/lib/python3.6/site-packages/conjureup/utils.py", line 170, in run_step
    raise Exception("Failure in step {}".format(step.filename))
Exception: Failure in step 00_pre-deploy
2017-06-22 17:46:03,387 [DEBUG] conjure-up/kubernetes-core - __init__.py:21 - Showing dialog for exception: Failure in step 00_pre-deploy
2017-06-22 17:46:14,120 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Setting Shutdown at conjureup/events.py:139
2017-06-22 17:46:14,121 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Received Shutdown at conjureup/events.py:176
2017-06-22 17:46:14,121 [INFO] conjure-up/kubernetes-core - events.py:180 - Shutting down
2017-06-22 17:46:14,123 [INFO] conjure-up/kubernetes-core - events.py:188 - Disconnecting model
2017-06-22 17:46:14,129 [INFO] conjure-up/kubernetes-core - events.py:190 - Disconnected
```

**Comment by battlemidget** [comment]
I'll need to sync up with you to see how you reproduce, right now I haven't been able to. Running:

```
juju bootstrap lxd/localhost booyah
conjure-up kubernetes
```

Select localhost cloud type, then select existing `booyah` controller, pre-deploy then passes:

```
2017-06-23 01:46:52,620 [DEBUG] conjure-up/kubernetes-core - common.py:93 - LXD Init: <bound method BaseLXDSetupController.set_lxd_init_auto of <conjureup.controllers.lxdsetup.gui.LXDSetupController object at 0x7fbc94400e48>>
2017-06-23 01:46:52,664 [DEBUG] conjure-up/kubernetes-core - common.py:93 - LXD Init: <bound method BaseLXDSetupController.set_lxc_config of <conjureup.controllers.lxdsetup.gui.LXDSetupController object at 0x7fbc94400e48>>
2017-06-23 01:46:52,685 [DEBUG] conjure-up/kubernetes-core - common.py:93 - LXD Init: <bound method BaseLXDSetupController.set_lxd_storage of <conjureup.controllers.lxdsetup.gui.LXDSetupController object at 0x7fbc94400e48>>
2017-06-23 01:46:52,705 [DEBUG] conjure-up/kubernetes-core - common.py:93 - LXD Init: functools.partial(<bound method BaseLXDSetupController.setup_bridge_network of <conjureup.controllers.lxdsetup.gui.LXDSetupController object at 0x7fbc94400e48>>, 'ens3')
2017-06-23 01:46:52,726 [DEBUG] conjure-up/kubernetes-core - common.py:93 - LXD Init: <bound method BaseLXDSetupController.setup_unused_bridge_network of <conjureup.controllers.lxdsetup.gui.LXDSetupController object at 0x7fbc94400e48>>
2017-06-23 01:46:52,748 [DEBUG] conjure-up/kubernetes-core - common.py:93 - LXD Init: <bound method BaseLXDSetupController.set_default_profile of <conjureup.controllers.lxdsetup.gui.LXDSetupController object at 0x7fbc94400e48>>
2017-06-23 01:46:54,697 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Setting Bootstrapped at conjureup/controllers/controllerpicker/common.py:40
2017-06-23 01:46:54,791 [INFO] conjure-up/kubernetes-core - gui.py:73 - Ignoring placement spec because we are deploying to LXD: ['lxd:0']
2017-06-23 01:46:54,791 [INFO] conjure-up/kubernetes-core - gui.py:73 - Ignoring placement spec because we are deploying to LXD: ['0']
2017-06-23 01:46:54,792 [INFO] conjure-up/kubernetes-core - gui.py:73 - Ignoring placement spec because we are deploying to LXD: ['0']
2017-06-23 01:46:54,792 [INFO] conjure-up/kubernetes-core - gui.py:73 - Ignoring placement spec because we are deploying to LXD: ['1']
2017-06-23 01:46:54,884 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Awaiting ModelConnected at conjureup/controllers/deploy/common.py:23
2017-06-23 01:46:55,577 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Setting ModelAvailable at conjureup/juju.py:783
2017-06-23 01:46:55,577 [INFO] conjure-up/kubernetes-core - juju.py:118 - Connecting to model booyah:conjure-kubernetes-core-a7a...
2017-06-23 01:46:55,591 [INFO] conjure-up/kubernetes-core - websocket: connection.py:160 - Driver connected to juju wss://10.11.229.84:17070/model/25147b89-c661-4a81-8135-df58972ea9a8/api
2017-06-23 01:46:55,615 [INFO] conjure-up/kubernetes-core - websocket: connection.py:354 - Authenticated
2017-06-23 01:46:55,625 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Setting ModelConnected at conjureup/juju.py:121 in task add_model at conjureup/juju.py:784
2017-06-23 01:46:55,625 [INFO] conjure-up/kubernetes-core - juju.py:122 - Connected
2017-06-23 01:46:55,626 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Received ModelConnected at conjureup/controllers/deploy/common.py:23
2017-06-23 01:46:55,626 [INFO] conjure-up/kubernetes-core - utils.py:141 - Running step: pre-deploy.
2017-06-23 01:46:55,627 [DEBUG] conjure-up/kubernetes-core - utils.py:149 - Executing script: /home/ubuntu/.cache/conjure-up/kubernetes-core/steps/00_pre-deploy
2017-06-23 01:46:55,691 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Setting PreDeployComplete at conjureup/controllers/deploy/common.py:36
2017-06-23 01:47:02,112 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Setting Shutdown at conjureup/events.py:130
2017-06-23 01:47:02,113 [DEBUG] conjure-up/kubernetes-core - events.py:52 - Received Shutdown at conjureup/events.py:176
2017-06-23 01:47:02,113 [INFO] conjure-up/kubernetes-core - events.py:180 - Shutting down
2017-06-23 01:47:02,114 [INFO] conjure-up/kubernetes-core - events.py:188 - Disconnecting model
2017-06-23 01:47:02,118 [INFO] conjure-up/kubernetes-core - events.py:190 - Disconnected
```

**Comment by battlemidget** [comment]
I'd like to propose we move this bug to the next 2.2.3 milestone. Juju is releasing their 2.2.1 tonight and I'd like to get what we have fixed along with their update pushed out to stable once verified by qa.

@tvansteenburgh thoughts?

**Comment by tvansteenburgh** [comment]
@battlemidget Yeah that's fine.

**Comment by battlemidget** [comment]
https://sentry.io/canonical-pj/conjure-up/issues/298639401/

**Comment by tvansteenburgh** [comment]
Turns out this problem was happening because I was trying to use a controller bootstrapped by my deb-installed lxd, not the lxd bundled with conjure-up. That doesn't work currently!
